Repository consuldemocracy/consuldemocracy, pull requests merged in 2018-12, with the labels that each got.

#3025 improve visualization for small resolution
  app/views/admin/homepage/show.html.erb
Labels: UX

#3079 [Backport] Removes references to deleted general terms page
  config/locales/es/pages.yml
  config/sitemap.rb
  spec/lib/tasks/sitemap_spec.rb
Labels: Improvement

#3037 Add web sections to seeds
  db/seeds.rb
Labels: Tech

#3093 Add a "Reviewed by Hound" badge
  README.md
Labels: Tech

#2899 Hide Featured section on Home Page if there are no cards
  app/views/welcome/index.html.erb
  spec/features/home_spec.rb
Labels: Enhancement, UX

#3080 [Backport] UI design
  app/assets/images/language_select.png
  app/assets/stylesheets/layout.scss
  app/views/budgets/investments/milestones/_milestone.html.erb
  app/views/documents/_additional_documents.html.erb
Labels: Improvement, UX

#3081 [Backport] Featured proposals
  app/controllers/proposals_controller.rb
  config/locales/en/settings.yml
  config/locales/es/settings.yml
  db/dev_seeds/settings.rb
  db/seeds.rb
  lib/tasks/settings.rake
  spec/features/proposals_spec.rb
  spec/support/common_actions/proposals.rb
Labels: Citizen proposals, Rake

#3038 Add map to sidebar on Heading's page
  app/assets/stylesheets/layout.scss
  app/controllers/admin/budget_headings_controller.rb
  app/controllers/budgets/investments_controller.rb
  app/models/budget/heading.rb
  app/views/admin/budgets/_heading_form.html.erb
  app/views/budgets/index.html.erb
  app/views/budgets/investments/_map.html.erb
  app/views/budgets/investments/_sidebar.html.erb
  config/locales/en/admin.yml
  config/routes/budget.rb
  db/dev_seeds/budgets.rb
  db/migrate/20181109111037_add_location_to_headings.rb
  db/schema.rb
  lib/migrate_spending_proposals_to_investments.rb
  spec/factories/budgets.rb
  spec/features/admin/budgets_spec.rb
  spec/features/budgets/investments_spec.rb
  spec/features/tags/budget_investments_spec.rb
  spec/models/budget/heading_spec.rb
Labels: Budget, Enhancement

#3043 Added feature to add content block to headings in sidebar
  app/controllers/admin/budget_headings_controller.rb
  app/controllers/admin/site_customization/content_blocks_controller.rb
  app/controllers/budgets/investments_controller.rb
  app/helpers/content_blocks_helper.rb
  app/models/budget/content_block.rb
  app/models/budget/heading.rb
  app/views/admin/budgets/_group.html.erb
  app/views/admin/budgets/_heading.html.erb
  app/views/admin/budgets/_heading_form.html.erb
  app/views/admin/site_customization/content_blocks/_form.html.erb
  app/views/admin/site_customization/content_blocks/_form_content_block.html.erb
  app/views/admin/site_customization/content_blocks/_form_heading_content_block.html.erb
  app/views/admin/site_customization/content_blocks/edit.html.erb
  app/views/admin/site_customization/content_blocks/index.html.erb
  app/views/budgets/investments/_content_blocks.html.erb
  app/views/budgets/investments/_sidebar.html.erb
  config/locales/en/admin.yml
  config/locales/es/admin.yml
  config/routes/admin.rb
  db/migrate/20181108103111_add_allow_custom_content_to_headings.rb
  db/migrate/20181108142513_create_heading_content_blocks.rb
  db/schema.rb
  spec/factories/budgets.rb
  spec/features/admin/site_customization/content_blocks_spec.rb
  spec/models/budget/heading_content_block_spec.rb
Labels: Budget, Enhancement

#3104 [Backport] Widgets dev seeds
  db/dev_seeds/widgets.rb
Labels: Improvement

#3098 [Backport] New algorithm for filter 'most active'
  app/models/debate.rb
  app/models/legislation/proposal.rb
  app/models/proposal.rb
  config/locales/en/settings.yml
  config/locales/es/general.yml
  config/locales/es/settings.yml
  db/dev_seeds/settings.rb
  db/seeds.rb
  lib/score_calculator.rb
  lib/tasks/settings.rake
  lib/tasks/votes.rake
  spec/models/debate_spec.rb
  spec/models/legislation/proposal_spec.rb
  spec/models/proposal_spec.rb
Labels: Citizen proposals, Enhancement, Legislation, debates

#3105 [Backport] Draft phase on legislation processes
  app/controllers/legislation/processes_controller.rb
  app/models/legislation/process.rb
  spec/features/admin/legislation/processes_spec.rb
  spec/models/legislation/process/phase_spec.rb
  spec/models/legislation/process_spec.rb
Labels: Legislation

#3121 [Backport] Budget investments price explanation
  app/views/budgets/investments/_investment_show.html.erb
  config/locales/en/budgets.yml
  config/locales/es/budgets.yml
  spec/features/budgets/investments_spec.rb
Labels: Budget, Improvement

#3122 [Backport] Proposal create question
  app/assets/stylesheets/layout.scss
  app/views/admin/proposals/show.html.erb
  app/views/proposals/_proposal.html.erb
  app/views/proposals/show.html.erb
  spec/features/admin/poll/questions_spec.rb
  spec/features/admin/proposals_spec.rb
  spec/features/proposals_spec.rb
Labels: Admin, Citizen proposals, Improvement

#3124 [Backport] Honeypot on users sign up form
  app/controllers/users/registrations_controller.rb
  app/views/users/registrations/new.html.erb
  spec/features/registration_form_spec.rb
Labels: Bug

#3123 [Backport] Admin poll questions index
  app/views/admin/poll/questions/_questions.html.erb
  config/locales/en/admin.yml
  config/locales/es/admin.yml
  spec/features/admin/poll/questions_spec.rb
Labels: Admin, Improvement, Polls

#3131 [Backport] Documents title
  app/views/documents/_documents.html.erb
  spec/shared/features/documentable.rb
Labels: Improvement, UX
