Repository consuldemocracy/consuldemocracy, pull requests merged in 2019-10, with the labels that each got.

#3700 Stub the response to external request for available locales
  spec/shared/features/remotely_translatable.rb
Labels: Specs

#3597 Add original heading id to investments
  app/models/budget/investment.rb
  db/migrate/20190531173316_add_original_heading_id_to_investments.rb
  db/schema.rb
  lib/tasks/budgets.rake
  spec/lib/tasks/budgets_spec.rb
  spec/models/budget/investment_spec.rb
Labels: Budget, Release notes

#3602 Moderate legislation proposals
  app/assets/javascripts/application.js
  app/assets/javascripts/moderator_legislation_proposals.js
  app/controllers/concerns/polymorphic.rb
  app/controllers/moderation/legislation/proposals_controller.rb
  app/views/legislation/proposals/_actions.html.erb
  app/views/legislation/proposals/show.html.erb
  app/views/moderation/legislation/proposals/hide.js.erb
  config/routes/moderation.rb
  spec/features/moderation/legislation_proposals_spec.rb
Labels: Moderation

#3740 Remove leftover code
  app/controllers/admin/tags_controller.rb
  app/controllers/budgets/ballot/lines_controller.rb
  app/controllers/budgets/investments_controller.rb
  app/controllers/concerns/commentable_actions.rb
  app/controllers/management/budgets/investments_controller.rb
  app/controllers/sandbox_controller.rb
  app/controllers/tags_controller.rb
  app/helpers/valuation_helper.rb
  app/models/abilities/common.rb
  app/models/proposal.rb
  app/models/tag_cloud.rb
  app/views/admin/admin_notifications/index.html.erb
  app/views/admin/budgets/_form.html.erb
  app/views/admin/milestone_statuses/index.html.erb
  app/views/admin/newsletters/index.html.erb
  config/api.yml
  config/locales/en/valuation.yml
  config/locales/es/valuation.yml
  config/routes.rb
  db/dev_seeds/debates.rb
  db/dev_seeds/notifications.rb
  db/dev_seeds/proposals.rb
  db/dev_seeds/tags_categories.rb
  doc/api/api_en.md
  doc/api/api_es.md
  spec/factories/classifications.rb
  spec/features/admin/tags_spec.rb
  spec/lib/acts_as_taggable_on_spec.rb
  spec/lib/cache_spec.rb
  spec/lib/graphql_spec.rb
  spec/models/debate_spec.rb
  spec/models/proposal_spec.rb
Labels: Maintenance

#3741 Extract partials to show "sign in to vote" message
  app/helpers/links_helper.rb
  app/views/budgets/index.html.erb
  app/views/budgets/investments/_ballot.html.erb
  app/views/budgets/investments/_sidebar.html.erb
  app/views/budgets/investments/_votes.html.erb
  app/views/budgets/show.html.erb
  app/views/comments/_comment_tree.html.erb
  app/views/comments/_commentable_tree.html.erb
  app/views/comments/_votes.html.erb
  app/views/debates/_comments.html.erb
  app/views/debates/_votes.html.erb
  app/views/direct_messages/new.html.erb
  app/views/legislation/annotations/_comments_box.html.erb
  app/views/legislation/annotations/_form.html.erb
  app/views/legislation/processes/_help_gif.html.erb
  app/views/legislation/proposals/_comments.html.erb
  app/views/legislation/proposals/_featured_votes.html.erb
  app/views/legislation/proposals/_votes.html.erb
  app/views/legislation/questions/_participation_not_allowed.html.erb
  app/views/polls/_callout.html.erb
  app/views/polls/_comments.html.erb
  app/views/proposals/_comments.html.erb
  app/views/proposals/_featured_votes.html.erb
  app/views/proposals/_votes.html.erb
  app/views/shared/_login_to_comment.html.erb
  app/views/shared/_login_to_vote.html.erb
  app/views/topics/_comments.html.erb
  app/views/topics/_informative_text.html.erb
  config/locales/en/budgets.yml
  config/locales/en/community.yml
  config/locales/en/general.yml
  config/locales/en/legislation.yml
  config/locales/es/budgets.yml
  config/locales/es/community.yml
  config/locales/es/general.yml
  config/locales/es/legislation.yml
  spec/features/budgets/ballots_spec.rb
  spec/features/comments/budget_investments_spec.rb
  spec/features/comments/debates_spec.rb
  spec/features/comments/legislation_annotations_spec.rb
  spec/features/comments/legislation_questions_spec.rb
  spec/features/comments/polls_spec.rb
  spec/features/comments/proposals_spec.rb
  spec/features/comments/topics_spec.rb
  spec/features/legislation/draft_versions_spec.rb
  spec/features/polls/polls_spec.rb
  spec/support/common_actions/votes.rb
Labels: Refactoring

#3738 Add rubocop rule for multiline blocks
  .rubocop_basic.yml
  app/controllers/admin/comments_controller.rb
  app/controllers/admin/legislation/processes_controller.rb
  app/controllers/budgets/executions_controller.rb
  app/controllers/budgets/results_controller.rb
  app/controllers/concerns/commentable_actions.rb
  app/controllers/dashboard/achievements_controller.rb
  app/controllers/dashboard/polls_controller.rb
  app/controllers/legislation/processes_controller.rb
  app/controllers/remote_translations_controller.rb
  app/models/budget/investment.rb
  app/models/legislation/process.rb
  app/models/poll/answer.rb
  app/models/poll/partial_result.rb
  app/models/poll/question.rb
  spec/controllers/comments_controller_spec.rb
  spec/controllers/legislation/annotations_controller_spec.rb
  spec/controllers/legislation/answers_controller_spec.rb
  spec/factories/verifications.rb
  spec/features/admin/administrators_spec.rb
  spec/features/admin/budget_headings_spec.rb
  spec/features/admin/budget_investments_spec.rb
  spec/features/admin/download_settings_spec.rb
  spec/features/admin/settings_spec.rb
  spec/features/notifications_spec.rb
  spec/features/proposal_notifications_spec.rb
  spec/features/social_media_meta_tags_spec.rb
  spec/features/tags/budget_investments_spec.rb
  spec/features/tracking/budget_investments_spec.rb
  spec/features/valuation/budget_investments_spec.rb
  spec/lib/remote_translations/caller_spec.rb
  spec/mailers/dashboard/mailer_spec.rb
  spec/models/budget/investment_spec.rb
  spec/models/budget/phase_spec.rb
  spec/models/dashboard/action_spec.rb
  spec/models/debate_spec.rb
  spec/models/i18n_content_spec.rb
  spec/models/legislation/process_spec.rb
  spec/models/officing/residence_spec.rb
  spec/models/poll/ballot_sheet_spec.rb
  spec/models/poll/poll_spec.rb
  spec/models/proposal_spec.rb
  spec/models/signature_spec.rb
Labels: Rubocop

#3735 Add rubocop lint rules
  .rubocop_basic.yml
  app/controllers/tracking/budget_investments_controller.rb
  app/helpers/globalize_helper.rb
  app/helpers/translatable_form_helper.rb
  app/mailers/mailer.rb
  app/models/budget/result.rb
  app/models/poll/partial_result.rb
  db/dev_seeds/polls.rb
  lib/comment_tree.rb
  lib/email_digest.rb
  lib/remote_translations/microsoft/available_locales.rb
  spec/factories/administration.rb
  spec/features/admin/budget_investments_spec.rb
  spec/features/admin/dashboard/actions_spec.rb
  spec/features/admin/emails/emails_download_spec.rb
  spec/features/admin/legislation/processes_spec.rb
  spec/features/admin/widgets/cards_spec.rb
  spec/features/budgets/investments_spec.rb
  spec/lib/remote_census_api_spec.rb
  spec/models/budget/phase_spec.rb
  spec/models/budget_spec.rb
  spec/models/concerns/sluggable.rb
  spec/shared/features/remotely_translatable.rb
Labels: Rubocop

#3745 Simplify generating form fields with labels
  app/controllers/application_controller.rb
  app/controllers/management/base_controller.rb
  app/controllers/management/sessions_controller.rb
  app/helpers/documents_helper.rb
  app/helpers/images_helper.rb
  app/helpers/proposals_helper.rb
  app/helpers/translatable_form_helper.rb
  app/views/account/show.html.erb
  app/views/admin/banners/_form.html.erb
  app/views/admin/budget_headings/_form.html.erb
  app/views/admin/budget_investments/_search_form.html.erb
  app/views/admin/budget_investments/edit.html.erb
  app/views/admin/budget_phases/_form.html.erb
  app/views/admin/dashboard/actions/_form.html.erb
  app/views/admin/geozones/_form.html.erb
  app/views/admin/legislation/draft_versions/_form.html.erb
  app/views/admin/legislation/proposals/_form.html.erb
  app/views/admin/local_census_records/_form.html.erb
  app/views/admin/newsletters/_form.html.erb
  app/views/admin/poll/shifts/_form.html.erb
  app/views/admin/signature_sheets/new.html.erb
  app/views/admin/site_customization/content_blocks/_form_content_block.html.erb
  app/views/admin/site_customization/content_blocks/_form_heading_content_block.html.erb
  app/views/admin/site_customization/pages/_form.html.erb
  app/views/admin/tags/index.html.erb
  app/views/admin/valuator_groups/edit.html.erb
  app/views/admin/valuator_groups/new.html.erb
  app/views/budgets/investments/_form.html.erb
  app/views/comments/_form.html.erb
  app/views/debates/_form.html.erb
  app/views/devise/password_expired/show.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/direct_messages/new.html.erb
  app/views/legislation/annotations/_comments_box.html.erb
  app/views/legislation/proposals/_form.html.erb
  app/views/management/users/new.html.erb
  app/views/map_locations/_form_fields.html.erb
  app/views/officing/ballot_sheets/new.html.erb
  app/views/officing/results/new.html.erb
  app/views/organizations/registrations/new.html.erb
  app/views/proposal_notifications/new.html.erb
  app/views/proposals/_form.html.erb
  app/views/proposals/retire_form.html.erb
  app/views/shared/_map.html.erb
  app/views/topics/_form.html.erb
  app/views/tracking/milestones/_form.html.erb
  app/views/tracking/progress_bars/_form.html.erb
  app/views/users/registrations/edit.html.erb
  app/views/users/registrations/new.html.erb
  app/views/valuation/budget_investments/_dossier_form.html.erb
  app/views/verification/residence/new.html.erb
  app/views/verification/sms/edit.html.erb
  config/initializers/foundation_rails_helper.rb
  config/locales/en/activerecord.yml
  config/locales/en/valuation.yml
  config/locales/es/activerecord.yml
  config/locales/es/valuation.yml
  lib/consul_form_builder.rb
Labels: Refactoring

#3744 Fix booth search with blank text
  app/controllers/admin/poll/booth_assignments_controller.rb
  app/controllers/admin/poll/booths_controller.rb
  app/models/poll/booth.rb
  app/views/admin/poll/booths/index.html.erb
  spec/models/poll/booth_spec.rb
Labels: Bug

#3750 Fix typos in legacy code
  app/helpers/images_helper.rb
  config/locales/en/general.yml
  config/locales/es/admin.yml
  config/locales/es/general.yml
Labels: Bug

#3751 Remove tasks executed in version 1.0.0
  lib/migrations/reports.rb
  lib/tasks/budgets.rake
  lib/tasks/consul.rake
  lib/tasks/db.rake
  lib/tasks/legislation_proposals.rake
  lib/tasks/polls.rake
  lib/tasks/proposal_actions.rake
  lib/tasks/proposals.rake
  lib/tasks/settings.rake
  lib/tasks/stats_and_results.rake
  spec/lib/migrations/reports_spec.rb
  spec/lib/tasks/budgets_spec.rb
  spec/lib/tasks/db_spec.rb
  spec/lib/tasks/settings_spec.rb
Labels: Maintenance

#3755 Fix typos in translatable spec
  spec/features/translatable_spec.rb
Labels: Specs

#3756 Fix duplicate usernames in dev seeds task
  db/dev_seeds/users.rb
Labels: Bug

#3757 Fix duplicate given order creating answers
  app/controllers/polls/answers_controller.rb
  spec/features/polls/votation_type_spec.rb
Labels: Bug

#3754 Fix flaky officing results spec
  spec/features/officing/results_spec.rb
Labels: Specs

#3760 Fix milestone publication date comparison
  app/models/milestone.rb
  spec/models/milestone_spec.rb
  spec/models/poll/officer_spec.rb
  spec/spec_helper.rb
Labels: Bug

#3694 Use puma instead of unicorn
  Capfile
  Gemfile
  Gemfile.lock
  config/deploy.rb
  lib/capistrano/tasks/restart.cap
Labels: Installer, Release notes

#3627 Upgrade ruby to 2.4.6
  .rubocop_basic.yml
  .ruby-version
  .travis.yml
  README.md
  README_ES.md
  config/deploy.rb
Labels: Installer

#3716 Edit Budget Investment only in accepting phase
  app/controllers/admin/budget_investments_controller.rb
  app/controllers/budgets/investments_controller.rb
  app/models/abilities/administrator.rb
  app/models/abilities/common.rb
  app/views/budgets/investments/_form.html.erb
  app/views/budgets/investments/edit.html.erb
  app/views/users/_budget_investment.html.erb
  config/locales/en/management.yml
  config/locales/es/management.yml
  config/routes/budget.rb
  spec/features/budgets/investments_spec.rb
  spec/models/abilities/administrator_spec.rb
  spec/models/abilities/common_spec.rb
Labels: Budget

#3776 Don't let valuators update investments
  app/models/abilities/valuator.rb
  spec/models/abilities/valuator_spec.rb
Labels: security

#2214 Add tests for related content score
  spec/factories/classifications.rb
  spec/models/related_content_score_spec.rb
  spec/models/related_content_spec.rb
Labels: Specs

#3783 Add timestamps to budget headings and groups
  db/migrate/20191020153426_add_timestamps_to_budget_groups.rb
  db/migrate/20191020153455_add_timestamps_to_budget_headings.rb
  db/schema.rb
Labels: Budget

#3766 Use relative URLs where possible
  app/controllers/admin/poll/active_polls_controller.rb
  app/controllers/admin/widget/cards_controller.rb
  app/controllers/comments_controller.rb
  app/controllers/concerns/access_denied_handler.rb
  app/controllers/management/users_controller.rb
  app/controllers/notifications_controller.rb
  app/controllers/users/omniauth_callbacks_controller.rb
  app/controllers/users/registrations_controller.rb
  app/helpers/application_helper.rb
  app/helpers/custom_urls_helper.rb
  app/helpers/direct_uploads_helper.rb
  app/helpers/documents_helper.rb
  app/helpers/images_helper.rb
  app/views/admin/poll/active_polls/edit.html.erb
  app/views/budgets/ballot/_investment_for_sidebar.html.erb
  app/views/budgets/investments/_ballot.html.erb
  app/views/budgets/investments/index.html.erb
  app/views/dashboard/_form.html.erb
  app/views/kaminari/_first_page.html.erb
  app/views/kaminari/_last_page.html.erb
  app/views/kaminari/_next_page.html.erb
  app/views/kaminari/_page.html.erb
  app/views/kaminari/_prev_page.html.erb
  app/views/legislation/proposals/edit.html.erb
  app/views/legislation/proposals/new.html.erb
  app/views/management/proposals/new.html.erb
  app/views/proposals/edit.html.erb
  app/views/proposals/new.html.erb
  app/views/shared/_map.html.erb
  app/views/shared/_suggest.html.erb
  spec/features/admin/site_customization/documents_spec.rb
  spec/features/campaigns_spec.rb
  spec/features/proposals_spec.rb
Labels: Refactoring

#3775 Do not call CensusAPI when endpoint is not defined
  lib/census_api.rb
  spec/lib/census_caller_spec.rb
Labels: Verification

#3782 Fix investments search with numbers in their title
  app/models/budget/investment.rb
  spec/models/budget/investment_spec.rb
Labels: Bug

#3779 Use jQuery's text() instead of html() where safer
  app/assets/javascripts/banners.js
  app/assets/javascripts/globalize.js
  app/assets/javascripts/markdown_editor.js
  app/views/shared/_common_globalize_locales.html.erb
  config/locales/en/general.yml
  config/locales/es/general.yml
  spec/features/xss_spec.rb
Labels: security

#3785 Upgrade Ruby to 2.4.9
  .ruby-version
  README.md
  README_ES.md
Labels: Maintenance

#3749 Sanitize descriptions in the views
  app/helpers/application_helper.rb
  app/models/budget.rb
  app/models/budget/phase.rb
  app/models/concerns/globalizable.rb
  app/models/concerns/sanitizable.rb
  app/models/legislation/draft_version.rb
  app/models/poll/question/answer.rb
  app/views/admin/debates/show.html.erb
  app/views/admin/hidden_budget_investments/index.html.erb
  app/views/admin/hidden_debates/index.html.erb
  app/views/admin/hidden_proposals/index.html.erb
  app/views/admin/poll/questions/answers/show.html.erb
  app/views/admin/poll/questions/show.html.erb
  app/views/budgets/_phases.html.erb
  app/views/budgets/index.html.erb
  app/views/budgets/investments/_investment.html.erb
  app/views/budgets/investments/_investment_detail.erb
  app/views/budgets/show.html.erb
  app/views/dashboard/_proposed_action.html.erb
  app/views/dashboard/actions/new_request.html.erb
  app/views/dashboard/mailer/new_actions_notification_rake_created.html.erb
  app/views/dashboard/mailer/new_actions_notification_rake_published.html.erb
  app/views/debates/_debate.html.erb
  app/views/debates/show.html.erb
  app/views/legislation/draft_versions/show.html.erb
  app/views/legislation/processes/milestones.html.erb
  app/views/legislation/proposals/show.html.erb
  app/views/mailer/newsletter.html.erb
  app/views/moderation/budgets/investments/index.html.erb
  app/views/moderation/debates/index.html.erb
  app/views/moderation/proposals/index.html.erb
  app/views/polls/index.html.erb
  app/views/polls/show.html.erb
  app/views/proposals/_info.html.erb
  app/views/tracking/budget_investments/edit.html.erb
  app/views/tracking/budget_investments/show.html.erb
  app/views/welcome/_recommended_carousel.html.erb
  db/migrate/20180801140800_add_collaborative_legislation_translations.rb
  db/migrate/20191006114603_remove_html_fields_form_legislation_draft_version.rb
  db/schema.rb
  lib/consul_form_builder.rb
  spec/features/xss_spec.rb
  spec/models/budget/phase_spec.rb
  spec/models/budget_spec.rb
  spec/models/legislation/draft_version_spec.rb
  spec/shared/models/sanitizable.rb
Labels: security

#3764 Apply rubocop basic rules
  .rubocop_basic.yml
  app/controllers/admin/site_customization/content_blocks_controller.rb
  app/controllers/legislation/draft_versions_controller.rb
  app/controllers/legislation/processes_controller.rb
  app/controllers/verification/letter_controller.rb
  app/helpers/users_helper.rb
  app/helpers/welcome_helper.rb
  app/models/comment.rb
  app/models/concerns/notifiable.rb
  app/models/legislation/people_proposal.rb
  app/models/legislation/proposal.rb
  app/models/proposal.rb
  app/models/signature.rb
  app/models/user.rb
  lib/score_calculator.rb
  spec/features/budgets/investments_spec.rb
  spec/features/notifications_spec.rb
  spec/models/newsletter_spec.rb
  spec/models/poll/officer_spec.rb
  spec/models/proposal_spec.rb
  spec/spec_helper.rb
Labels: Rubocop

#3786 Remove obsolete method to recalculate counter
  config/initializers/acts_as_taggable_on.rb
  spec/lib/acts_as_taggable_on_spec.rb
Labels: Maintenance

#3286 Replace sass-rails gem by sassc-rails
  Gemfile
  Gemfile.lock
Labels: Maintenance

#3784 Reduce security risk on remote_census_api
  .rubocop.yml
  .rubocop_basic.yml
  config/locales/en/settings.yml
  config/locales/es/settings.yml
  lib/remote_census_api.rb
  spec/lib/remote_census_api_spec.rb
Labels: security

#3787 Fix adding blank comments to existing annotations
  app/controllers/legislation/annotations_controller.rb
  spec/features/legislation/draft_versions_spec.rb
Labels: Bug

#3790 Use rubocop 0.74 with code climate
  .codeclimate.yml
Labels: Rubocop

#3791 Fix warnings in several environments
  Gemfile.lock
  app/models/budget.rb
  app/models/legislation/process.rb
  app/models/poll/shift.rb
  spec/features/admin/poll/questions/answers/documents/documents_spec.rb
  spec/features/budget_polls/budgets_spec.rb
Labels: Maintenance

#3792 Apply rubocop FindBy rules
  .rubocop.yml
  .rubocop_basic.yml
  app/models/budget/ballot.rb
  app/models/budget/phase.rb
  app/models/concerns/relationable.rb
  app/models/concerns/sluggable.rb
  app/models/legislation/question.rb
  app/models/newsletter.rb
  app/models/notification.rb
  app/models/officing/residence.rb
  app/models/poll/ballot.rb
  app/models/poll/booth.rb
  app/models/poll/voter.rb
  app/models/setting.rb
  app/models/signature.rb
  app/models/user.rb
  app/models/verification/email.rb
  app/models/verification/management/email.rb
  app/models/verification/residence.rb
  app/models/widget/feed.rb
  config/initializers/i18n_translation.rb
  db/pages/accessibility.rb
  db/pages/conditions.rb
  db/pages/faq.rb
  db/pages/privacy.rb
  db/pages/welcome_level_three_verified.rb
  db/pages/welcome_level_two_verified.rb
  db/pages/welcome_not_verified.rb
  spec/features/admin/site_customization/pages_spec.rb
Labels: Rubocop

#3797 Use a block to travel in time in specs
  spec/features/proposal_notifications_spec.rb
Labels: Specs

#3801 Use the shared partial to render errors
  app/views/admin/banners/_errors.html.erb
  app/views/admin/banners/_form.html.erb
  app/views/admin/geozones/_errors.html.erb
  app/views/admin/geozones/_form.html.erb
  app/views/admin/legislation/draft_versions/_form.html.erb
  app/views/admin/legislation/processes/_form.html.erb
  app/views/admin/legislation/proposals/_form.html.erb
  app/views/admin/legislation/questions/_form.html.erb
  app/views/admin/site_customization/content_blocks/_form_content_block.html.erb
  app/views/admin/site_customization/content_blocks/_form_heading_content_block.html.erb
  app/views/admin/site_customization/pages/_form.html.erb
  config/locales/en/admin.yml
  config/locales/en/general.yml
  config/locales/es/admin.yml
  config/locales/es/general.yml
Labels: Refactoring

#3802 Make HTML areas independent of CKEditor
  app/assets/javascripts/application.js
  app/assets/javascripts/html_editor.js
  app/assets/stylesheets/layout.scss
  app/views/admin/budget_investments/edit.html.erb
  app/views/admin/budget_phases/_form.html.erb
  app/views/admin/dashboard/actions/_form.html.erb
  app/views/admin/legislation/homepages/_form.html.erb
  app/views/admin/legislation/milestones/_summary_form.html.erb
  app/views/admin/newsletters/_form.html.erb
  app/views/admin/poll/active_polls/_form.html.erb
  app/views/admin/poll/questions/answers/_form.html.erb
  app/views/admin/site_customization/pages/_form.html.erb
  app/views/budgets/investments/_form.html.erb
  app/views/dashboard/polls/_question_answer_fields.html.erb
  app/views/debates/_form.html.erb
  app/views/layouts/admin.html.erb
  app/views/layouts/devise.html.erb
  app/views/layouts/mailer.html.erb
  app/views/layouts/management.html.erb
  app/views/legislation/proposals/_form.html.erb
  app/views/proposals/_form.html.erb
  lib/consul_form_builder.rb
  spec/features/admin/site_customization/pages_spec.rb
  spec/features/admin/translatable_spec.rb
  spec/features/translatable_spec.rb
  spec/support/matchers/have_ckeditor.rb
Labels: Refactoring

#3798 Apply Rails/InverseOf rubocop rule
  .rubocop.yml
  .rubocop_basic.yml
  app/models/activity.rb
  app/models/budget/investment.rb
  app/models/budget/investment/change_log.rb
  app/models/budget/phase.rb
  app/models/comment.rb
  app/models/concerns/documentable.rb
  app/models/concerns/flaggable.rb
  app/models/concerns/followable.rb
  app/models/concerns/galleryable.rb
  app/models/concerns/imageable.rb
  app/models/concerns/linkable.rb
  app/models/concerns/milestoneable.rb
  app/models/concerns/relationable.rb
  app/models/concerns/reportable.rb
  app/models/concerns/stats_versionable.rb
  app/models/dashboard/executed_action.rb
  app/models/debate.rb
  app/models/direct_message.rb
  app/models/geozones_poll.rb
  app/models/legislation/annotation.rb
  app/models/legislation/answer.rb
  app/models/legislation/draft_version.rb
  app/models/legislation/people_proposal.rb
  app/models/legislation/process.rb
  app/models/legislation/proposal.rb
  app/models/legislation/question.rb
  app/models/legislation/question_option.rb
  app/models/newsletter.rb
  app/models/poll.rb
  app/models/poll/answer.rb
  app/models/poll/ballot.rb
  app/models/poll/ballot_sheet.rb
  app/models/poll/booth.rb
  app/models/poll/booth_assignment.rb
  app/models/poll/officer.rb
  app/models/poll/pair_answer.rb
  app/models/poll/partial_result.rb
  app/models/poll/question.rb
  app/models/poll/question/answer.rb
  app/models/poll/question/answer/video.rb
  app/models/poll/recount.rb
  app/models/proposal.rb
  app/models/proposal_notification.rb
  app/models/related_content.rb
  app/models/signature_sheet.rb
  app/models/site_customization/page.rb
  app/models/topic.rb
  app/models/user.rb
  app/models/votation_set_answer.rb
  app/models/widget/card.rb
  db/migrate/20191024025634_rename_rigth_id_to_right_id.rb
  db/schema.rb
Labels: Rubocop

#3799 Merge basic and standard rubocop files in one file
  .hound.yml
  .rubocop.yml
  .rubocop_basic.yml
  app/controllers/debates_controller.rb
  app/models/budget/phase.rb
  app/models/poll/question/answer.rb
  spec/controllers/comments_controller_spec.rb
  spec/controllers/legislation/annotations_controller_spec.rb
  spec/controllers/legislation/answers_controller_spec.rb
  spec/features/admin/admin_notifications_spec.rb
  spec/features/admin/budget_investments_spec.rb
  spec/features/admin/emails/emails_download_spec.rb
  spec/features/admin/emails/newsletters_spec.rb
  spec/features/legislation/questions_spec.rb
  spec/lib/email_digests_spec.rb
  spec/models/budget/investment_spec.rb
  spec/models/budget/phase_spec.rb
  spec/models/concerns/globalizable.rb
  spec/models/proposal_spec.rb
Labels: Rubocop

#3800 Add missing spanish translations
  config/locales/en/activemodel.yml
  config/locales/es/general.yml
Labels: Bug

#3805 Remove people proposal model
  app/models/comment.rb
  app/models/legislation/people_proposal.rb
  app/models/legislation/process.rb
  app/models/setting.rb
  app/models/user.rb
  db/dev_seeds.rb
  db/dev_seeds/legislation_people_proposals.rb
  db/dev_seeds/legislation_processes.rb
  db/migrate/20191030011813_remove_people_proposal_phase_from_legislation_process.rb
  db/migrate/20191030011956_drop_legislation_people_proposals.rb
  db/schema.rb
  spec/factories/legislations.rb
  spec/models/legislation/people_proposals_spec.rb
Labels: Maintenance

#3781 Don't send newsletters to unconfirmed accounts
  lib/user_segments.rb
  spec/models/newsletter_spec.rb
Labels: Bug
