Repository consuldemocracy/consuldemocracy, pull requests merged in 2019-09, with the labels that each got.

#3652 Remove unused JavaScript code
  app/assets/javascripts/allow_participation.js.coffee
  app/assets/javascripts/annotatable.js.coffee
  app/assets/javascripts/application.js
  app/assets/javascripts/banners.js.coffee
  app/assets/javascripts/columns_selector.js.coffee
  app/assets/javascripts/comments.js.coffee
  app/assets/javascripts/cookies.js.coffee
  app/assets/javascripts/dashboard_graphs.js
  app/assets/javascripts/documentable.js.coffee
  app/assets/javascripts/forms.js.coffee
  app/assets/javascripts/gettext.js.coffee
  app/assets/javascripts/imageable.js.coffee
  app/assets/javascripts/legislation_allegations.js.coffee
  app/assets/javascripts/legislation_annotatable.js.coffee
  app/assets/javascripts/managers.js.coffee
  app/assets/javascripts/polls.js.coffee
  app/assets/javascripts/prevent_double_submission.js.coffee
  app/assets/javascripts/sortable.js.coffee
  app/assets/javascripts/stats.js.coffee
  app/assets/javascripts/tracks.js.coffee
  app/assets/javascripts/tree_navigator.js.coffee
  app/assets/javascripts/users.js.coffee
  app/assets/javascripts/valuation_budget_investment_form.js.coffee
  app/assets/javascripts/votations.js.coffee
  app/assets/javascripts/votes.js.coffee
  app/assets/javascripts/watch_form_changes.js.coffee
  app/assets/stylesheets/participation.scss
  spec/features/polls/voter_spec.rb
Labels: Refactoring

#3654 Fix JavaScript Lint errors
  app/assets/javascripts/advanced_search.js.coffee
  app/assets/javascripts/answers.js.coffee
  app/assets/javascripts/dashboard_graphs.js
  app/assets/javascripts/polls_admin.js.coffee
  app/views/shared/_locale_switcher.html.erb
  spec/features/admin/poll/shifts_spec.rb
Labels: Bug

#3656 Fix text confirming investment heading support
  app/views/budgets/investments/_votes.html.erb
  config/locales/en/budgets.yml
  spec/features/budgets/votes_spec.rb
Labels: Bug

#3537 Set locales in test environment to avoid failed specs
  config/environments/test.rb
  spec/features/remote_translations_spec.rb
  spec/rails_helper.rb
Labels: Specs

#3661 Fix table layout after selecting an investment
  app/assets/javascripts/columns_selector.js
  app/views/admin/budget_investments/toggle_selection.js.erb
  spec/features/admin/budget_investments_spec.rb
Labels: Bug, UX

#3693 Add search form on admin booths
  app/controllers/admin/poll/booths_controller.rb
  app/views/admin/poll/booths/index.html.erb
  app/views/admin/shared/_booth_search.html.erb
  config/locales/en/admin.yml
  spec/features/admin/poll/booths_spec.rb
  spec/features/admin/poll/shifts_spec.rb
Labels: Admin

#3698 Fix share message interpolation variable
  config/locales/ar/budgets.yml
  config/locales/gl/budgets.yml
  config/locales/so-SO/budgets.yml
  config/locales/sq-AL/budgets.yml
  config/locales/val/budgets.yml
  config/locales/zh-CN/budgets.yml
Labels: Bug

#3717 Remove attachment useless code to show errors
  app/helpers/documents_helper.rb
  app/helpers/images_helper.rb
Labels: Rubocop

#3702 Simplify after blocks in specs
  spec/controllers/concerns/remotely_translatable_spec.rb
  spec/controllers/debates_controller_spec.rb
  spec/controllers/installation_controller_spec.rb
  spec/controllers/remote_translation_controller_spec.rb
  spec/features/account_spec.rb
  spec/features/admin/budget_groups_spec.rb
  spec/features/admin/budget_headings_spec.rb
  spec/features/admin/budget_investments_spec.rb
  spec/features/admin/debates_spec.rb
  spec/features/admin/legislation/processes_spec.rb
  spec/features/admin/settings_spec.rb
  spec/features/admin/signature_sheets_spec.rb
  spec/features/budgets/investments_spec.rb
  spec/features/comments/topics_spec.rb
  spec/features/communities_spec.rb
  spec/features/debates_spec.rb
  spec/features/emails_spec.rb
  spec/features/home_spec.rb
  spec/features/management/document_verifications_spec.rb
  spec/features/moderation_spec.rb
  spec/features/notifications_spec.rb
  spec/features/officing/residence_spec.rb
  spec/features/proposal_notifications_spec.rb
  spec/features/proposals_spec.rb
  spec/features/remote_translations_spec.rb
  spec/features/social_media_meta_tags_spec.rb
  spec/features/welcome_spec.rb
  spec/helpers/signature_sheets_helper_spec.rb
  spec/lib/tasks/dashboards_spec.rb
  spec/mailers/dashboard/mailer_spec.rb
  spec/models/budget_spec.rb
  spec/models/concerns/globalizable.rb
  spec/models/debate_spec.rb
  spec/models/newsletter_spec.rb
  spec/models/officing/residence_spec.rb
  spec/models/proposal_spec.rb
  spec/models/remote_translation_spec.rb
  spec/models/signature_sheet_spec.rb
  spec/models/signature_spec.rb
  spec/models/verification/management/document_spec.rb
  spec/requests/dashboard/successful_supports_spec.rb
  spec/shared/features/documentable.rb
  spec/shared/features/nested_documentable.rb
  spec/shared/features/nested_imageable.rb
  spec/shared/features/remotely_translatable.rb
  spec/shared/models/map_validations.rb
  spec/spec_helper.rb
  spec/support/verifiable.rb
Labels: Specs

#3715 Apply explict RSpec/DescribedClass rubocop rule
  .rubocop_basic.yml
  spec/lib/age_spec.rb
  spec/lib/census_api_spec.rb
  spec/lib/census_caller_spec.rb
  spec/lib/email_digests_spec.rb
  spec/lib/graph_ql/api_types_creator_spec.rb
  spec/lib/graph_ql/query_type_creator_spec.rb
  spec/lib/local_census_spec.rb
  spec/lib/manager_authenticator_spec.rb
  spec/lib/remote_census_api_spec.rb
  spec/lib/remote_translations/caller_spec.rb
  spec/lib/remote_translations/microsoft/client_spec.rb
  spec/lib/tag_sanitizer_spec.rb
  spec/lib/user_segments_spec.rb
  spec/lib/wysiwyg_sanitizer_spec.rb
  spec/mailers/devise_mailer_spec.rb
  spec/mailers/mailer_spec.rb
  spec/models/activity_spec.rb
  spec/models/ahoy/data_source_spec.rb
  spec/models/budget/ballot/line_spec.rb
  spec/models/budget/investment_spec.rb
  spec/models/budget/result_spec.rb
  spec/models/budget_spec.rb
  spec/models/comment_spec.rb
  spec/models/dashboard/action_spec.rb
  spec/models/debate_spec.rb
  spec/models/direct_message_spec.rb
  spec/models/flag_spec.rb
  spec/models/legislation/question_spec.rb
  spec/models/notification_spec.rb
  spec/models/officing/residence_spec.rb
  spec/models/organization_spec.rb
  spec/models/poll/booth_spec.rb
  spec/models/poll/pair_answer_spec.rb
  spec/models/poll/poll_spec.rb
  spec/models/poll/shift_spec.rb
  spec/models/poll/voter_spec.rb
  spec/models/proposal_notification_spec.rb
  spec/models/proposal_spec.rb
  spec/models/related_content_spec.rb
  spec/models/setting_spec.rb
  spec/models/tag_cloud_spec.rb
  spec/models/user_spec.rb
  spec/models/verification/management/document_spec.rb
  spec/models/verification/management/email_spec.rb
  spec/models/verification/residence_spec.rb
  spec/models/verification/sms_spec.rb
  spec/models/vote_spec.rb
Labels: Rubocop

#3714 Simplify investments creation in specs
  spec/features/admin/budget_investments_spec.rb
  spec/features/admin/budgets_spec.rb
  spec/features/admin/download_settings_spec.rb
  spec/features/admin/hidden_budget_investments_spec.rb
  spec/features/admin/system_emails_spec.rb
  spec/features/budget_polls/voter_spec.rb
  spec/features/budgets/budgets_spec.rb
  spec/features/budgets/stats_spec.rb
  spec/features/comments/budget_investments_valuation_spec.rb
  spec/features/emails_spec.rb
  spec/features/moderation/budget_investments_spec.rb
  spec/features/tracking/budget_investments_spec.rb
  spec/features/valuation/budget_investments_spec.rb
  spec/models/budget/ballot_spec.rb
  spec/models/budget/investment_spec.rb
  spec/models/budget/result_spec.rb
  spec/models/budget_spec.rb
Labels: Specs

#3713 Make translatable specs faster
  spec/factories/milestones.rb
  spec/factories/notifications.rb
  spec/factories/proposals.rb
  spec/features/admin/admin_notifications_spec.rb
  spec/features/admin/banners_spec.rb
  spec/features/admin/budget_groups_spec.rb
  spec/features/admin/budget_headings_spec.rb
  spec/features/admin/budget_investment_milestones_spec.rb
  spec/features/admin/budget_investments_spec.rb
  spec/features/admin/budget_phases_spec.rb
  spec/features/admin/budgets_spec.rb
  spec/features/admin/legislation/draft_versions_spec.rb
  spec/features/admin/legislation/processes_spec.rb
  spec/features/admin/legislation/questions_spec.rb
  spec/features/admin/poll/active_polls_spec.rb
  spec/features/admin/poll/polls_spec.rb
  spec/features/admin/poll/questions/answers/answers_spec.rb
  spec/features/admin/poll/questions_spec.rb
  spec/features/admin/site_customization/information_texts_spec.rb
  spec/features/admin/site_customization/pages_spec.rb
  spec/features/admin/translatable_spec.rb
  spec/features/admin/widgets/cards_spec.rb
  spec/features/budgets/investments_spec.rb
  spec/features/debates_spec.rb
  spec/features/localization_spec.rb
  spec/features/proposals_spec.rb
  spec/features/translatable_spec.rb
  spec/models/banner_spec.rb
  spec/models/budget/group_spec.rb
  spec/models/budget/heading_spec.rb
  spec/models/budget/investment_spec.rb
  spec/models/budget/phase_spec.rb
  spec/models/budget_spec.rb
  spec/models/concerns/globalizable.rb
  spec/models/i18n_content_spec.rb
  spec/models/legislation/draft_version_spec.rb
  spec/models/legislation/process_spec.rb
  spec/models/legislation/question_option_spec.rb
  spec/models/legislation/question_spec.rb
  spec/models/milestone_spec.rb
  spec/models/poll/active_poll_spec.rb
  spec/models/poll/poll_spec.rb
  spec/models/poll/question/answer_spec.rb
  spec/models/poll/question_spec.rb
  spec/models/progress_bar_spec.rb
  spec/models/proposal_spec.rb
  spec/models/site_customization/page_spec.rb
  spec/models/widget/card_spec.rb
  spec/shared/features/edit_translatable.rb
  spec/shared/features/new_translatable.rb
  spec/spec_helper.rb
  spec/support/common_actions/translations.rb
Labels: Specs

#3718 Remove unused and obsolete code
  app/controllers/admin/poll/booth_assignments_controller.rb
  app/controllers/polls_controller.rb
  app/models/abilities/tracker.rb
  config/api.yml
  config/locales/en/admin.yml
  config/locales/es/admin.yml
  spec/features/admin/admin_notifications_spec.rb
  spec/features/admin/budget_investments_spec.rb
  spec/features/admin/emails/newsletters_spec.rb
  spec/features/admin/poll/shifts_spec.rb
  spec/features/admin/stats_spec.rb
  spec/features/admin/system_emails_spec.rb
  spec/features/budgets/investments_spec.rb
  spec/features/direct_messages_spec.rb
  spec/features/polls/answers_spec.rb
  spec/features/polls/voter_spec.rb
  spec/features/proposals_spec.rb
  spec/lib/graphql_spec.rb
  spec/models/poll/shift_spec.rb
  spec/models/signature_spec.rb
Labels: Refactoring

#3719 Remove redundant code
  app/models/i18n_content.rb
  config/initializers/i18n_translation.rb
  spec/features/admin/poll/questions/answers/documents/documents_spec.rb
  spec/features/admin/poll/questions/answers/images/images_spec.rb
  spec/features/budget_polls/officing_spec.rb
  spec/features/budgets/ballots_spec.rb
  spec/features/polls/polls_spec.rb
  spec/features/proposal_notifications_spec.rb
  spec/lib/reply_email_spec.rb
  spec/models/i18n_content_spec.rb
  spec/models/poll/shift_spec.rb
Labels: Refactoring

#3720 Update featured proposals specs
  spec/features/official_positions_spec.rb
  spec/features/proposals_spec.rb
  spec/features/tags/budget_investments_spec.rb
  spec/features/tags/proposals_spec.rb
  spec/features/votes_spec.rb
Labels: Specs

#3721 Simplify testing array contents
  spec/features/admin/emails/emails_download_spec.rb
  spec/lib/acts_as_paranoid_aliases_spec.rb
  spec/lib/email_digests_spec.rb
  spec/models/activity_spec.rb
  spec/models/budget/group_spec.rb
  spec/models/budget/heading_spec.rb
  spec/models/budget/investment_spec.rb
  spec/models/comment_spec.rb
  spec/models/community_spec.rb
  spec/models/custom/verification/residence_spec.rb
  spec/models/debate_spec.rb
  spec/models/document_spec.rb
  spec/models/newsletter_spec.rb
  spec/models/notification_spec.rb
  spec/models/officing/residence_spec.rb
  spec/models/organization_spec.rb
  spec/models/poll/ballot_spec.rb
  spec/models/poll/booth_spec.rb
  spec/models/poll/officer_spec.rb
  spec/models/poll/poll_spec.rb
  spec/models/poll/voter_spec.rb
  spec/models/proposal_spec.rb
  spec/models/related_content_spec.rb
  spec/models/user_spec.rb
  spec/models/verification/management/document_spec.rb
  spec/models/verification/residence_spec.rb
Labels: Specs

#3722 Use traits to simplify specs
  spec/controllers/application_controller_spec.rb
  spec/factories/budgets.rb
  spec/factories/milestones.rb
  spec/factories/polls.rb
  spec/factories/proposals.rb
  spec/factories/users.rb
  spec/features/admin/budget_groups_spec.rb
  spec/features/admin/budget_headings_spec.rb
  spec/features/admin/budget_investments_spec.rb
  spec/features/admin/budgets_spec.rb
  spec/features/admin/change_log_spec.rb
  spec/features/admin/download_settings_spec.rb
  spec/features/admin/poll/booth_assigments_spec.rb
  spec/features/admin/poll/polls_spec.rb
  spec/features/admin/stats_spec.rb
  spec/features/budget_polls/ballot_sheets_spec.rb
  spec/features/budget_polls/budgets_spec.rb
  spec/features/budget_polls/polls_spec.rb
  spec/features/budget_polls/questions_spec.rb
  spec/features/budgets/ballots_spec.rb
  spec/features/budgets/executions_spec.rb
  spec/features/budgets/investments_spec.rb
  spec/features/budgets/votes_spec.rb
  spec/features/dashboard/polls_spec.rb
  spec/features/emails_spec.rb
  spec/features/management/budget_investments_spec.rb
  spec/features/polls/polls_spec.rb
  spec/features/polls/votation_type_spec.rb
  spec/features/proposal_notifications_spec.rb
  spec/features/proposals_spec.rb
  spec/features/users_spec.rb
  spec/features/valuation/budget_investments_spec.rb
  spec/lib/graphql_spec.rb
  spec/models/abilities/administrator_spec.rb
  spec/models/abilities/common_spec.rb
  spec/models/abilities/everyone_spec.rb
  spec/models/abilities/valuator_spec.rb
  spec/models/budget/investment_spec.rb
  spec/models/budget/stats_spec.rb
  spec/models/budget_spec.rb
  spec/models/newsletter_spec.rb
  spec/models/poll/answer_spec.rb
  spec/models/poll/ballot_sheet_spec.rb
  spec/models/poll/poll_spec.rb
  spec/models/poll/stats_spec.rb
  spec/shared/features/admin_milestoneable.rb
Labels: Specs

#3723 Simplify data creation in poll factories
  spec/factories/polls.rb
  spec/features/admin/poll/booth_assigments_spec.rb
  spec/features/admin/poll/booths_spec.rb
  spec/features/admin/poll/officer_assignments_spec.rb
  spec/features/admin/poll/shifts_spec.rb
  spec/features/budget_polls/ballot_sheets_spec.rb
  spec/features/budget_polls/voter_spec.rb
  spec/features/officing/booth_spec.rb
  spec/features/officing/residence_spec.rb
  spec/features/officing/results_spec.rb
  spec/features/officing/voters_spec.rb
  spec/features/polls/polls_spec.rb
  spec/features/polls/voter_spec.rb
  spec/models/poll/booth_spec.rb
  spec/models/poll/officer_spec.rb
Labels: Specs

#3724 Remove isolated useless assignments
  app/controllers/valuation/budget_investments_controller.rb
  app/helpers/welcome_helper.rb
  spec/features/account_spec.rb
  spec/features/admin/admin_notifications_spec.rb
  spec/features/admin/emails/newsletters_spec.rb
  spec/features/admin/homepage/homepage_spec.rb
  spec/features/admin/legislation/draft_versions_spec.rb
  spec/features/admin/legislation/questions_spec.rb
  spec/features/admin/poll/booth_assigments_spec.rb
  spec/features/admin/site_customization/content_blocks_spec.rb
  spec/features/admin/stats_spec.rb
  spec/features/admin/tags_spec.rb
  spec/features/admin/translatable_spec.rb
  spec/features/admin/valuator_groups_spec.rb
  spec/features/admin/verifications_spec.rb
  spec/features/admin_spec.rb
  spec/features/budget_polls/officing_spec.rb
  spec/features/budget_polls/polls_spec.rb
  spec/features/budget_polls/questions_spec.rb
  spec/features/budgets/ballots_spec.rb
  spec/features/budgets/budgets_spec.rb
  spec/features/budgets/investments_spec.rb
  spec/features/budgets/votes_spec.rb
  spec/features/comments/budget_investments_spec.rb
  spec/features/comments/topics_spec.rb
  spec/features/debates_spec.rb
  spec/features/home_spec.rb
  spec/features/management/budget_investments_spec.rb
  spec/features/notifications_spec.rb
  spec/features/officing/results_spec.rb
  spec/features/officing/voters_spec.rb
  spec/features/officing_spec.rb
  spec/features/polls/polls_spec.rb
  spec/features/proposals_spec.rb
  spec/features/site_customization/custom_pages_spec.rb
  spec/features/tags/budget_investments_spec.rb
  spec/features/tags/debates_spec.rb
  spec/features/tags/proposals_spec.rb
  spec/features/tags_spec.rb
  spec/lib/graphql_spec.rb
  spec/lib/user_segments_spec.rb
  spec/models/debate_spec.rb
  spec/models/direct_message_spec.rb
  spec/models/i18n_content_spec.rb
  spec/models/legislation/process_spec.rb
  spec/models/newsletter_spec.rb
  spec/models/proposal_notification_spec.rb
  spec/shared/features/mappable.rb
  spec/shared/features/nested_documentable.rb
  spec/shared/features/nested_imageable.rb
  spec/shared/features/notifiable_in_app.rb
  spec/shared/features/relationable.rb
Labels: Rubocop

#3726 Add more tests to calculate winners
  spec/models/budget/result_spec.rb
Labels: Specs

#3729 Fix extra records in investments and polls
  app/models/poll.rb
  app/models/valuator.rb
  spec/models/poll/poll_spec.rb
  spec/models/valuator_spec.rb
Labels: Bug

#3730 Remove obsolete code
  app/helpers/stats_helper.rb
  app/models/budget/investment.rb
  spec/controllers/admin/api/stats_controller_spec.rb
  spec/factories/classifications.rb
  spec/factories/legislations.rb
  spec/features/admin/budget_investments_spec.rb
  spec/features/admin/valuator_groups_spec.rb
  spec/features/budgets/ballots_spec.rb
  spec/features/budgets/executions_spec.rb
  spec/features/budgets/investments_spec.rb
  spec/features/budgets/votes_spec.rb
  spec/features/comments/budget_investments_spec.rb
  spec/features/comments/legislation_questions_spec.rb
  spec/features/communities_spec.rb
  spec/features/debates_spec.rb
  spec/features/emails_spec.rb
  spec/features/legislation/proposals_spec.rb
  spec/features/legislation/resume_spec.rb
  spec/features/management/budget_investments_spec.rb
  spec/features/polls/polls_spec.rb
  spec/features/proposal_notifications_spec.rb
  spec/features/proposals_spec.rb
  spec/features/topics_spec.rb
  spec/features/valuation/budget_investments_spec.rb
  spec/models/budget/investment_spec.rb
  spec/models/direct_message_spec.rb
  spec/models/poll/officer_spec.rb
  spec/models/proposal_spec.rb
  spec/requests/dashboard/successful_supports_spec.rb
  spec/shared/features/notifiable_in_app.rb
Labels: Refactoring

#3731 Test exact array contents where possible
  spec/features/budgets/investments_spec.rb
  spec/helpers/geozones_helper_spec.rb
  spec/lib/acts_as_taggable_on_spec.rb
  spec/lib/email_digests_spec.rb
  spec/lib/user_segments_spec.rb
  spec/models/budget/ballot/line_spec.rb
  spec/models/budget/investment_spec.rb
  spec/models/comment_spec.rb
  spec/models/debate_spec.rb
  spec/models/legislation/process_spec.rb
  spec/models/local_census_record_spec.rb
  spec/models/milestone_spec.rb
  spec/models/notification_spec.rb
  spec/models/poll/booth_spec.rb
  spec/models/poll/officer_spec.rb
  spec/models/poll/pair_answer_spec.rb
  spec/models/poll/poll_spec.rb
  spec/models/proposal_notification_spec.rb
  spec/models/proposal_spec.rb
  spec/models/tag_cloud_spec.rb
  spec/models/topic_spec.rb
  spec/models/user_spec.rb
  spec/models/vote_spec.rb
  spec/models/widget/card_spec.rb
  spec/support/verifiable.rb
Labels: Specs

#3732 Simplify creating associations in specs
  spec/factories/budgets.rb
  spec/factories/classifications.rb
  spec/factories/comments.rb
  spec/factories/debates.rb
  spec/factories/milestones.rb
  spec/factories/notifications.rb
  spec/factories/polls.rb
  spec/factories/proposals.rb
  spec/factories/users.rb
  spec/features/admin/homepage/homepage_spec.rb
  spec/features/admin/poll/booth_assigments_spec.rb
  spec/features/admin/poll/officer_assignments_spec.rb
  spec/features/admin/stats_spec.rb
  spec/features/admin/system_emails_spec.rb
  spec/features/budgets/ballots_spec.rb
  spec/features/budgets/executions_spec.rb
  spec/features/budgets/investments_spec.rb
  spec/features/budgets/votes_spec.rb
  spec/features/debates_spec.rb
  spec/features/emails_spec.rb
  spec/features/home_spec.rb
  spec/features/management/budget_investments_spec.rb
  spec/features/notifications_spec.rb
  spec/features/officing/results_spec.rb
  spec/features/polls/polls_spec.rb
  spec/features/proposal_notifications_spec.rb
  spec/features/proposals_spec.rb
  spec/features/stats_spec.rb
  spec/features/topics_spec.rb
  spec/features/users_spec.rb
  spec/features/votes_spec.rb
  spec/lib/email_digests_spec.rb
  spec/lib/graphql_spec.rb
  spec/models/budget/ballot_spec.rb
  spec/models/budget/investment_spec.rb
  spec/models/budget/stats_spec.rb
  spec/models/debate_spec.rb
  spec/models/poll/officer_spec.rb
  spec/models/poll/voter_spec.rb
  spec/models/proposal_spec.rb
  spec/models/signature_spec.rb
  spec/models/tag_spec.rb
  spec/models/user_spec.rb
  spec/models/vote_spec.rb
  spec/shared/features/followable.rb
Labels: Specs

#3725 Check page content from the user's perspective
  app/views/admin/budget_headings/index.html.erb
  spec/controllers/application_controller_spec.rb
  spec/features/admin/budget_headings_spec.rb
  spec/features/admin/poll/polls_spec.rb
  spec/features/admin/poll/questions/answers/answers_spec.rb
  spec/features/admin/settings_spec.rb
  spec/features/admin/tags_spec.rb
  spec/features/budgets/ballots_spec.rb
  spec/features/budgets/investments_spec.rb
  spec/features/debates_spec.rb
  spec/features/proposals_spec.rb
  spec/features/tags/budget_investments_spec.rb
  spec/features/tags/debates_spec.rb
  spec/features/tags/proposals_spec.rb
  spec/lib/graphql_spec.rb
  spec/models/budget/result_spec.rb
  spec/models/budget_spec.rb
  spec/support/common_actions/budgets.rb
Labels: Specs

#3727 Simplify valuator factories
  spec/factories/budgets.rb
  spec/features/admin/budget_investments_spec.rb
  spec/features/comments/budget_investments_valuation_spec.rb
  spec/features/emails_spec.rb
  spec/features/valuation/budget_investments_spec.rb
  spec/models/abilities/valuator_spec.rb
  spec/models/budget/investment_spec.rb
  spec/models/valuator_spec.rb
Labels: Specs

#3728 Use `let` to remove duplication in specs
  spec/features/admin/valuator_groups_spec.rb
  spec/features/legislation/draft_versions_spec.rb
  spec/lib/email_digests_spec.rb
  spec/models/poll/voter_spec.rb
Labels: Specs

#3734 Fix remaining unused variables warnings
  spec/controllers/admin/api/stats_controller_spec.rb
  spec/factories/budgets.rb
  spec/features/admin/budget_investments_spec.rb
  spec/features/admin/legislation/draft_versions_spec.rb
  spec/features/admin/poll/booth_assigments_spec.rb
  spec/features/admin/poll/questions/answers/answers_spec.rb
  spec/features/admin/poll/shifts_spec.rb
  spec/features/budgets/ballots_spec.rb
  spec/features/budgets/executions_spec.rb
  spec/features/budgets/investments_spec.rb
  spec/features/communities_spec.rb
  spec/features/dashboard/dashboard_spec.rb
  spec/features/debates_spec.rb
  spec/features/notifications_spec.rb
  spec/features/officing/voters_spec.rb
  spec/features/polls/polls_spec.rb
  spec/features/tags/debates_spec.rb
  spec/features/tags/proposals_spec.rb
  spec/lib/graphql_spec.rb
  spec/models/budget/ballot_spec.rb
  spec/models/budget/heading_spec.rb
  spec/models/budget/investment_spec.rb
  spec/models/community_spec.rb
  spec/models/direct_message_spec.rb
  spec/models/document_spec.rb
  spec/models/notification_spec.rb
  spec/models/poll/voter_spec.rb
  spec/models/proposal_notification_spec.rb
  spec/models/widget/card_spec.rb
  spec/models/widget/feed_spec.rb
Labels: Rubocop

#3736 Remove instance variables in RSpec
  .rubocop.yml
  .rubocop_basic.yml
  spec/controllers/remote_translation_controller_spec.rb
  spec/controllers/users/confirmations_controller_spec.rb
  spec/controllers/users/registrations_controller_spec.rb
  spec/features/account_spec.rb
  spec/features/admin/activity_spec.rb
  spec/features/admin/banners_spec.rb
  spec/features/admin/budget_investments_spec.rb
  spec/features/admin/change_log_spec.rb
  spec/features/admin/managers_spec.rb
  spec/features/admin/moderators_spec.rb
  spec/features/admin/officials_spec.rb
  spec/features/admin/organizations_spec.rb
  spec/features/admin/poll/officers_spec.rb
  spec/features/admin/stats_spec.rb
  spec/features/admin/users_spec.rb
  spec/features/budgets/investments_spec.rb
  spec/features/campaigns_spec.rb
  spec/features/comments/budget_investments_spec.rb
  spec/features/comments/debates_spec.rb
  spec/features/comments/legislation_annotations_spec.rb
  spec/features/comments/legislation_questions_spec.rb
  spec/features/comments/polls_spec.rb
  spec/features/comments/proposals_spec.rb
  spec/features/comments/topics_spec.rb
  spec/features/legislation/draft_versions_spec.rb
  spec/features/legislation/proposals_spec.rb
  spec/features/legislation/questions_spec.rb
  spec/features/legislation/resume_spec.rb
  spec/features/moderation/budget_investments_spec.rb
  spec/features/moderation/comments_spec.rb
  spec/features/moderation/debates_spec.rb
  spec/features/moderation/proposal_notifications_spec.rb
  spec/features/moderation/proposals_spec.rb
  spec/features/official_positions_spec.rb
  spec/features/officing/results_spec.rb
  spec/features/tracking/budgets_spec.rb
  spec/features/users_spec.rb
  spec/features/valuation/budgets_spec.rb
  spec/features/votes_spec.rb
  spec/lib/tasks/sitemap_spec.rb
Labels: Rubocop
