Repository consuldemocracy/consuldemocracy, pull requests merged in 2019-05, with the labels that each got.

#3472 Always use map image from admin site customization images
  app/views/budgets/groups/show.html.erb
  app/views/legislation/proposals/_geozones.html.erb
  app/views/shared/_map.html.erb
  spec/features/admin/site_customization/images_spec.rb
Labels: Admin, Improvement

#3483 Fix obsolete `respond_with_bip` usage
  app/controllers/dashboard/polls_controller.rb
  spec/features/dashboard/polls_spec.rb
Labels: Backport

#3487 Remove unused (and flaky) card code and its spec
  app/models/widget/card.rb
  spec/models/widget/card_spec.rb
Labels: Backport

#3486 Fix typo in budget executions spec
  spec/features/budgets/executions_spec.rb
Labels: Backport

#3466 Add document uploads from admin section
  app/controllers/admin/site_customization/documents_controller.rb
  app/helpers/admin_helper.rb
  app/models/document.rb
  app/views/admin/_menu.html.erb
  app/views/admin/site_customization/documents/index.html.erb
  app/views/admin/site_customization/documents/new.html.erb
  config/locales/en/activerecord.yml
  config/locales/en/admin.yml
  config/locales/es/activerecord.yml
  config/locales/es/admin.yml
  config/routes/admin.rb
  db/migrate/20181128175808_add_admin_to_documents.rb
  db/schema.rb
  spec/factories/files.rb
  spec/features/admin/site_customization/documents_spec.rb
  spec/models/document_spec.rb
Labels: Admin, Improvement

#3492 Don't destroy budgets with an associated poll
  app/controllers/admin/budgets_controller.rb
  config/locales/en/admin.yml
  config/locales/es/admin.yml
  spec/features/admin/budgets_spec.rb
Labels: Backport

#3499 Add admin budget stats
  app/controllers/admin/api/stats_controller.rb
  app/controllers/admin/stats_controller.rb
  app/helpers/budgets_helper.rb
  app/helpers/stats_helper.rb
  app/models/budget.rb
  app/views/admin/stats/_graph.html.erb
  app/views/admin/stats/budget_balloting.html.erb
  app/views/admin/stats/budget_supporting.html.erb
  app/views/admin/stats/budgets.html.erb
  app/views/admin/stats/graph.html.erb
  app/views/admin/stats/show.html.erb
  app/views/layouts/admin.html.erb
  config/initializers/ahoy.rb
  config/initializers/vote_extensions.rb
  config/locales/en/admin.yml
  config/locales/es/admin.yml
  config/routes/admin.rb
  spec/controllers/admin/api/stats_controller_spec.rb
  spec/features/admin/stats_spec.rb
  spec/features/campaigns_spec.rb
Labels: Backport

#3438 Add budget stats
  app/assets/images/budgets/stats/gender.png
  app/controllers/budgets/results_controller.rb
  app/controllers/budgets/stats_controller.rb
  app/models/abilities/administrator.rb
  app/models/abilities/everyone.rb
  app/models/budget/ballot/line.rb
  app/models/budget/stats.rb
  app/views/budgets/executions/show.html.erb
  app/views/budgets/results/show.html.erb
  app/views/budgets/show.html.erb
  app/views/budgets/stats/show.html.erb
  config/locales/en/budgets.yml
  config/locales/es/budgets.yml
  config/routes/budget.rb
  db/migrate/20170628211547_add_ballot_line_counter_cached_to_budget_ballots.rb
  db/schema.rb
  spec/factories/users.rb
  spec/features/budgets/stats_spec.rb
  spec/models/budget/stats_spec.rb
Labels: Backport

#3397 Remove question and external_url fields from proposals and legislation proposals
  app/controllers/legislation/proposals_controller.rb
  app/controllers/management/proposals_controller.rb
  app/controllers/proposals_controller.rb
  app/models/legislation/proposal.rb
  app/models/proposal.rb
  app/views/admin/hidden_proposals/index.html.erb
  app/views/admin/poll/questions/_successful_proposals.html.erb
  app/views/documents/_additional_documents.html.erb
  app/views/legislation/proposals/show.html.erb
  app/views/proposals/_form.html.erb
  app/views/proposals/_info.html.erb
  config/api.yml
  config/locales/en/documents.yml
  config/locales/en/general.yml
  config/locales/es/documents.yml
  config/locales/es/general.yml
  db/dev_seeds/legislation_proposals.rb
  db/dev_seeds/proposals.rb
  db/migrate/20190307165132_remove_question_and_external_url_from_proposals.rb
  db/migrate/20190307165337_remove_question_and_external_url_from_legislation_proposals.rb
  db/schema.rb
  lib/tasks/proposal_actions.rake
  spec/factories/proposals.rb
  spec/features/admin/hidden_proposals_spec.rb
  spec/features/admin/poll/questions_spec.rb
  spec/features/management/proposals_spec.rb
  spec/features/proposals_spec.rb
  spec/features/tags/proposals_spec.rb
  spec/lib/tasks/proposals_spec.rb
  spec/models/proposal_spec.rb
  spec/shared/features/mappable.rb
  spec/shared/features/nested_documentable.rb
  spec/shared/features/nested_imageable.rb
  spec/support/common_actions.rb
  spec/support/common_actions/proposals.rb
Labels: Citizen proposals, Improvement, Legislation

#3506 Remove redirect for poll officers
  app/controllers/users/sessions_controller.rb
Labels: Improvement

#3476 Allow delete polls with associated questions and answers
  app/controllers/admin/poll/polls_controller.rb
  app/models/poll.rb
  app/models/poll/question.rb
  app/views/admin/poll/polls/_poll.html.erb
  config/locales/en/admin.yml
  config/locales/es/admin.yml
  spec/features/admin/poll/polls_spec.rb
Labels: Admin, Improvement, Polls

#3507 Proposals authors user segment
  app/views/admin/newsletters/show.html.erb
  config/locales/en/admin.yml
  config/locales/es/admin.yml
  lib/user_segments.rb
  spec/lib/user_segments_spec.rb
Labels: Admin, Improvement, Newsletters

#3508 Improve help texts on Admin UI
  app/assets/images/logo_email.png
  app/mailers/application_mailer.rb
  app/models/site_customization/image.rb
  app/views/admin/budget_investments/_select_investment.html.erb
  app/views/admin/newsletters/new.html.erb
  app/views/admin/poll/officers/_search.html.erb
  app/views/admin/poll/shifts/_shifts.html.erb
  app/views/admin/site_customization/pages/_form.html.erb
  app/views/layouts/_mailer_header.html.erb
  config/locales/en/admin.yml
  config/locales/en/community.yml
  config/locales/en/documents.yml
  config/locales/en/images.yml
  config/locales/es/admin.yml
  spec/features/admin/budget_groups_spec.rb
  spec/features/admin/budget_headings_spec.rb
  spec/features/admin/budget_investments_spec.rb
  spec/features/admin/budgets_spec.rb
  spec/features/admin/poll/shifts_spec.rb
  spec/features/admin/site_customization/images_spec.rb
  spec/features/admin/tags_spec.rb
  spec/features/topics_specs.rb
  spec/fixtures/files/logo_email_custom.png
  spec/shared/features/documentable.rb
Labels: Admin, Improvement, UX

#3509 Users menu
  app/helpers/users_helper.rb
  app/views/admin/shared/_admin_shortcuts.html.erb
  app/views/layouts/_admin_header.html.erb
  app/views/layouts/management.html.erb
  app/views/shared/_admin_login_items.html.erb
  config/locales/en/general.yml
  config/locales/es/general.yml
  spec/features/admin/budget_investments_spec.rb
  spec/features/management_spec.rb
  spec/features/officing_spec.rb
  spec/features/proposal_notifications_spec.rb
  spec/features/users_auth_spec.rb
  spec/support/common_actions/notifications.rb
Labels: Improvement, UX

#3504 Add slug to polls
  app/controllers/polls_controller.rb
  app/models/poll.rb
  app/views/polls/_poll_group.html.erb
  app/views/polls/_poll_subnav.html.erb
  db/dev_seeds/polls.rb
  db/migrate/20171008154106_add_slug_to_polls.rb
  db/schema.rb
  lib/tasks/polls.rake
  spec/factories/polls.rb
  spec/features/admin/poll/polls_spec.rb
  spec/features/polls/polls_spec.rb
Labels: Backport, Release notes

#3503 Improve poll stats
  app/controllers/officing/base_controller.rb
  app/controllers/polls/questions_controller.rb
  app/helpers/stats_helper.rb
  app/models/poll/question.rb
  app/models/poll/question/answer.rb
  app/models/poll/stats.rb
  app/models/poll/voter.rb
  app/views/polls/results.html.erb
  app/views/polls/show.html.erb
  spec/features/officing/results_spec.rb
Labels: Backport

#3510 Simplify stats caching
  app/models/budget/stats.rb
  app/models/concerns/statisticable.rb
  app/models/poll/stats.rb
Labels: Backport

#3511 Refactor gender and age stats methods
  app/helpers/stats_helper.rb
  app/models/budget/stats.rb
  app/models/concerns/statisticable.rb
  app/models/poll/stats.rb
  app/views/polls/stats.html.erb
Labels: Backport

#3488 Admin basic customization texts
  app/controllers/admin/site_customization/information_texts_controller.rb
  app/helpers/site_customization_helper.rb
  app/models/i18n_content.rb
  app/views/admin/site_customization/information_texts/_tabs.html.erb
  config/locales/en/admin.yml
  config/locales/es/admin.yml
  spec/features/admin/site_customization/information_texts_spec.rb
  spec/features/site_customization/information_texts_spec.rb
  spec/models/i18n_content_spec.rb
Labels: Admin, Improvement

#3515 Proposals support on mobile
  app/assets/javascripts/foundation_extras.js.coffee
  app/assets/stylesheets/layout.scss
  app/assets/stylesheets/participation.scss
  app/views/proposals/show.html.erb
  spec/features/proposals_spec.rb
Labels: Citizen proposals, Improvement

#3519 Simplify link to poll
  app/helpers/polls_helper.rb
  app/views/polls/_poll_group.html.erb
  spec/features/polls/polls_spec.rb
Labels: Backport

#3520 Add options to show advanced stats
  app/controllers/admin/budgets_controller.rb
  app/controllers/admin/poll/polls_controller.rb
  app/controllers/concerns/report_attributes.rb
  app/controllers/dashboard/polls_controller.rb
  app/models/abilities/everyone.rb
  app/models/budget.rb
  app/models/concerns/reportable.rb
  app/models/concerns/statisticable.rb
  app/models/poll.rb
  app/models/report.rb
  app/views/admin/budgets/_form.html.erb
  app/views/admin/poll/results/_show_results.html.erb
  app/views/admin/shared/_show_results_fields.html.erb
  app/views/budgets/stats/_advanced_stats.html.erb
  app/views/budgets/stats/_advanced_stats_links.html.erb
  app/views/budgets/stats/show.html.erb
  app/views/polls/_advanced_stats.html.erb
  app/views/polls/_advanced_stats_links.html.erb
  app/views/polls/stats.html.erb
  config/i18n-tasks.yml
  config/locales/en/activerecord.yml
  config/locales/en/admin.yml
  config/locales/es/activerecord.yml
  config/locales/es/admin.yml
  db/migrate/20190424114803_create_reports.rb
  db/migrate/20190429125842_add_advanced_stats_to_reports.rb
  db/schema.rb
  lib/migrations/reports.rb
  lib/tasks/stats_and_results.rake
  spec/factories/budgets.rb
  spec/features/admin/budgets_spec.rb
  spec/features/budgets/executions_spec.rb
  spec/features/budgets/investments_spec.rb
  spec/features/budgets/results_spec.rb
  spec/features/budgets/stats_spec.rb
  spec/features/polls/polls_spec.rb
  spec/lib/migrations/reports_spec.rb
  spec/models/abilities/everyone_spec.rb
  spec/models/budget_spec.rb
  spec/models/concerns/reportable.rb
  spec/models/poll/poll_spec.rb
Labels: Backport, Release notes

#3534 Resize Capybara window back to its original size
  spec/features/proposals_spec.rb
Labels: Backport

#3361 Display all polls for current booth
  app/controllers/officing/voters_controller.rb
  app/models/poll.rb
  app/views/officing/voters/_already_voted.html.erb
  app/views/officing/voters/_cannot_vote.html.erb
  app/views/officing/voters/new.html.erb
  config/locales/en/officing.yml
  config/locales/es/officing.yml
  spec/features/officing/voters_spec.rb
Labels: Backport, Improvement, Polls

#3561 Change devise configuration
  config/initializers/devise.rb
  spec/features/users_auth_spec.rb
Labels: Improvement

#3539 Remove token on views
  app/views/polls/show.html.erb
  config/locales/en/general.yml
  config/locales/es/general.yml
  spec/features/polls/voter_spec.rb
Labels: Polls

#3563 Add task to regenerate ballot_lines_count cache
  lib/tasks/regenerate_ballot_lines_cache.rake
Labels: Release notes

#3570 Fix valid votes labels
  app/controllers/admin/poll/recounts_controller.rb
  app/helpers/poll_recounts_helper.rb
  app/models/poll/stats.rb
  app/views/admin/poll/recounts/index.html.erb
  config/locales/en/admin.yml
  config/locales/en/officing.yml
  config/locales/es/admin.yml
  config/locales/es/officing.yml
  spec/features/admin/poll/polls_spec.rb
  spec/helpers/poll_recounts_helper_spec.rb
Labels: Backport

#3565 Fix order in annotation comments with same score
  app/controllers/legislation/annotations_controller.rb
  lib/comment_tree.rb
  lib/merged_comment_tree.rb
  spec/features/comments/legislation_annotations_spec.rb
Labels: Backport

#3571 Add Bosnian, Croatian, Czech, Danish, Greek, and Turkish locales
  config/application.rb
  config/locales/bs-BA/i18n.yml
  config/locales/da-DK/i18n.yml
  config/locales/hr-HR/i18n.yml
  config/locales/it/i18n.yml
  config/locales/pl-PL/i18n.yml
  config/locales/sq-AL/i18n.yml
Labels: Translations
