Repository consuldemocracy/consuldemocracy, pull requests merged in 2019-06, with the labels that each got.

#3572 Hide polls created by users from proposals dashboard on admin poll index
  app/controllers/admin/poll/polls_controller.rb
  app/models/poll.rb
  spec/features/admin/poll/polls_spec.rb
Labels: Admin, Citizen proposals, Polls

#3573 Add help texs, links and new message section to improve UX
  app/assets/stylesheets/legislation.scss
  app/assets/stylesheets/legislation_process.scss
  app/controllers/dashboard_controller.rb
  app/helpers/proposals_dashboard_helper.rb
  app/views/comments/_comment.html.erb
  app/views/communities/show.html.erb
  app/views/dashboard/_menu.html.erb
  app/views/dashboard/messages.html.erb
  app/views/legislation/proposals/show.html.erb
  config/locales/en/general.yml
  config/locales/en/legislation.yml
  config/locales/en/settings.yml
  config/locales/es/general.yml
  config/locales/es/legislation.yml
  config/locales/es/settings.yml
  config/routes/proposal.rb
  spec/features/comments/budget_investments_spec.rb
  spec/features/comments/budget_investments_valuation_spec.rb
  spec/features/comments/debates_spec.rb
  spec/features/comments/legislation_annotations_spec.rb
  spec/features/comments/legislation_questions_spec.rb
  spec/features/comments/polls_spec.rb
  spec/features/comments/proposals_spec.rb
  spec/features/comments/topics_spec.rb
  spec/features/dashboard/dashboard_spec.rb
  spec/features/legislation/proposals_spec.rb
  spec/features/proposal_notifications_spec.rb
  spec/support/common_actions/notifications.rb
Labels: Improvement, UX

#3574 Allow users to delete dashboard polls
  app/controllers/dashboard/polls_controller.rb
  app/views/dashboard/polls/_form.html.erb
  app/views/dashboard/polls/_poll.html.erb
  config/locales/en/general.yml
  config/locales/es/general.yml
  config/routes/proposal.rb
  spec/features/admin/poll/polls_spec.rb
  spec/features/dashboard/polls_spec.rb
Labels: Citizen proposals, Improvement, Polls

#3576 Add new settings automatically on every deployment
  app/models/setting.rb
  config/deploy.rb
  lib/tasks/settings.rake
  spec/models/setting_spec.rb
Labels: Backport

#3577 Extract partial with mobile sticky content
  app/views/proposals/_support_status.html.erb
  app/views/proposals/show.html.erb
Labels: Citizen proposals, Improvement

#3587 Show name and email for deleted poll officer's user account
  app/models/poll/officer.rb
  config/locales/en/general.yml
  config/locales/es/general.yml
  spec/models/poll/officer_spec.rb
Labels: Bug

#3580 Use find instead of find by
  app/controllers/admin/budget_groups_controller.rb
  app/controllers/admin/budget_headings_controller.rb
  app/controllers/admin/budget_investments_controller.rb
  app/controllers/admin/budgets_controller.rb
  app/controllers/budgets/ballot/lines_controller.rb
  app/controllers/budgets/ballots_controller.rb
  app/controllers/budgets/groups_controller.rb
  app/controllers/budgets/investments_controller.rb
  app/controllers/budgets/results_controller.rb
  app/controllers/budgets/stats_controller.rb
  app/controllers/budgets_controller.rb
  app/controllers/management/budgets/investments_controller.rb
  app/controllers/valuation/budget_investments_controller.rb
  app/models/budget/investment.rb
  app/models/concerns/sluggable.rb
  spec/controllers/budgets/ballots/lines_controller_spec.rb
  spec/features/admin/budget_groups_spec.rb
  spec/features/admin/budget_headings_spec.rb
  spec/features/admin/budget_investments_spec.rb
  spec/features/admin/budgets_spec.rb
  spec/features/budgets/ballots_spec.rb
  spec/features/budgets/budgets_spec.rb
  spec/features/budgets/executions_spec.rb
  spec/features/budgets/groups_spec.rb
  spec/features/budgets/investments_spec.rb
  spec/features/budgets/results_spec.rb
  spec/features/budgets/stats_spec.rb
  spec/features/management/budget_investments_spec.rb
  spec/features/valuation/budget_investments_spec.rb
  spec/models/budget/investment_spec.rb
Labels: Backport

#3585 Images and documents settings
  app/assets/stylesheets/admin.scss
  app/controllers/admin/settings_controller.rb
  app/helpers/documentables_helper.rb
  app/helpers/imageables_helper.rb
  app/models/budget/investment.rb
  app/models/concerns/documentable.rb
  app/models/dashboard/action.rb
  app/models/image.rb
  app/models/legislation/process.rb
  app/models/legislation/proposal.rb
  app/models/milestone.rb
  app/models/poll/question/answer.rb
  app/models/proposal.rb
  app/models/setting.rb
  app/views/admin/settings/_content_types_settings_form.html.erb
  app/views/admin/settings/_featured_settings_form.html.erb
  app/views/admin/settings/_featured_settings_table.html.erb
  app/views/admin/settings/_filter_subnav.html.erb
  app/views/admin/settings/_images_and_documents_tab.html.erb
  app/views/admin/settings/_settings_form.html.erb
  app/views/admin/settings/_settings_table.html.erb
  app/views/admin/settings/index.html.erb
  config/i18n-tasks.yml
  config/locales/en/admin.yml
  config/locales/en/settings.yml
  config/locales/es/admin.yml
  config/locales/es/settings.yml
  config/routes/admin.rb
  spec/features/admin/settings_spec.rb
  spec/models/setting_spec.rb
  spec/shared/models/image_validations.rb
Labels: Admin, Backport, Improvement

#3592 Don't show links to disabled budget results
  app/helpers/budgets_helper.rb
  app/views/budgets/_finished.html.erb
  app/views/budgets/_subnav.html.erb
  app/views/budgets/executions/show.html.erb
  app/views/budgets/index.html.erb
  app/views/budgets/results/show.html.erb
  app/views/budgets/show.html.erb
  app/views/budgets/stats/show.html.erb
  spec/features/budgets/results_spec.rb
Labels: Backport

#3590 Add task to upgrade to a new release
  config/deploy.rb
  lib/application_logger.rb
  lib/tasks/budgets.rake
  lib/tasks/consul.rake
  lib/tasks/polls.rake
  lib/tasks/regenerate_ballot_lines_cache.rake
  lib/tasks/settings.rake
  lib/tasks/stats.rake
  lib/tasks/stats_and_results.rake
Labels: Backport

#3581 Avoid duplicate records using translations
  app/controllers/polls_controller.rb
  app/controllers/valuation/budget_investments_controller.rb
  app/models/budget/group.rb
  app/models/budget/heading.rb
  app/models/poll.rb
  app/models/poll/booth.rb
  app/models/user.rb
  app/views/budgets/investments/_votes.html.erb
  spec/models/budget/group_spec.rb
  spec/models/budget/heading_spec.rb
  spec/models/poll/booth_spec.rb
  spec/models/poll/poll_spec.rb
  spec/models/user_spec.rb
Labels: Backport

#3603 Avoid error when accessing final voting stats before the balloting phase
  app/controllers/admin/stats_controller.rb
  app/models/abilities/administrator.rb
  app/views/admin/stats/budgets.html.erb
  config/locales/en/admin.yml
  config/locales/es/admin.yml
  spec/features/admin/stats_spec.rb
Labels: Admin, Budget, Bug
