Repository consuldemocracy/consuldemocracy, pull requests merged in 2019-11, with the labels that each got.

#3617 Avoid error for polls results
  app/models/poll/question.rb
  spec/features/polls/results_spec.rb
Labels: Bug, Polls

#3809 Simplify JavaScript to pluralize translations
  app/assets/javascripts/application.js
  app/assets/javascripts/budget_edit_associations.js
  app/assets/javascripts/globalize.js
  app/assets/javascripts/i18n.js
  app/controllers/admin/budgets_controller.rb
  app/models/abilities/administrator.rb
  app/views/admin/budgets/_form.html.erb
  app/views/shared/_common_globalize_locales.html.erb
  config/i18n-tasks.yml
  config/locales/en/general.yml
  config/locales/es/general.yml
  config/routes/admin.rb
Labels: Refactoring

#3807 Fix assigning staff members to budgets
  app/assets/javascripts/budget_edit_associations.js
  app/controllers/admin/budget_investments_controller.rb
  app/controllers/admin/budgets_controller.rb
  app/helpers/budget_executions_helper.rb
  app/helpers/budgets_helper.rb
  app/helpers/translatable_form_helper.rb
  app/models/budget.rb
  app/models/budget/investment.rb
  app/models/budget_rol_assignment.rb
  app/models/tagging.rb
  app/models/user.rb
  app/views/admin/budget_investments/_search_form.html.erb
  app/views/admin/budget_investments/show.html.erb
  app/views/admin/budgets/_association.html.erb
  app/views/admin/budgets/_form.html.erb
  config/locales/en/activerecord.yml
  config/locales/en/admin.yml
  config/locales/es/activerecord.yml
  config/locales/es/admin.yml
  db/migrate/20191031172132_drop_budget_rol_assignments.rb
  db/migrate/20191031173943_use_acts_as_taggable_in_budgets.rb
  db/migrate/20191031210734_remove_help_link_from_budgets.rb
  db/schema.rb
  lib/tasks/consul.rake
  lib/tasks/migrations.rake
  spec/factories/classifications.rb
  spec/features/admin/budget_investments_spec.rb
  spec/features/admin/budgets_spec.rb
  spec/features/tags/budget_investments_spec.rb
  spec/lib/tasks/migrations_spec.rb
  spec/models/budget_spec.rb
Labels: Bug

#3812 Stop using Knapsack Pro
  .travis.yml
  Gemfile
  Gemfile.lock
  Rakefile
  bin/knapsack_pro_rspec
  knapsack_rspec_report.json
  spec/spec_helper.rb
Labels: Specs

#3811 Use audited to track changes in investments
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/admin.scss
  app/controllers/admin/budget_investment_audits_controller.rb
  app/controllers/admin/budget_investments_controller.rb
  app/controllers/application_controller.rb
  app/helpers/audits_helper.rb
  app/helpers/change_log_helper.rb
  app/models/audit.rb
  app/models/budget/investment.rb
  app/models/budget/investment/change_log.rb
  app/models/user.rb
  app/views/admin/audits/_audits.html.erb
  app/views/admin/audits/show.html.erb
  app/views/admin/budget_investments/_written_by_author.html.erb
  app/views/admin/budget_investments/show.html.erb
  app/views/admin/change_logs/_change_log.html.erb
  app/views/admin/change_logs/show.html.erb
  config/initializers/audited.rb
  config/initializers/routes_hierarchy.rb
  config/locales/en/activerecord.yml
  config/locales/en/admin.yml
  config/locales/es/activerecord.yml
  config/locales/es/admin.yml
  config/routes/admin.rb
  db/dev_seeds/budgets.rb
  db/migrate/20191102002206_install_audited.rb
  db/migrate/20191102002238_drop_budget_investment_change_logs.rb
  db/schema.rb
  spec/features/admin/audits_spec.rb
  spec/features/admin/change_log_spec.rb
Labels: Bug

#3816 Fix typos in columns selector
  app/assets/javascripts/columns_selector.js
  app/assets/javascripts/cookies.js
  app/assets/stylesheets/admin.scss
  app/views/admin/budget_investments/_investments.html.erb
  spec/features/admin/budget_investments_spec.rb
Labels: Maintenance

#3817 Fix valuation permissions for finished budgets
  app/helpers/valuators_helper.rb
  app/models/abilities/administrator.rb
  app/models/abilities/valuator.rb
  app/views/admin/valuators/show.html.erb
  app/views/valuation/budget_investments/_valuation_comments.html.erb
  app/views/valuation/budget_investments/edit.html.erb
  spec/models/abilities/valuator_spec.rb
Labels: Bug

#3822 Fix admin permissions for finished budgets
  app/controllers/admin/budget_investments_controller.rb
  app/models/abilities/administrator.rb
  app/views/admin/budget_investments/_select_investment.html.erb
  app/views/admin/budget_investments/show.html.erb
  app/views/valuation/budget_investments/show.html.erb
  spec/features/admin/budget_investments_spec.rb
  spec/features/valuation/budget_investments_spec.rb
  spec/models/abilities/administrator_spec.rb
Labels: Bug

#3821 Revert "Stop using Knapsack Pro"
  .travis.yml
  Gemfile
  Gemfile.lock
  Rakefile
  bin/knapsack_pro_rspec
  spec/spec_helper.rb
Labels: Specs

#3824 Avoid jumping CKEditor
  app/assets/stylesheets/layout.scss
Labels: Bug

#3825 Enable Lint/SafeNavigationChain rubocop rule
  .rubocop.yml
Labels: Rubocop

#3804 Bump ckeditor from 4.2.4 to 4.3.0
  Gemfile
  Gemfile.lock
  config/initializers/ckeditor.rb
Labels: dependencies, security

#3826 Update deprecated jQuery syntax
  app/assets/javascripts/ckeditor/reinit.js
  app/assets/javascripts/forms.js
  app/assets/javascripts/table_sortable.js
  app/assets/javascripts/valuation_budget_investment_form.js
  spec/shared/features/nested_documentable.rb
Labels: Maintenance

#3827 Remove obsolete report columns from polls
  db/migrate/20191107193003_remove_old_stats_and_results_enabled_columns.rb
  db/schema.rb
Labels: Maintenance

#3773 Local census records fixes
  app/models/local_census_record.rb
  app/views/admin/local_census_records/_form.html.erb
  app/views/admin/local_census_records/_local_census_record.html.erb
  config/locales/en/activerecord.yml
  config/locales/es/activerecord.yml
  spec/features/admin/local_census_records/imports_spec.rb
  spec/features/admin/local_census_records_spec.rb
  spec/fixtures/files/local_census_records/import/invalid.csv
  spec/fixtures/files/local_census_records/import/valid.csv
  spec/models/local_census_record_spec.rb
  spec/models/local_census_records/import_spec.rb
Labels: Verification

#3829 Remove duplicated local census records on deployment
  config/deploy.rb
  lib/tasks/local_census_records.rake
  spec/lib/tasks/local_census_records_spec.rb
Labels: Release notes, Verification

#3828 Bring back removal of translatable columns
  db/migrate/20190213150434_rename_old_translatable_attibutes_in_debates.rb
  db/migrate/20190215152236_rename_old_translatable_attibutes_in_proposals.rb
  db/migrate/20190218122530_rename_old_translatable_attibutes_in_comments.rb
  db/migrate/20190218162141_rename_old_translatable_attibutes_in_budget_investments.rb
  db/migrate/20190221154819_remove_deprecated_translatable_fields_from_banners.rb
  db/migrate/20190221162450_remove_deprecated_translatable_fields_from_polls.rb
  db/migrate/20190221162858_remove_deprecated_translatable_fields_from_poll_questions.rb
  db/migrate/20190221163117_remove_deprecated_translatable_fields_from_poll_question_answers.rb
  db/migrate/20190221163818_remove_deprecated_translatable_fields_from_admin_notifications.rb
  db/migrate/20190221164056_remove_deprecated_translatable_fields_from_milestones.rb
  db/migrate/20190221164559_remove_deprecated_translatable_fields_from_legislation_draft_versions.rb
  db/migrate/20190221164928_remove_deprecated_translatable_fields_from_legislation_processes.rb
  db/migrate/20190221165347_remove_deprecated_translatable_fields_from_legislation_questions.rb
  db/migrate/20190221171155_remove_deprecated_translatable_fields_from_legislation_question_options.rb
  db/migrate/20190221171859_remove_deprecated_translatable_fields_from_site_customization_pages.rb
  db/migrate/20190221172209_remove_deprecated_translatable_fields_from_widget_cards.rb
  db/migrate/20190325184500_remove_deprecated_translatable_fields_from_budgets.rb
  db/migrate/20190325185046_remove_deprecated_translatable_fields_from_budget_groups.rb
  db/migrate/20190325185405_remove_deprecated_translatable_fields_from_budget_headings.rb
  db/migrate/20190325185550_remove_deprecated_translatable_fields_from_budget_phases.rb
  db/schema.rb
Labels: Maintenance

#3831 Fix random title with trailing spaces
  spec/factories/proposals.rb
Labels: Specs

#3832 Don't add log info messages when running tests
  lib/application_logger.rb
Labels: Specs

#3833 Remove old milestone tables
  db/migrate/20191108173350_remove_old_milestone_tables.rb
  db/schema.rb
Labels: Maintenance

#3834 Apply rubocop Rails/FindBy rule everywhere
  .rubocop.yml
  app/controllers/admin/homepage_controller.rb
  app/controllers/application_controller.rb
  app/controllers/dashboard/actions_controller.rb
  app/controllers/legislation/annotations_controller.rb
  app/controllers/officing/base_controller.rb
  app/controllers/officing/results_controller.rb
  app/controllers/officing/voters_controller.rb
  app/controllers/polls_controller.rb
  app/controllers/verification/email_controller.rb
  app/controllers/verification/sms_controller.rb
  app/helpers/budgets_helper.rb
  app/helpers/polls_helper.rb
  app/helpers/site_customization_helper.rb
  config/initializers/i18n_translation.rb
  spec/features/admin/homepage/homepage_spec.rb
  spec/features/admin/settings_spec.rb
  spec/features/admin/stats_spec.rb
  spec/features/budget_polls/budgets_spec.rb
  spec/features/budget_polls/voter_spec.rb
  spec/features/legislation/processes_spec.rb
  spec/features/organizations_spec.rb
  spec/features/polls/voter_spec.rb
  spec/features/proposal_notifications_spec.rb
  spec/mailers/previews/dashboard_mailer_preview.rb
  spec/models/debate_spec.rb
  spec/models/newsletter_spec.rb
  spec/models/proposal_spec.rb
Labels: Rubocop

#3839 Improve restrictions for poll stats
  app/controllers/polls_controller.rb
  app/helpers/polls_helper.rb
  app/models/abilities/administrator.rb
  app/models/abilities/everyone.rb
  app/models/budget.rb
  app/models/budget/phase.rb
  app/models/concerns/reportable.rb
  app/models/poll.rb
  app/views/polls/_poll_subnav.html.erb
  lib/tasks/stats.rake
  spec/features/polls/polls_spec.rb
  spec/models/abilities/administrator_spec.rb
  spec/models/abilities/everyone_spec.rb
  spec/models/budget_spec.rb
  spec/models/concerns/reportable.rb
Labels: Bug

#3843 Remove unused code
  app/controllers/admin/settings_controller.rb
  app/controllers/admin/widget/base_controller.rb
  app/controllers/concerns/admin/manages_proposal_settings.rb
  app/controllers/concerns/dashboard/group_supports.rb
  app/helpers/application_helper.rb
  app/helpers/documents_helper.rb
  app/helpers/imageables_helper.rb
  app/helpers/images_helper.rb
  app/helpers/officers_helper.rb
  app/helpers/polls_helper.rb
  app/models/administrator_task.rb
  app/models/poll/voter.rb
Labels: Maintenance

#3844 Split comments and debates admin tests
  spec/features/admin/comments_spec.rb
  spec/features/admin/debates_spec.rb
  spec/features/admin/hidden_comments_spec.rb
  spec/features/admin/hidden_debates_spec.rb
Labels: Specs

#3845 Reduce number of records in pagination tests
  app/controllers/concerns/moderate_actions.rb
  spec/features/admin/budget_investments_spec.rb
  spec/features/admin/hidden_budget_investments_spec.rb
  spec/features/admin/hidden_comments_spec.rb
  spec/features/admin/hidden_debates_spec.rb
  spec/features/admin/hidden_proposals_spec.rb
  spec/features/admin/hidden_users_spec.rb
  spec/features/admin/local_census_records_spec.rb
  spec/features/admin/organizations_spec.rb
  spec/features/admin/proposal_notifications_spec.rb
  spec/features/admin/site_customization/documents_spec.rb
  spec/features/debates_spec.rb
  spec/features/moderation/budget_investments_spec.rb
  spec/features/moderation/comments_spec.rb
  spec/features/moderation/debates_spec.rb
  spec/features/moderation/proposal_notifications_spec.rb
  spec/features/moderation/proposals_spec.rb
  spec/features/proposals_spec.rb
  spec/features/valuation/budget_investments_spec.rb
Labels: Specs

#3695 Define SMTP settings in secrets file
  config/deploy.rb
  config/environments/preproduction.rb
  config/environments/production.rb
  config/environments/staging.rb
  config/initializers/delayed_job_config.rb
  config/secrets.yml.example
  lib/tasks/secrets.rake
Labels: Installer, Release notes

#3849 Make puma restarts work with systemd
  config/deploy.rb
  config/puma.rb
Labels: Bug

#3846 Avoid redirects with unprotected query params
  app/controllers/admin/hidden_budget_investments_controller.rb
  app/controllers/admin/hidden_comments_controller.rb
  app/controllers/admin/hidden_debates_controller.rb
  app/controllers/admin/hidden_proposals_controller.rb
  app/controllers/admin/hidden_users_controller.rb
  app/controllers/admin/organizations_controller.rb
  app/controllers/admin/proposal_notifications_controller.rb
  app/controllers/application_controller.rb
  app/controllers/concerns/moderate_actions.rb
  app/controllers/debates_controller.rb
  app/controllers/images_controller.rb
  app/controllers/moderation/users_controller.rb
  app/helpers/application_helper.rb
  app/views/budgets/investments/_investment_show.html.erb
  spec/controllers/admin/hidden_debates_controller_spec.rb
  spec/controllers/admin/organizations_controller_spec.rb
  spec/controllers/debates_controller_spec.rb
  spec/controllers/images_controller_spec.rb
  spec/controllers/moderation/budgets/investments_controller_spec.rb
  spec/controllers/moderation/users_controller_spec.rb
  spec/features/localization_spec.rb
Labels: security

#3532 Allow create legislation proposals on process draft phase
  app/views/legislation/processes/_proposals_content.html.erb
  spec/features/legislation/processes_spec.rb
Labels: Legislation

#3851 Reduce false positives count in security reports
  app/assets/javascripts/banners.js
  app/controllers/communities_controller.rb
  app/controllers/management/base_controller.rb
  app/controllers/management/sessions_controller.rb
  app/helpers/banners_helper.rb
  app/models/budget/investment.rb
  app/models/concerns/globalizable.rb
  app/models/concerns/search_cache.rb
  app/models/newsletter.rb
  app/views/admin/banners/_form.html.erb
  app/views/admin/banners/index.html.erb
  app/views/shared/_banner.html.erb
  spec/features/admin/banners_spec.rb
  spec/features/xss_spec.rb
Labels: security

#3850 Add puma configuration to version control
  Gemfile
  Gemfile.lock
  config/deploy.rb
  config/deploy/preproduction.rb
  config/deploy/production.rb
  config/deploy/staging.rb
  config/puma.rb
  config/puma/development.rb
  config/puma/preproduction.rb
  config/puma/production.rb
  config/puma/staging.rb
Labels: Maintenance

#3853 Fix secrets task on first deployments
  config/deploy.rb
Labels: Bug

#3808 Update chromeOptions for newer versions of chromedriver
  spec/rails_helper.rb
Labels: Specs

#3857 Update Ruby after `deploy:updating`
  config/deploy.rb
Labels: Bug

#3425 Upgrade Ruby version in Dockerfile
  Dockerfile
Labels: Maintenance

#3860 Remove browser gem direct dependency
  Gemfile
  Gemfile.lock
  app/views/layouts/application.html.erb
Labels: Maintenance

#3861 Fix "go back" link in newsletters
  app/views/admin/newsletters/edit.html.erb
  app/views/admin/newsletters/new.html.erb
  app/views/admin/newsletters/show.html.erb
  spec/features/admin/emails/newsletters_spec.rb
Labels: Admin

#3859 Restart the application on every reboot
  Capfile
  config/deploy.rb
  config/puma/defaults.rb
  config/puma/preproduction.rb
  config/puma/production.rb
  config/puma/staging.rb
  config/schedule.rb
Labels: Maintenance

#3864 Avoid invalid random titles in dashboard specs
  spec/features/admin/dashboard/actions_spec.rb
  spec/models/dashboard/action_spec.rb
Labels: Specs

#3866 Make it easier to release a new version of CONSUL
  Gemfile
  Gemfile.lock
  Rakefile
Labels: Maintenance

#3868 Categories are still shown when properties of the legislation process are changed
  app/controllers/admin/legislation/processes_controller.rb
  spec/features/admin/legislation/processes_spec.rb
Labels: Bug
