Repository consuldemocracy/consuldemocracy, pull requests merged in 2019-12, with the labels that each got.

#3873 Bump knapsack_pro from 1.1.0 to 1.15.0
  Gemfile
  Gemfile.lock
Labels: dependencies

#3880 Remove translations accidentally added from en-US
  config/locales/en-US/activerecord.yml
  config/locales/en-US/admin.yml
  config/locales/en-US/budgets.yml
  config/locales/en-US/community.yml
  config/locales/en-US/general.yml
  config/locales/en-US/legislation.yml
  config/locales/en-US/moderation.yml
  config/locales/en-US/pages.yml
Labels: Bug, Translations

#3874 Sanitize values before sending them to remote translation client
  lib/remote_translations/caller.rb
  spec/lib/remote_translations/caller_spec.rb
Labels: Bug

#3871 Use symbols instead of strings for SMTP settings
  config/secrets.yml.example
  lib/tasks/secrets.rake
Labels: Bug

#3887 Remove comments from `en/rails.yml` files
  config/locales/en/rails.yml
Labels: Translations

#3778 Fix blank space in admin content
  app/assets/stylesheets/admin.scss
  app/assets/stylesheets/dashboard.scss
  app/assets/stylesheets/mixins.scss
  app/views/admin/_menu.html.erb
  app/views/layouts/admin.html.erb
  app/views/layouts/dashboard.html.erb
  app/views/officing/_menu.html.erb
Labels: Bug, UX
