Repository consuldemocracy/consuldemocracy, pull requests merged in 2020-10, with the labels that each got.

#4192 Use Harmony mode in uglifier for ES2015+ support
  config/environments/preproduction.rb
  config/environments/production.rb
  config/environments/staging.rb
Labels: Bug

#4143 Update Travis badge to use travis-ci.com
  .travis.yml
  README.md
  README_ES.md
Labels: Maintenance

#4141 Use Rails 5 default settings
  config/application.rb
  config/environments/development.rb
  config/environments/preproduction.rb
  config/environments/production.rb
  config/environments/staging.rb
Labels: Maintenance

#4142 Upgrade to Rails 5.2
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/controllers/admin/geozones_controller.rb
  app/controllers/application_controller.rb
  app/controllers/legislation/annotations_controller.rb
  app/controllers/management/base_controller.rb
  app/controllers/management/sessions_controller.rb
  app/models/application_record.rb
  app/models/comment.rb
  app/models/poll/question.rb
  bin/bundle
  bin/setup
  bin/update
  config/application.rb
  config/environments/development.rb
  config/environments/test.rb
  config/initializers/application_controller_renderer.rb
  config/initializers/content_security_policy.rb
  config/initializers/escape_javascript_fix.rb
  db/schema.rb
  spec/controllers/legislation/processes_controller_spec.rb
  spec/rails_helper.rb
  spec/spec_helper.rb
Labels: Maintenance, Release notes

#4208 Avoid seasonal clock changes issues in specs
  spec/system/proposal_notifications_spec.rb
Labels: Specs

#4193 Bump devise-security from 0.10.1 to 0.11.1
  Gemfile
  Gemfile.lock
  config/initializers/devise-security.rb
Labels: dependencies

#4210 Fix rubocop offenses in XLSX files
  app/views/legislation/processes/summary.xlsx.axlsx
  config/deploy.rb
Labels: Rubocop

#4212 Fix redirect when toggling visible to valuators
  app/controllers/admin/budget_investments_controller.rb
  app/views/admin/budget_investments/_select_investment.html.erb
  spec/controllers/admin/budget_investments_controller_spec.rb
  spec/spec_helper.rb
  spec/system/admin/budget_investments_spec.rb
  spec/views/admin/budget_investments/select_investment_spec.rb
Labels: Bug

#4200 Use labels for web_section_ids checkboxes texts
  app/views/admin/banners/_form.html.erb
  spec/system/admin/banners_spec.rb
Labels: Bug, UX

#4217 Run delayed job tasks in the staging environment
  config/deploy/staging.rb
Labels: Bug
