Repository consuldemocracy/consuldemocracy, pull requests merged in 2020-09, with the labels that each got.

#4051 Upgrade to jQuery 3.5.1
  Gemfile
  Gemfile.lock
  app/assets/javascripts/application.js
  app/assets/javascripts/dashboard_graphs.js
  app/assets/javascripts/globalize.js
  app/assets/javascripts/legislation_admin.js
  app/assets/javascripts/legislation_annotatable.js
  app/views/admin/poll/questions/answers/images/destroy.js.erb
  app/views/legislation/annotations/_comments_box_form.js.erb
  spec/system/admin/translatable_spec.rb
Labels: 1.2, Maintenance

#4117 Apply Legislation Process default colors to dev seeds
  app/helpers/legislation_helper.rb
  app/models/legislation/process.rb
  app/views/admin/legislation/processes/_form.html.erb
  spec/models/legislation/process_spec.rb
Labels: 1.2, Refactoring

#4115 Update columns type of attachment file
  db/migrate/20170322145702_create_site_customization_images.rb
  db/migrate/20170627113331_create_images.rb
  db/migrate/20170720092638_create_documents.rb
  db/migrate/20200908084257_change_attachment_size_fields_to_bigint.rb
  db/schema.rb
Labels: 1.2, Maintenance

#4116 Remove deprecated columns
  db/migrate/20200831112342_remove_deprecated_fields_from_budget_investments.rb
  db/migrate/20200831112559_remove_deprecated_field_from_comments.rb
  db/migrate/20200831112936_remove_deprecated_fields_from_debates.rb
  db/migrate/20200831113416_remove_deprecated_fields_from_proposals.rb
  db/schema.rb
Labels: 1.2

#4065 Add collaborative legislation summary
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/layout.scss
  app/assets/stylesheets/legislation_process.scss
  app/assets/stylesheets/mixins.scss
  app/assets/stylesheets/participation.scss
  app/controllers/legislation/processes_controller.rb
  app/models/abilities/administrator.rb
  app/models/abilities/everyone.rb
  app/models/comment.rb
  app/models/legislation/draft_version.rb
  app/models/legislation/question.rb
  app/views/comments/_responses_count.html.erb
  app/views/legislation/processes/_key_dates.html.erb
  app/views/legislation/processes/_summary_allegations.html.erb
  app/views/legislation/processes/_summary_comments.html.erb
  app/views/legislation/processes/_summary_debate.html.erb
  app/views/legislation/processes/_summary_proposals.html.erb
  app/views/legislation/processes/summary.html.erb
  app/views/legislation/processes/summary.xlsx.axlsx
  config/locales/en/legislation.yml
  config/locales/es/legislation.yml
  config/routes/legislation.rb
  spec/controllers/legislation/processes_controller_spec.rb
  spec/models/abilities/administrator_spec.rb
  spec/models/abilities/everyone_spec.rb
  spec/system/legislation/summary_spec.rb
Labels: 1.2, Legislation

#4125 Filter investments only by assigned staff
  app/helpers/admin_budget_investments_helper.rb
  app/helpers/admin_helper.rb
  app/helpers/budgets_helper.rb
  app/helpers/valuation_helper.rb
  app/views/admin/budget_investments/_search_form.html.erb
  spec/helpers/admin_budget_investments_helper_spec.rb
  spec/system/admin/budget_investments_spec.rb
Labels: 1.2, Admin

#4126 Clarify the meaning of max "votable" headings
  app/views/admin/budget_groups/_form.html.erb
  config/locales/en/activerecord.yml
  config/locales/en/admin.yml
  config/locales/es/activerecord.yml
  config/locales/es/admin.yml
  lib/consul_form_builder.rb
  spec/lib/consul_form_builder_spec.rb
  spec/system/admin/budget_groups_spec.rb
Labels: 1.2, Admin

#4122 Fix dashboard poster intro text
  config/locales/en/general.yml
Labels: 1.2, Bug

#4114 Get map center longitude from correct place
  app/assets/javascripts/map.js
  spec/shared/system/mappable.rb
Labels: 1.2, Bug

#4130 Add Serbian (Cyrillic) new language mapping
  crowdin.yml
Labels: 1.2, Translations

#4005 Simplify code related to the admin menu
  app/assets/stylesheets/admin.scss
  app/assets/stylesheets/dashboard.scss
  app/assets/stylesheets/foundation_and_overrides.scss
  app/assets/stylesheets/layout.scss
  app/assets/stylesheets/mixins.scss
  app/helpers/admin_helper.rb
  app/views/admin/_menu.html.erb
  app/views/layouts/admin.html.erb
  app/views/layouts/dashboard.html.erb
  app/views/layouts/management.html.erb
  app/views/layouts/proposals_dashboard.html.erb
  app/views/management/_account_info.html.erb
  app/views/management/_menu.html.erb
  app/views/moderation/_menu.html.erb
Labels: Refactoring

#4006 Make the admin menu fill the screen vertically
  app/assets/stylesheets/admin.scss
  app/assets/stylesheets/dashboard.scss
  app/assets/stylesheets/mixins.scss
  app/views/layouts/admin.html.erb
  app/views/layouts/dashboard.html.erb
  app/views/layouts/management.html.erb
Labels: Bug

#3956 Fix minor design details in admin front
  app/assets/stylesheets/admin.scss
  app/assets/stylesheets/layout.scss
Labels: UX

#4127 Make sure Puma has restarted properly
  config/deploy.rb
Labels: 1.2, Bug

#4138 Fix crash in management with successful proposals
  app/views/proposals/_support_status.html.erb
  spec/system/management/proposals_spec.rb
Labels: 1.2, Bug

#4129 Fix Airbrake crash with no project key
  config/initializers/errbit.rb
Labels: 1.2, Bug
