Repository consuldemocracy/consuldemocracy, pull requests merged in 2020-02, with the labels that each got.

#3913 Expire investment cache when its image changes
  app/views/budgets/investments/_investment_show.html.erb
Labels: Bug

#3910 Force dateFormat on datepicker
  app/assets/javascripts/advanced_search.js
  spec/features/admin/banners_spec.rb
Labels: Bug

#3914 Improve retired proposal page when translation interface is enabled.
  app/views/proposals/retire_form.html.erb
Labels: Citizen proposals

#3916 Fix filters for investments without admin/valuator
  app/models/budget/investment.rb
  spec/models/budget/investment_spec.rb
Labels: Bug

#3919 Align select admins and valuators with the rest of the form
  app/views/admin/budgets/_form.html.erb
Labels: Admin, Budgets, UX

#3915 Fix Polls link in admin menu
  app/helpers/admin_helper.rb
  app/views/admin/_menu.html.erb
  spec/features/admin/poll/booth_assigments_spec.rb
Labels: Bug

#3912 Refactor editing budget investments
  app/helpers/budget_investments_helper.rb
  app/views/budgets/investments/_author_actions.html.erb
  app/views/budgets/investments/_investment_show.html.erb
  app/views/users/_budget_investment.html.erb
  spec/features/budgets/investments_spec.rb
Labels: Budgets, UX

#3063 Check for missing feature specs for Poll::Question::Answer
  spec/features/admin/poll/questions/answers/images/images_spec.rb
  spec/features/polls/answers_spec.rb
Labels: Specs

#3921 Fix card description overflow
  app/assets/stylesheets/layout.scss
Labels: Bug

#3911 Improve Dashboard emails
  app/mailers/dashboard/mailer.rb
  app/models/setting.rb
  config/locales/en/settings.yml
  config/locales/es/settings.yml
  lib/tasks/consul.rake
  lib/tasks/settings.rake
  spec/lib/tasks/dashboards_spec.rb
  spec/mailers/dashboard/mailer_spec.rb
  spec/models/proposal_spec.rb
Labels: Bug

#3922 Add locales to datepicker
  app/assets/javascripts/application.js
Labels: Translations

#3924 Remove fallbacks = true from staging, preprod and prod
  config/environments/preproduction.rb
  config/environments/production.rb
  config/environments/staging.rb
Labels: Bug

#3926 Fix hidden active elements in admin menu
  app/views/admin/_menu.html.erb
  spec/features/admin_spec.rb
Labels: Bug

#3917 Improve remote translations
  app/controllers/concerns/remotely_translatable.rb
  app/models/remote_translation.rb
  config/locales/en/activerecord.yml
  config/locales/es/activerecord.yml
  spec/controllers/concerns/remotely_translatable_spec.rb
  spec/features/remote_translations_spec.rb
  spec/models/remote_translation_spec.rb
  spec/shared/features/remotely_translatable.rb
Labels: Translations

#3929 Fix flaky spec when unselecting an investment
  spec/features/admin/budget_investments_spec.rb
Labels: Specs

#3931 Specify which bundler version to install
  config/deploy.rb
Labels: Maintenance
