Repository consuldemocracy/consuldemocracy, pull requests merged in 2020-08, with the labels that each got.

#4073 Javascript fixes
  app/assets/javascripts/allow_participation.js
  app/assets/javascripts/application.js
  app/assets/javascripts/forms.js
  app/assets/javascripts/foundation_extras.js
  app/assets/javascripts/legislation_annotatable.js
  app/assets/javascripts/map.js
  app/assets/javascripts/stat_graphs.js
  app/assets/javascripts/table_sortable.js
  app/assets/javascripts/tags.js
  app/views/admin/stats/polls.html.erb
  spec/system/admin/settings_spec.rb
  spec/system/proposals_spec.rb
Labels: 1.2, Maintenance

#4063 Add approval voting to budgets
  app/controllers/admin/budget_headings_controller.rb
  app/controllers/admin/budgets_controller.rb
  app/helpers/budgets_helper.rb
  app/models/budget.rb
  app/models/budget/ballot.rb
  app/models/budget/heading.rb
  app/models/budget/voting_styles/approval.rb
  app/models/budget/voting_styles/base.rb
  app/models/budget/voting_styles/knapsack.rb
  app/views/admin/budget_headings/_form.html.erb
  app/views/admin/budget_headings/index.html.erb
  app/views/admin/budgets/_form.html.erb
  app/views/budgets/ballot/_progress_bar.html.erb
  app/views/budgets/ballot/progress_bar/_approval.html.erb
  app/views/budgets/ballot/progress_bar/_knapsack.html.erb
  config/i18n-tasks.yml
  config/locales/en/activerecord.yml
  config/locales/en/admin.yml
  config/locales/en/budgets.yml
  config/locales/es/activerecord.yml
  config/locales/es/admin.yml
  config/locales/es/budgets.yml
  db/migrate/20190418114431_add_approval_voting_fields.rb
  db/schema.rb
  spec/factories/budgets.rb
  spec/helpers/budgets_helper_spec.rb
  spec/models/budget/ballot/line_spec.rb
  spec/models/budget/ballot_spec.rb
  spec/models/budget/heading_spec.rb
  spec/models/budget/investment_spec.rb
  spec/models/budget_spec.rb
  spec/system/admin/budget_headings_spec.rb
  spec/system/admin/budgets_spec.rb
  spec/system/budgets/votes_spec.rb
Labels: 1.2, Budgets, Community Interest

#4066 Show Wordpress login button if it's the only one enabled
  app/assets/stylesheets/layout.scss
  app/helpers/settings_helper.rb
  app/views/devise/_omniauth_form.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/users/registrations/new.html.erb
  config/locales/en/general.yml
  config/locales/es/general.yml
  spec/system/users_auth_spec.rb
Labels: 1.2, Bug

#4070 Remove redundant calls to load resources
  app/controllers/budgets/executions_controller.rb
  app/controllers/budgets/groups_controller.rb
  app/controllers/budgets/investments_controller.rb
  app/controllers/budgets/results_controller.rb
  app/controllers/budgets/stats_controller.rb
Labels: Refactoring

#4047 Allow voting when skip verification is enabled
  app/controllers/polls/questions_controller.rb
  app/models/poll/answer.rb
  app/models/poll/voter.rb
  config/locales/en/activerecord.yml
  config/locales/es/activerecord.yml
  spec/models/poll/answer_spec.rb
  spec/models/poll/voter_spec.rb
Labels: Bug, Polls

#4076 Use complete keys on legislation translations
  app/views/admin/legislation/draft_versions/index.html.erb
  app/views/legislation/annotations/_version_chooser.html.erb
  app/views/legislation/annotations/index.html.erb
  app/views/legislation/annotations/show.html.erb
  app/views/legislation/draft_versions/changes.html.erb
  app/views/legislation/draft_versions/show.html.erb
  app/views/legislation/processes/_process.html.erb
  app/views/legislation/processes/index.html.erb
  app/views/legislation/processes/phase_empty.html.erb
  app/views/legislation/processes/phase_not_open.html.erb
  app/views/legislation/questions/_question.html.erb
  app/views/legislation/questions/show.html.erb
  config/locales/en/legislation.yml
Labels: Legislation, Translations

#4067 Allow links and images on legislation drafts
  app/helpers/application_helper.rb
  app/views/legislation/draft_versions/show.html.erb
  lib/admin_legislation_sanitizer.rb
  spec/system/xss_spec.rb
Labels: 1.2, Bug

#4081 Add feature flag exception for the module polls
  app/controllers/admin/poll/base_controller.rb
  app/controllers/polls_controller.rb
  spec/system/admin/poll/polls_spec.rb
  spec/system/polls/polls_spec.rb
Labels: 1.2, Bug

#4078 Bump mdl from 0.5.0 to 0.10.0
  .mdlrc
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT_ES.md
  Gemfile
  Gemfile.lock
  doc/api/api_en.md
  doc/api/api_es.md
Labels: 1.2, dependencies

#4079 Fix redirect with GET params of after POST requests
  app/controllers/application_controller.rb
  app/controllers/users/sessions_controller.rb
  spec/system/sessions_spec.rb
Labels: 1.2, Bug

#3699 Bump turbolinks to 5.2.1
  Gemfile
  Gemfile.lock
  app/assets/javascripts/application.js
  app/assets/javascripts/check_all_none.js
  app/assets/javascripts/columns_selector.js
  app/assets/javascripts/datepicker.js
  app/assets/javascripts/html_editor.js
  app/assets/javascripts/legislation_annotatable.js
  app/assets/javascripts/legislation_draft_versions.js
  app/assets/javascripts/managers.js
  app/assets/javascripts/map.js
  app/assets/javascripts/markdown_editor.js
  app/assets/javascripts/settings.js
  app/assets/javascripts/social_share.js
  app/assets/javascripts/stat_graphs.js
  app/assets/javascripts/turbolinks_anchors.js
  app/assets/javascripts/watch_form_changes.js
  app/views/admin/budget_investments/show.html.erb
  app/views/admin/legislation/draft_versions/_form.html.erb
  app/views/admin/legislation/draft_versions/edit.html.erb
  app/views/admin/legislation/homepages/_form.html.erb
  app/views/admin/legislation/processes/_form.html.erb
  app/views/admin/legislation/proposals/_form.html.erb
  app/views/admin/legislation/questions/_form.html.erb
  app/views/admin/site_customization/content_blocks/_form_content_block.html.erb
  app/views/admin/site_customization/pages/_form.html.erb
  app/views/admin/stats/budget_supporting.html.erb
  app/views/admin/stats/graph.html.erb
  app/views/budgets/groups/show.html.erb
  app/views/budgets/show.html.erb
  app/views/dashboard/progress.html.erb
  app/views/layouts/_common_head.html.erb
  app/views/layouts/admin.html.erb
  app/views/layouts/dashboard.html.erb
  app/views/layouts/proposals_dashboard.html.erb
  app/views/legislation/annotations/_comments_box.html.erb
  app/views/legislation/annotations/_comments_box_form.js.erb
  config/locales/en/admin.yml
  config/locales/en/general.yml
  config/locales/es/admin.yml
  config/locales/es/general.yml
  spec/shared/system/mappable.rb
  spec/support/common_actions/verifications.rb
  spec/system/admin/banners_spec.rb
  spec/system/admin/budget_investments_spec.rb
  spec/system/admin/legislation/draft_versions_spec.rb
  spec/system/legislation/draft_versions_spec.rb
  spec/system/proposals_spec.rb
Labels: 1.2, dependencies

#4080 Fix banner overlapping with other content
  app/assets/stylesheets/layout.scss
  app/assets/stylesheets/participation.scss
  app/helpers/banners_helper.rb
  app/models/banner.rb
  app/views/admin/banners/_form.html.erb
  app/views/budgets/index.html.erb
  app/views/shared/_section_header.html.erb
  spec/models/banner_spec.rb
Labels: 1.2, Bug

#4077 Fix poll answer images not being displayed
  app/assets/stylesheets/participation.scss
  app/views/polls/_gallery.html.erb
  spec/system/polls/polls_spec.rb
Labels: 1.2, Bug

#4083 Don't disable button to download emails
  app/assets/javascripts/application.js
  app/assets/javascripts/prevent_double_submission.js
  app/views/admin/emails_download/index.html.erb
  spec/system/admin/emails/emails_download_spec.rb
  spec/system/comments/debates_spec.rb
  spec/system/comments/legislation_annotations_spec.rb
  spec/system/comments/legislation_questions_spec.rb
Labels: 1.2, Admin, Bug

#4082 Disable phase date fields when a phase is disabled
  app/assets/javascripts/legislation_admin.js
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/layout.scss
  app/assets/stylesheets/legislation_process_form.scss
  app/views/admin/legislation/processes/_form.html.erb
  spec/system/admin/legislation/processes_spec.rb
Labels: 1.2, Admin, Bug

#4096 Fix sticky element on medium/large screens
  app/assets/javascripts/foundation_extras.js
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/sticky_overrides.scss
  spec/system/proposals_spec.rb
Labels: 1.2, Bug

#4097 Downgrade sassc from 2.4.0 to 2.2.1
  Gemfile.lock
Labels: 1.2, dependencies

#4087 Fix invalid "hint" attribute in forms
  lib/consul_form_builder.rb
  spec/lib/consul_form_builder_spec.rb
Labels: Bug

#3624 Add support for Errbit self-hosted exception management
  Gemfile
  Gemfile.lock
  config/initializers/errbit.rb
  config/initializers/rollbar.rb
  config/secrets.yml.example
Labels: 1.2

#4111 Use native HTML5 date fields in the admin section
  app/assets/javascripts/advanced_search.js
  app/assets/javascripts/application.js
  app/assets/javascripts/datepicker.js
  app/assets/javascripts/legislation_admin.js
  app/helpers/legislation_helper.rb
  app/views/admin/banners/_form.html.erb
  app/views/admin/budget_phases/_form.html.erb
  app/views/admin/legislation/processes/_form.html.erb
  app/views/admin/milestones/_form.html.erb
  app/views/admin/poll/polls/_form.html.erb
  lib/consul_form_builder.rb
  spec/system/admin/banners_spec.rb
  spec/system/admin/legislation/processes_spec.rb
  spec/system/dashboard/polls_spec.rb
Labels: 1.2, UX

#4112 Simplify banner form dates
  app/views/admin/banners/_form.html.erb
Labels: 1.2, Refactoring
