Repository consuldemocracy/consuldemocracy, pull requests merged in 2020-05, with the labels that each got.

#3997 Do not run all javascript after every ajax call
  app/assets/javascripts/application.js
  app/assets/javascripts/comments.js
  app/assets/javascripts/legislation_annotatable.js
  spec/system/comments/debates_spec.rb
Labels: Bug

#3998 Destroy and intialize ckeditor on browser history back
  app/assets/javascripts/ckeditor/reinit.js
  app/assets/javascripts/html_editor.js
  spec/system/ckeditor_spec.rb
Labels: Bug

#4008 Simplify code to render comments
  Gemfile
  Gemfile.lock
  app/assets/javascripts/comments.js
  app/assets/stylesheets/layout.scss
  app/views/budgets/investments/show.html.erb
  app/views/comments/_comment.html.erb
  app/views/comments/_comment_list.html.erb
  app/views/comments/_comment_tree.html.erb
  app/views/comments/_commentable_tree.html.erb
  app/views/comments/_form.html.erb
  app/views/comments/create.js.erb
  app/views/debates/_comments.html.erb
  app/views/legislation/annotations/show.html.erb
  app/views/legislation/proposals/_comments.html.erb
  app/views/legislation/questions/show.html.erb
  app/views/polls/_comments.html.erb
  app/views/proposals/_comments.html.erb
  app/views/topics/_comments.html.erb
  app/views/valuation/budget_investments/_valuation_comments.html.erb
  config/locales/en/general.yml
  config/locales/es/general.yml
  spec/shared/system/notifiable_in_app.rb
  spec/support/common_actions/comments.rb
  spec/support/common_actions/notifications.rb
  spec/system/comments/budget_investments_spec.rb
  spec/system/comments/budget_investments_valuation_spec.rb
  spec/system/comments/debates_spec.rb
  spec/system/comments/legislation_annotations_spec.rb
  spec/system/comments/legislation_questions_spec.rb
  spec/system/comments/polls_spec.rb
  spec/system/comments/proposals_spec.rb
  spec/system/comments/topics_spec.rb
  spec/system/emails_spec.rb
Labels: Refactoring

#3992 Check remote translations locales at runtime
  app/models/remote_translation.rb
  spec/controllers/remote_translation_controller_spec.rb
  spec/lib/remote_translations/caller_spec.rb
  spec/models/remote_translation_spec.rb
  spec/spec_helper.rb
Labels: Translations

#3995 Do not update form location fields when marker is not defined
  app/assets/javascripts/map.js
Labels: Bug

#4010 Fix flaky nested documentable / imageable specs
  spec/shared/system/nested_documentable.rb
  spec/shared/system/nested_imageable.rb
Labels: Specs

#3768 Don't count errors for the same field twice
  app/views/shared/_errors.html.erb
  spec/system/admin/dashboard/actions_spec.rb
  spec/views/shared/errors_spec.rb
Labels: UX

#4012 Simplify chromedriver installation with webdrivers
  .travis.yml
  Dockerfile
  Gemfile
  Gemfile.lock
  README.md
  README_ES.md
  spec/rails_helper.rb
Labels: Maintenance

#4003 Update comment responses count when adding replies
  app/assets/javascripts/comments.js
  app/assets/javascripts/users.js
  app/assets/stylesheets/layout.scss
  app/views/comments/_comment.html.erb
  app/views/comments/_responses_count.html.erb
  app/views/comments/create.js.erb
  spec/system/comments/budget_investments_spec.rb
  spec/system/comments/budget_investments_valuation_spec.rb
  spec/system/comments/debates_spec.rb
  spec/system/comments/legislation_annotations_spec.rb
  spec/system/comments/legislation_questions_spec.rb
  spec/system/comments/polls_spec.rb
  spec/system/comments/proposals_spec.rb
  spec/system/comments/topics_spec.rb
  spec/system/users_spec.rb
Labels: Bug
