Repository consuldemocracy/consuldemocracy, pull requests merged in 2020-06, with the labels that each got.

#4026 Fix chromedriver hanging with CKEditor
  spec/rails_helper.rb
  spec/support/common_actions/verifications.rb
  spec/support/matchers/have_ckeditor.rb
Labels: Specs

#3952 Use "resolve" for polymorphic hierarchy paths
  app/controllers/admin/milestones_controller.rb
  app/controllers/admin/progress_bars_controller.rb
  app/controllers/comments_controller.rb
  app/controllers/notifications_controller.rb
  app/helpers/comments_helper.rb
  app/views/admin/audits/_audits.html.erb
  app/views/admin/audits/show.html.erb
  app/views/admin/milestones/_form.html.erb
  app/views/admin/milestones/_milestones.html.erb
  app/views/admin/progress_bars/_form.html.erb
  app/views/admin/progress_bars/_progress_bars.html.erb
  app/views/admin/progress_bars/index.html.erb
  config/initializers/routes_hierarchy.rb
  config/routes/admin.rb
  config/routes/budget.rb
  config/routes/community.rb
  config/routes/legislation.rb
  config/routes/poll.rb
  spec/routing/polymorphic_routes_spec.rb
  spec/shared/system/admin_milestoneable.rb
  spec/shared/system/admin_progressable.rb
  spec/shared/system/milestoneable.rb
  spec/shared/system/progressable.rb
  spec/support/common_actions/notifications.rb
  spec/system/admin/budget_investments_spec.rb
  spec/system/admin/proposals_spec.rb
  spec/system/admin/translatable_spec.rb
  spec/system/budgets/investments_spec.rb
  spec/system/proposals_spec.rb
  spec/system/xss_spec.rb
Labels: Refactoring

#4007 Use a memory cache store in development
  config/environments/development.rb
Labels: Maintenance

#4036 Apply Layout/SpaceAroundMethodCallOperator rule
  .hound.yml
  .rubocop.yml
  Gemfile
  Gemfile.lock
  config/initializers/ckeditor.rb
  spec/system/admin/poll/polls_spec.rb
  spec/system/admin/translatable_spec.rb
Labels: Rubocop

#4038 Fix deleting searched managers/moderators/admins
  app/views/admin/administrators/index.html.erb
  app/views/admin/administrators/search.html.erb
  app/views/admin/managers/index.html.erb
  app/views/admin/managers/search.html.erb
  app/views/admin/moderators/index.html.erb
  app/views/admin/moderators/search.html.erb
  app/views/admin/officials/index.html.erb
  spec/system/admin/administrators_spec.rb
  spec/system/admin/managers_spec.rb
  spec/system/admin/moderators_spec.rb
Labels: Bug

#4040 Rename admin proposal notifications controller
  app/controllers/admin/hidden_proposal_notifications_controller.rb
  app/helpers/admin_helper.rb
  app/views/admin/_menu.html.erb
  app/views/admin/hidden_proposal_notifications/index.html.erb
  config/i18n-tasks.yml
  config/locales/en/admin.yml
  config/locales/es/admin.yml
  config/routes/admin.rb
  spec/system/admin/proposal_notifications_spec.rb
Labels: Maintenance

#4046 Remove unused document section on polls
  app/views/polls/show.html.erb
Labels: Polls

#4001 Discard session[:locale] when is not valid
  app/controllers/admin/site_customization/information_texts_controller.rb
  app/controllers/application_controller.rb
  app/controllers/management/base_controller.rb
  spec/spec_helper.rb
  spec/system/localization_spec.rb
Labels: Bug
