Repository consuldemocracy/consuldemocracy, pull requests merged in 2020-04, with the labels that each got.

#3895 Support creates follow
  app/controllers/management/proposals_controller.rb
  app/controllers/proposals_controller.rb
  app/models/proposal.rb
  app/views/mailer/proposal_notification_digest.html.erb
  app/views/proposals/vote.js.erb
  config/locales/en/general.yml
  config/locales/en/mailers.yml
  config/locales/en/settings.yml
  config/locales/es/general.yml
  config/locales/es/mailers.yml
  config/locales/es/settings.yml
  spec/features/dashboard/dashboard_spec.rb
  spec/features/emails_spec.rb
  spec/features/management/proposals_spec.rb
  spec/features/proposal_notifications_spec.rb
  spec/models/proposal_spec.rb
  spec/support/common_actions/notifications.rb
Labels: Proposals

#3477 Fix a bug where a category can't be created if it already exists as a tag
  app/controllers/admin/tags_controller.rb
  spec/features/admin/tags_spec.rb
Labels: Bug

#3963 Apply escape_javascript security patch
  .rubocop.yml
  config/initializers/escape_javascript_fix.rb
Labels: security

#3940 Add title to differentiate signature sheets
  app/controllers/admin/signature_sheets_controller.rb
  app/models/signature_sheet.rb
  app/views/admin/signature_sheets/new.html.erb
  config/locales/en/activerecord.yml
  config/locales/es/activerecord.yml
  db/migrate/20190621181440_add_name_field_to_signature_sheets.rb
  db/schema.rb
  spec/factories/proposals.rb
  spec/features/admin/signature_sheets_spec.rb
  spec/models/signature_sheet_spec.rb
Labels: Admin

#3966 Remove unused tag filter
  app/controllers/concerns/commentable_actions.rb
  app/controllers/debates_controller.rb
  app/controllers/legislation/proposals_controller.rb
  app/controllers/proposals_controller.rb
  app/views/debates/index.html.erb
  app/views/proposals/index.html.erb
  config/locales/en/general.yml
  config/locales/es/general.yml
Labels: Maintenance

#3967 Fix duplicate records in investments by tag
  app/helpers/budget_executions_helper.rb
  app/models/budget/investment.rb
  spec/helpers/budget_executions_helper_spec.rb
  spec/models/budget/investment_spec.rb
Labels: Bug

#3959 Fix custom translations with options
  config/initializers/i18n_translation.rb
  spec/features/site_customization/information_texts_spec.rb
Labels: Bug

#3968 Fix flaky spec: Admin Active polls Add
  spec/features/admin/budget_phases_spec.rb
  spec/features/admin/legislation/processes_spec.rb
  spec/shared/features/nested_documentable.rb
  spec/support/common_actions/verifications.rb
Labels: Specs

#3969 Order legislation process tags alphabetically
  app/views/admin/legislation/proposals/_form.html.erb
  spec/features/admin/legislation/processes_spec.rb
Labels: Bug

#3856 Get search dictionary based on I18n.default_locale
  app/models/concerns/search_cache.rb
  app/models/concerns/searchable.rb
  lib/search_dictionary_selector.rb
  spec/features/proposals_spec.rb
  spec/lib/search_dictionary_selector_spec.rb
  spec/models/debate_spec.rb
  spec/models/proposal_spec.rb
  spec/spec_helper.rb
Labels: Translations

#3974 Don't include unneeded helpers in tests
  app/helpers/documentables_helper.rb
  app/helpers/documents_helper.rb
  app/helpers/imageables_helper.rb
  spec/features/comments/budget_investments_spec.rb
  spec/features/comments/debates_spec.rb
  spec/features/comments/legislation_annotations_spec.rb
  spec/features/comments/legislation_questions_spec.rb
  spec/features/comments/polls_spec.rb
  spec/features/comments/proposals_spec.rb
  spec/features/comments/topics_spec.rb
  spec/shared/features/documentable.rb
  spec/shared/features/followable.rb
  spec/shared/features/imageable.rb
  spec/shared/features/imageable_destroy.rb
  spec/shared/features/mappable.rb
  spec/shared/features/nested_documentable.rb
  spec/shared/features/nested_imageable.rb
  spec/shared/models/document_validations.rb
  spec/shared/models/image_validations.rb
Labels: Specs

#3975 Fix checking for nil in page content
  spec/features/admin/valuators_spec.rb
  spec/features/admin/verifications_spec.rb
Labels: Specs

#3972 Replaces icons of expand/collapse comments
  app/assets/javascripts/comments.js
  app/assets/stylesheets/icons.scss
  app/assets/stylesheets/layout.scss
  app/views/comments/_comment.html.erb
Labels: UX

#3976 Deactivate ckeditor file attachments feature
  app/assets/javascripts/ckeditor/config.js
  spec/features/ckeditor_spec.rb
Labels: Bug

#3973 Replace equalizer to display flex on cards
  app/assets/stylesheets/layout.scss
  app/views/pages/_cards.html.erb
  app/views/pages/custom_page.html.erb
  app/views/shared/_card.html.erb
  app/views/shared/_cards.html.erb
  app/views/welcome/_card.html.erb
  app/views/welcome/_cards.html.erb
  app/views/welcome/index.html.erb
Labels: UX

#3979 Allow to paste formatted content into ckeditors
  app/assets/javascripts/ckeditor/config.js
  config/initializers/ckeditor.rb
Labels: UX

#3977 Fix attaching images in CKEditor via drag and drop
  app/assets/javascripts/ckeditor/config.js
Labels: Bug

#3981 Disable ckeditor unused plugins
  app/assets/javascripts/ckeditor/config.js
  config/initializers/ckeditor.rb
Labels: Maintenance

#3983 Add ckeditor tabletools plugin
  config/initializers/ckeditor.rb
Labels: Bug

#3982 Mitigate flaky specs for vote multiple times
  spec/system/comments/budget_investments_spec.rb
  spec/system/comments/polls_spec.rb
  spec/system/comments/proposals_spec.rb
  spec/system/comments/topics_spec.rb
Labels: Specs

#3987 Fix source translations
  config/locales/en/general.yml
  config/locales/en/mailers.yml
  spec/mailers/dashboard/mailer_spec.rb
Labels: Translations

#3633 Use Rails 5.1 methods to simplify code
  app/controllers/valuation/budget_investments_controller.rb
  app/helpers/admin/local_census_records/imports_helper.rb
  app/helpers/application_helper.rb
  app/helpers/banners_helper.rb
  app/helpers/budget_investments_helper.rb
  app/helpers/budgets_helper.rb
  app/helpers/documents_helper.rb
  app/helpers/globalize_helper.rb
  app/helpers/layouts_helper.rb
  app/helpers/map_locations_helper.rb
  app/helpers/milestones_helper.rb
  app/helpers/stats_helper.rb
  app/helpers/translatable_form_helper.rb
  app/helpers/users_helper.rb
  app/models/direct_message.rb
  app/models/poll.rb
  app/views/admin/legislation/questions/index.html.erb
  app/views/admin/poll/officer_assignments/by_officer.html.erb
  app/views/legislation/questions/show.html.erb
  app/views/management/budgets/investments/index.html.erb
  lib/consul_form_builder.rb
Labels: Maintenance

#3985 Increase severity of DynamicFindBy rubocop rule
  .rubocop.yml
Labels: Rubocop

#3990 Update contributing
  CONTRIBUTING.md
  CONTRIBUTING_ES.md
Labels: Maintenance

#3960 Update ruby version docker
  Dockerfile
Labels: Maintenance
