Repository consuldemocracy/consuldemocracy, pull requests merged in 2020-01, with the labels that each got.

#3830 Fix pagination problem on mobile
  app/assets/stylesheets/layout.scss
Labels: Bug

#3823 Update contributing guidelines
  CONTRIBUTING.md
  CONTRIBUTING_ES.md
  README.md
  README_ES.md
Labels: Documentation

#3900 Fix style for validation errors in HTML areas
  app/assets/stylesheets/layout.scss
Labels: Bug

#3901 Fix uploading images through CKEditor's upload tab
  app/assets/javascripts/ckeditor/config.js
  spec/features/ckeditor_spec.rb
Labels: Bug

#3606 Add Font Awesome icons
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/icons.scss
  app/assets/stylesheets/layout.scss
Labels: UX

#3840 Add CSRF protection to Omniauth requests
  Gemfile
  Gemfile.lock
  app/views/devise/_omniauth_form.html.erb
Labels: security
