Repository consuldemocracy/consuldemocracy, pull requests merged in 2020-07, with the labels that each got.

#3948 Fix bug flagging legislation proposals
  app/assets/javascripts/flaggable.js
  app/controllers/comments_controller.rb
  app/controllers/concerns/flag_actions.rb
  app/views/admin/debates/show.html.erb
  app/views/budgets/investments/_flag_actions.html.erb
  app/views/budgets/investments/_investment_detail.erb
  app/views/budgets/investments/_refresh_flag_actions.js.erb
  app/views/comments/_actions.html.erb
  app/views/comments/_flag_actions.html.erb
  app/views/comments/_refresh_flag_actions.js.erb
  app/views/debates/_flag_actions.html.erb
  app/views/debates/_refresh_flag_actions.js.erb
  app/views/debates/show.html.erb
  app/views/legislation/proposals/_flag_actions.html.erb
  app/views/legislation/proposals/_refresh_flag_actions.js.erb
  app/views/legislation/proposals/show.html.erb
  app/views/proposals/_flag_actions.html.erb
  app/views/proposals/_info.html.erb
  app/views/proposals/_refresh_flag_actions.js.erb
  app/views/shared/_flag_actions.html.erb
  app/views/shared/_refresh_flag_actions.js.erb
  spec/factories/comments.rb
  spec/shared/system/flaggable.rb
  spec/system/admin/debates_spec.rb
  spec/system/budgets/investments_spec.rb
  spec/system/comments/budget_investments_spec.rb
  spec/system/comments/debates_spec.rb
  spec/system/comments/legislation_annotations_spec.rb
  spec/system/comments/legislation_questions_spec.rb
  spec/system/comments/polls_spec.rb
  spec/system/comments/proposals_spec.rb
  spec/system/comments/topics_spec.rb
  spec/system/debates_spec.rb
  spec/system/legislation/proposals_spec.rb
  spec/system/proposals_spec.rb
Labels: Bug

#3978 Upgrade Ruby to 2.5.8
  .rubocop.yml
  .ruby-version
  README.md
  README_ES.md
  app/controllers/polls_controller.rb
  app/models/setting.rb
Labels: Maintenance

#4054 Allow deleting polls with answers including videos
  app/models/poll/question/answer.rb
  spec/system/admin/poll/polls_spec.rb
Labels: Admin, Bug, Polls

#4028 Add Rails 5.2 compatibility
  Gemfile
  Gemfile.lock
  app/controllers/graphql_controller.rb
  app/controllers/proposals_controller.rb
  app/controllers/users_controller.rb
  app/models/application_record.rb
  app/models/budget/investment.rb
  app/models/community.rb
  app/models/concerns/searchable.rb
  app/models/tag_cloud.rb
  app/models/user.rb
  config/application.rb
  config/deploy.rb
  config/initializers/acts_as_taggable_on.rb
  config/initializers/graphql_api.rb
  db/dev_seeds/budgets.rb
  db/dev_seeds/flags.rb
  db/dev_seeds/hiddings.rb
  db/dev_seeds/notifications.rb
  db/dev_seeds/polls.rb
  db/dev_seeds/votes.rb
  db/migrate/20200519120717_rename_columns_with_slash_characters.rb
  db/schema.rb
  lib/graph_ql/api_types_creator.rb
  lib/tasks/budgets.rake
  lib/tasks/consul.rake
  lib/tasks/local_census_records.rake
  lib/tasks/migrations.rake
  lib/tasks/secrets.rake
  lib/user_segments.rb
  spec/controllers/pages_controller_spec.rb
  spec/lib/graph_ql/query_type_creator_spec.rb
  spec/lib/graphql_spec.rb
  spec/lib/tasks/budgets_spec.rb
  spec/lib/tasks/local_census_records_spec.rb
  spec/lib/tasks/migrations_spec.rb
  spec/models/community_spec.rb
Labels: Maintenance

#4050 Improve test checking order by relevance
  spec/models/debate_spec.rb
  spec/spec_helper.rb
  spec/system/proposals_spec.rb
Labels: Specs

#4034 Add processes feature info section in the help page
  app/views/pages/help/_processes.html.erb
  config/locales/en/pages.yml
  config/locales/es/pages.yml
Labels: Bug

#4064 Remove Google plus share button
  app/assets/fonts/icons.svg
  app/assets/stylesheets/icons.scss
  app/assets/stylesheets/layout.scss
  app/assets/stylesheets/participation.scss
  config/initializers/social_share_button.rb
  config/locales/en/social_share_button.yml
  config/locales/es/social_share_button.yml
  spec/system/debates_spec.rb
  spec/system/proposals_spec.rb
Labels: Maintenance

#4061 Fix race condition with ballot lines
  Gemfile
  app/models/budget/ballot/line.rb
  spec/models/budget/ballot/line_spec.rb
  spec/models/budget/stats_spec.rb
  spec/spec_helper.rb
Labels: 1.2, Bug, security

#4068 Do not delete users when deleting legislation answers
  app/models/legislation/answer.rb
  spec/models/legislation/answer_spec.rb
Labels: 1.2, Bug

#4062 Refactor ballot / ballot line voting logic
  app/assets/stylesheets/participation.scss
  app/controllers/budgets/ballot/lines_controller.rb
  app/controllers/budgets/ballots_controller.rb
  app/controllers/budgets/investments_controller.rb
  app/helpers/ballots_helper.rb
  app/models/budget.rb
  app/models/budget/ballot.rb
  app/models/budget/ballot/line.rb
  app/models/budget/investment.rb
  app/models/budget/voting_styles/base.rb
  app/models/budget/voting_styles/knapsack.rb
  app/views/budgets/ballot/_ballot.html.erb
  app/views/budgets/ballot/_progress_bar.html.erb
  app/views/budgets/ballot/lines/create.js.erb
  app/views/budgets/ballot/lines/destroy.js.erb
  app/views/budgets/investments/_header.html.erb
  app/views/budgets/investments/_sidebar.html.erb
  config/i18n-tasks.yml
  config/locales/en/budgets.yml
  config/locales/es/budgets.yml
Labels: 1.2, Refactoring
