Repository consuldemocracy/consuldemocracy, pull requests merged in 2021-11, with the labels that each got.

#4718 Simplify navigation in single heading budgets
  app/components/budgets/ballot/ballot_component.html.erb
  app/components/budgets/ballot/ballot_component.rb
  app/controllers/budgets/investments_controller.rb
  app/views/budgets/ballot/_ballot.html.erb
  spec/components/budgets/ballot/ballot_component_spec.rb
  spec/system/budgets/ballots_spec.rb
  spec/system/budgets/investments_spec.rb
Labels: Budgets, UX

#4721 Fix Sass deprecation warning
  app/assets/stylesheets/_consul_settings.scss
Labels: Maintenance

#4729 Add consistency between deploy-secrets and installer
  config/deploy-secrets.yml.example
Labels: Maintenance

#4725 Add SDG icons in Croatian
  vendor/assets/images/sdg/hr/goal_1.png
  vendor/assets/images/sdg/hr/goal_10.png
  vendor/assets/images/sdg/hr/goal_11.png
  vendor/assets/images/sdg/hr/goal_12.png
  vendor/assets/images/sdg/hr/goal_13.png
  vendor/assets/images/sdg/hr/goal_14.png
  vendor/assets/images/sdg/hr/goal_15.png
  vendor/assets/images/sdg/hr/goal_16.png
  vendor/assets/images/sdg/hr/goal_17.png
  vendor/assets/images/sdg/hr/goal_2.png
  vendor/assets/images/sdg/hr/goal_3.png
  vendor/assets/images/sdg/hr/goal_4.png
  vendor/assets/images/sdg/hr/goal_5.png
  vendor/assets/images/sdg/hr/goal_6.png
  vendor/assets/images/sdg/hr/goal_7.png
  vendor/assets/images/sdg/hr/goal_8.png
  vendor/assets/images/sdg/hr/goal_9.png
  vendor/assets/images/sdg/hr/original/goal_1.jpg
  vendor/assets/images/sdg/hr/original/goal_10.jpg
  vendor/assets/images/sdg/hr/original/goal_11.jpg
  vendor/assets/images/sdg/hr/original/goal_12.jpg
  vendor/assets/images/sdg/hr/original/goal_13.jpg
  vendor/assets/images/sdg/hr/original/goal_14.jpg
  vendor/assets/images/sdg/hr/original/goal_15.jpg
  vendor/assets/images/sdg/hr/original/goal_16.jpg
  vendor/assets/images/sdg/hr/original/goal_17.jpg
  vendor/assets/images/sdg/hr/original/goal_2.jpg
  vendor/assets/images/sdg/hr/original/goal_3.jpg
  vendor/assets/images/sdg/hr/original/goal_4.jpg
  vendor/assets/images/sdg/hr/original/goal_5.jpg
  vendor/assets/images/sdg/hr/original/goal_6.jpg
  vendor/assets/images/sdg/hr/original/goal_7.jpg
  vendor/assets/images/sdg/hr/original/goal_8.jpg
  vendor/assets/images/sdg/hr/original/goal_9.jpg
Labels: Translations, SDG

#4726 Translate budget and budget phase main link url
  app/components/admin/budget_phases/form_component.html.erb
  app/components/admin/budgets/form_component.html.erb
  app/controllers/admin/budgets_controller.rb
  app/controllers/admin/budgets_wizard/budgets_controller.rb
  app/controllers/concerns/admin/budget_phases_actions.rb
  app/models/budget.rb
  app/models/budget/phase.rb
  app/models/concerns/globalizable.rb
  config/locales/en/activerecord.yml
  config/locales/en/admin.yml
  config/locales/es/activerecord.yml
  config/locales/es/admin.yml
  db/migrate/20211103090940_translate_budget_main_link_url.rb
  db/migrate/20211103112944_translate_budget_phase_main_link_url.rb
  db/schema.rb
  spec/factories/proposals.rb
  spec/models/concerns/globalizable.rb
  spec/models/milestone_spec.rb
  spec/models/progress_bar_spec.rb
  spec/models/proposal_spec.rb
  spec/system/admin/translatable_spec.rb
Labels: Budgets

#4684 Remove a potentially pre-existing server.pid in entrypoint.sh
  scripts/entrypoint.sh
Labels: Devops

#4730 Add setting to allow removing investments supports
  app/assets/stylesheets/admin.scss
  app/assets/stylesheets/participation.scss
  app/components/budgets/investments/votes_component.html.erb
  app/controllers/budgets/investments/votes_controller.rb
  app/models/setting.rb
  app/views/budgets/investments/_investment.html.erb
  app/views/budgets/investments/_investment_show.html.erb
  config/locales/en/settings.yml
  config/locales/es/settings.yml
  db/dev_seeds/settings.rb
  spec/components/budgets/investments/votes_component_spec.rb
  spec/controllers/budgets/investments/votes_controller_spec.rb
  spec/system/budgets/budgets_spec.rb
  spec/system/budgets/investments_spec.rb
  spec/system/management/budget_investments_spec.rb
Labels: Budgets, 1.4

#4732 Fix investment list layout on small/medium screens
  app/assets/stylesheets/participation.scss
  app/components/budgets/investments/votes_component.html.erb
  app/views/management/budgets/investments/index.html.erb
Labels: Bug, UX, 1.4

#4711 Fix typos in budget administration texts
  config/locales/en/admin.yml
Labels: Bug, Budgets, Translations, 1.4

#4735 Fix Rubocop convention offenses
  spec/system/admin/budget_groups_spec.rb
  spec/system/budgets/budgets_spec.rb
Labels: Rubocop

#3855 Add Security/Open rubocop rule
  .rubocop.yml
  app/models/concerns/attachable.rb
  lib/sms_api.rb
  lib/tasks/active_storage.rake
  spec/controllers/proposals_controller_spec.rb
Labels: security, Rubocop, 1.4

#4736 Fix typos in proposals dashboard and budgets admin
  config/locales/en/admin.yml
  config/locales/en/general.yml
Labels: Bug, 1.4

#4740 Fix flaky spec in campaign-tracking tests
  spec/system/campaigns_spec.rb
Labels: Flaky spec, 1.4

#4739 Make investment filters less prominent
  app/models/budget.rb
  app/views/budgets/investments/_sidebar.html.erb
  config/locales/en/budgets.yml
  config/locales/es/budgets.yml
  spec/components/budgets/investments/filters_component_spec.rb
  spec/models/budget_spec.rb
  spec/system/budgets/investments_spec.rb
Labels: Budgets, UX, 1.4

#4741 Query the database before a visit in campaigns test
  spec/system/campaigns_spec.rb
Labels: Flaky spec, 1.4

#4743 Update translations from Crowdin
  config/locales/ar/budgets.yml
  config/locales/ast/budgets.yml
  config/locales/bg-BG/budgets.yml
  config/locales/bs-BA/budgets.yml
  config/locales/ca/budgets.yml
  config/locales/cs-CZ/budgets.yml
  config/locales/da-DK/budgets.yml
  config/locales/de-DE/budgets.yml
  config/locales/el-GR/budgets.yml
  config/locales/en-GB/budgets.yml
  config/locales/es-PE/budgets.yml
  config/locales/eu-ES/budgets.yml
  config/locales/fa-IR/budgets.yml
  config/locales/fr/budgets.yml
  config/locales/gl/budgets.yml
  config/locales/he/budgets.yml
  config/locales/hr-HR/budgets.yml
  config/locales/id-ID/budgets.yml
  config/locales/it/budgets.yml
  config/locales/ka-GE/budgets.yml
  config/locales/mk-MK/budgets.yml
  config/locales/nl/budgets.yml
  config/locales/oc-FR/budgets.yml
  config/locales/pl-PL/budgets.yml
  config/locales/pt-BR/budgets.yml
  config/locales/ro-RO/budgets.yml
  config/locales/ru/budgets.yml
  config/locales/sl-SI/budgets.yml
  config/locales/so-SO/budgets.yml
  config/locales/sq-AL/budgets.yml
  config/locales/sr/budgets.yml
  config/locales/sv-SE/budgets.yml
  config/locales/tr-TR/budgets.yml
  config/locales/uk-UA/budgets.yml
  config/locales/val/budgets.yml
  config/locales/zh-CN/budgets.yml
  config/locales/zh-TW/budgets.yml
Labels: Translations, 1.4

#4745 Fix user edit page title
  config/locales/es/devise_views.yml
Labels: Bug, Translations, 1.4

#4720 Release version 1.4.0
  CHANGELOG.md
  README.md
  README_ES.md
  Rakefile
  app/controllers/installation_controller.rb
Labels: Maintenance

#4748 Change the way we handle source strings updates
  crowdin.yml
Labels: Translations

#4749 Release version 1.4.1
  CHANGELOG.md
  Rakefile
  app/controllers/installation_controller.rb
Labels: Maintenance
