Repository consuldemocracy/consuldemocracy, pull requests merged in 2021-12, with the labels that each got.

#4645 Remove newrelic and rollbar gem dependencies
  Gemfile
  Gemfile.lock
  Gemfile_custom
  config/initializers/rollbar.rb
  config/newrelic.yml
  config/secrets.yml.example
Labels: Release notes, Maintenance

#4750 Fix comment notifications on legislation proposals
  app/helpers/mailer_helper.rb
  spec/mailers/mailer_spec.rb
Labels: Bug, Legislation

#4752 Remove broken technical assistance text in footer
  app/views/layouts/_footer.html.erb
  config/locales/en/general.yml
  config/locales/es/general.yml
Labels: Bug, UX

#4733 Make dev seeds independent on available locales
  config/i18n-tasks.yml
  config/locales/en/seeds.yml
  config/locales/es/seeds.yml
  db/dev_seeds.rb
  db/dev_seeds/admin_notifications.rb
  db/dev_seeds/budgets.rb
  db/dev_seeds/legislation_processes.rb
  db/dev_seeds/widgets.rb
  lib/tasks/db.rake
Labels: Translations, Customization

#4734 Make management and admin headers consistent
  app/helpers/admin_helper.rb
  app/views/layouts/_admin_header.html.erb
  app/views/layouts/management.html.erb
  spec/system/management_spec.rb
Labels: UX, Coadministration

#4643 Use telephone fields in phone number form controls
  app/views/account/show.html.erb
  app/views/organizations/registrations/new.html.erb
  app/views/verification/sms/new.html.erb
Labels: UX

#2125 Redefine postal code verification methods to use setting config parameter
  app/models/custom/verification/residence.rb
  app/models/setting.rb
  app/models/verification/residence.rb
  config/locales/en/settings.yml
  config/locales/en/verification.yml
  config/locales/es/settings.yml
  config/locales/es/verification.yml
  spec/models/custom/verification/residence_spec.rb
  spec/models/verification/residence_spec.rb
  spec/system/verification/residence_spec.rb
Labels: Verification, Release notes, Customization

#4754 Remove legacy code from Madrid's fork
  app/controllers/welcome_controller.rb
  app/views/welcome/verification.html.erb
  config/locales/en/general.yml
  config/locales/es/general.yml
  public/docs/directrices_ejercicio_propuesta.pdf
  public/docs/formulario_propuestas_ciudadanas.pdf
Labels: Maintenance

#2859 Add geozones as user segments
  app/controllers/admin/emails_download_controller.rb
  app/helpers/user_segments_helper.rb
  app/models/admin_notification.rb
  app/models/newsletter.rb
  config/i18n-tasks.yml
  db/dev_seeds/newsletters.rb
  lib/user_segments.rb
  spec/factories/emails.rb
  spec/factories/notifications.rb
  spec/lib/user_segments_spec.rb
  spec/system/admin/admin_notifications_spec.rb
  spec/system/admin/emails/newsletters_spec.rb
Labels: Newsletters

#4543 Make confirm alerts show the triggering action
  app/components/moderation/shared/index_component.html.erb
  app/views/admin/poll/questions/answers/images/index.html.erb
  app/views/budgets/investments/_actions.html.erb
  app/views/comments/_actions.html.erb
  app/views/debates/_actions.html.erb
  app/views/legislation/proposals/_actions.html.erb
  app/views/proposal_notifications/_actions.html.erb
  app/views/proposals/_actions.html.erb
  config/locales/en/admin.yml
  config/locales/en/moderation.yml
  config/locales/es/admin.yml
  config/locales/es/moderation.yml
  spec/system/admin/activity_spec.rb
  spec/system/admin/admin_notifications_spec.rb
  spec/system/admin/administrators_spec.rb
  spec/system/admin/banners_spec.rb
  spec/system/admin/budget_groups_spec.rb
  spec/system/admin/budget_headings_spec.rb
  spec/system/admin/dashboard/actions_spec.rb
  spec/system/admin/emails/newsletters_spec.rb
  spec/system/admin/geozones_spec.rb
  spec/system/admin/hidden_comments_spec.rb
  spec/system/admin/hidden_debates_spec.rb
  spec/system/admin/hidden_proposals_spec.rb
  spec/system/admin/hidden_users_spec.rb
  spec/system/admin/local_census_records_spec.rb
  spec/system/admin/managers_spec.rb
  spec/system/admin/milestone_statuses_spec.rb
  spec/system/admin/moderators_spec.rb
  spec/system/admin/poll/officers_spec.rb
  spec/system/admin/poll/questions/answers/documents/documents_spec.rb
  spec/system/admin/poll/questions/answers/images/images_spec.rb
  spec/system/admin/poll/questions_spec.rb
  spec/system/admin/poll/shifts_spec.rb
  spec/system/admin/proposal_notifications_spec.rb
  spec/system/admin/sdg/managers_spec.rb
  spec/system/admin/site_customization/content_blocks_spec.rb
  spec/system/admin/site_customization/documents_spec.rb
  spec/system/admin/tags_spec.rb
  spec/system/admin/valuator_groups_spec.rb
  spec/system/admin/valuators_spec.rb
  spec/system/admin/widgets/cards_spec.rb
  spec/system/debates_spec.rb
  spec/system/moderation/budget_investments_spec.rb
  spec/system/moderation/comments_spec.rb
  spec/system/moderation/debates_spec.rb
  spec/system/moderation/legislation_proposals_spec.rb
  spec/system/moderation/proposal_notifications_spec.rb
  spec/system/moderation/proposals_spec.rb
  spec/system/moderation/users_spec.rb
  spec/system/sdg_management/homepage_spec.rb
  spec/system/sdg_management/local_targets_spec.rb
Labels: UX

#4757 Remove URL methods in models
  app/components/relationable/related_list_component.html.erb
  app/models/budget/investment.rb
  app/models/debate.rb
  app/models/proposal.rb
  spec/shared/system/relationable.rb
Labels: Refactoring

#4214 Allow hiding users without hiding their content
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/layout.scss
  app/assets/stylesheets/moderation/users/index.scss
  app/assets/stylesheets/moderation_actions.scss
  app/components/admin/action_component.rb
  app/components/moderation/users/index_component.html.erb
  app/components/moderation/users/index_component.rb
  app/components/shared/moderation_actions_component.html.erb
  app/components/shared/moderation_actions_component.rb
  app/controllers/admin/hidden_users_controller.rb
  app/controllers/moderation/users_controller.rb
  app/models/ability.rb
  app/models/comment.rb
  app/models/user.rb
  app/views/budgets/investments/_actions.html.erb
  app/views/comments/_actions.html.erb
  app/views/comments/_comment.html.erb
  app/views/debates/_actions.html.erb
  app/views/legislation/proposals/_actions.html.erb
  app/views/moderation/users/index.html.erb
  app/views/proposal_notifications/_actions.html.erb
  app/views/proposals/_actions.html.erb
  app/views/proposals/_notifications.html.erb
  config/locales/en/admin.yml
  config/locales/en/moderation.yml
  config/locales/es/admin.yml
  config/locales/es/moderation.yml
  config/routes/moderation.rb
  spec/components/moderation/users/index_component_spec.rb
  spec/components/shared/moderation_actions_component_spec.rb
  spec/controllers/moderation/users_controller_spec.rb
  spec/factories/legislations.rb
  spec/models/abilities/moderator_spec.rb
  spec/models/user_spec.rb
  spec/system/admin/activity_spec.rb
  spec/system/admin/hidden_comments_spec.rb
  spec/system/admin/hidden_users_spec.rb
  spec/system/comments/budget_investments_valuation_spec.rb
  spec/system/comments/debates_spec.rb
  spec/system/moderation/budget_investments_spec.rb
  spec/system/moderation/comments_spec.rb
  spec/system/moderation/debates_spec.rb
  spec/system/moderation/legislation_proposals_spec.rb
  spec/system/moderation/proposal_notifications_spec.rb
  spec/system/moderation/proposals_spec.rb
  spec/system/moderation/users_spec.rb
Labels: Coadministration, Accessibility

#4753 Fix invalid HTML in application layout
  app/helpers/tracks_helper.rb
  app/views/layouts/_common_head.html.erb
  app/views/layouts/_tracking_data.html.erb
  app/views/layouts/application.html.erb
  app/views/layouts/dashboard.html.erb
  app/views/verification/letter/edit.html.erb
  app/views/verification/letter/new.html.erb
  app/views/verification/letter/show.html.erb
  app/views/verification/residence/new.html.erb
  app/views/verification/sms/edit.html.erb
  app/views/verification/sms/new.html.erb
  spec/system/tracks_spec.rb
Labels: Maintenance

#4762 Remove redundant permissions to edit/create records
  app/models/abilities/administrator.rb
  app/models/abilities/common.rb
  spec/models/abilities/common_spec.rb
Labels: Maintenance
