Repository consuldemocracy/consuldemocracy, pull requests merged in 2021-06, with the labels that each got.

#4518 Fix exception using locales with no help images
  app/assets/images/help/budgets.png
  app/assets/images/help/proposals.png
  app/components/pages/help/section_component.html.erb
  app/components/pages/help/section_component.rb
  app/components/sdg/goals/icon_component.rb
  app/views/pages/help/_budgets.html.erb
  app/views/pages/help/_debates.html.erb
  app/views/pages/help/_polls.html.erb
  app/views/pages/help/_processes.html.erb
  app/views/pages/help/_proposals.html.erb
  lib/asset_finder.rb
  spec/components/pages/help/section_component_spec.rb
  spec/system/help_page_spec.rb
Labels: Bug

#4535 Bump parser from 2.7.2.0 to 3.0.1.1
  Gemfile.lock
Labels: dependencies

#4515 Fix order loading custom styles
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/custom.scss
  app/assets/stylesheets/custom/.gitkeep
  app/assets/stylesheets/layout.scss
Labels: Bug, Maintenance

#4528 Fix crash destroying budgets with admins/valuators
  app/models/budget.rb
  spec/models/budget_spec.rb
  spec/system/admin/budgets_spec.rb
Labels: Admin, Bug

#4522 Fix crash with budgets with disabled current phase
  app/components/admin/budgets/duration_component.rb
  app/components/admin/budgets/index_component.rb
  app/models/budget.rb
  spec/components/admin/budgets/duration_component_spec.rb
  spec/components/admin/budgets/index_component_spec.rb
Labels: Admin, Bug

#4537 Update translations from Crowdin
  config/locales/de-DE/admin.yml
  config/locales/de-DE/budgets.yml
  config/locales/de-DE/sdg.yml
  config/locales/sv-SE/activemodel.yml
  config/locales/sv-SE/activerecord.yml
  config/locales/sv-SE/admin.yml
  config/locales/sv-SE/budgets.yml
  config/locales/sv-SE/community.yml
  config/locales/sv-SE/devise_views.yml
  config/locales/sv-SE/general.yml
  config/locales/sv-SE/legislation.yml
  config/locales/sv-SE/mailers.yml
  config/locales/sv-SE/pages.yml
  config/locales/sv-SE/sdg.yml
  config/locales/sv-SE/sdg_management.yml
  config/locales/sv-SE/settings.yml
  config/locales/sv-SE/valuation.yml
  config/locales/sv-SE/verification.yml
  config/locales/tr-TR/activemodel.yml
  config/locales/tr-TR/activerecord.yml
  config/locales/tr-TR/admin.yml
  config/locales/tr-TR/budgets.yml
  config/locales/tr-TR/devise_views.yml
  config/locales/tr-TR/documents.yml
  config/locales/tr-TR/general.yml
  config/locales/tr-TR/legislation.yml
  config/locales/tr-TR/mailers.yml
  config/locales/tr-TR/management.yml
  config/locales/tr-TR/sdg.yml
  config/locales/tr-TR/sdg_management.yml
  config/locales/tr-TR/settings.yml
  config/locales/tr-TR/stats.yml
  config/locales/tr-TR/valuation.yml
  config/locales/tr-TR/verification.yml
Labels: Translations

#4503 Increase menu button touch area on small screens
  app/assets/stylesheets/admin.scss
  app/assets/stylesheets/layout.scss
  app/views/layouts/_admin_header.html.erb
  app/views/layouts/_header.html.erb
  spec/spec_helper.rb
  spec/system/admin_spec.rb
  spec/system/debates_spec.rb
  spec/system/home_spec.rb
  spec/system/proposals_spec.rb
Labels: Accessibility, UX

#4509 Remove skip map checkbox
  app/assets/javascripts/map.js
  app/controllers/budgets/investments_controller.rb
  app/controllers/management/budgets/investments_controller.rb
  app/controllers/management/proposals_controller.rb
  app/controllers/proposals_controller.rb
  app/models/concerns/mappable.rb
  app/views/map_locations/_form_fields.html.erb
  config/locales/en/activerecord.yml
  config/locales/en/budgets.yml
  config/locales/en/general.yml
  config/locales/es/activerecord.yml
  config/locales/es/budgets.yml
  config/locales/es/general.yml
  db/dev_seeds/budgets.rb
  db/dev_seeds/proposals.rb
  lib/tasks/proposal_actions.rake
  spec/factories/budgets.rb
  spec/factories/proposals.rb
  spec/shared/models/map_validations.rb
  spec/shared/system/mappable.rb
Labels: Budgets

#4501 Improve budget header
  app/assets/stylesheets/admin.scss
  app/assets/stylesheets/participation.scss
  app/components/admin/budgets/form_component.html.erb
  app/components/budgets/budget_component.html.erb
  app/controllers/admin/budgets_controller.rb
  app/models/budget.rb
  config/locales/en/activerecord.yml
  config/locales/en/admin.yml
  config/locales/es/activerecord.yml
  config/locales/es/admin.yml
  db/migrate/20200213163214_add_main_link_to_budgets.rb
  db/schema.rb
  spec/components/budgets/budget_component_spec.rb
  spec/components/budgets/subheader_component_spec.rb
  spec/models/budget_spec.rb
  spec/models/concerns/globalizable.rb
  spec/system/admin/budgets_spec.rb
  spec/system/admin/translatable_spec.rb
  spec/system/budgets/budgets_spec.rb
Labels: Budgets

#4502 Allow attaching an image to budgets
  app/assets/stylesheets/admin/budgets/form.scss
  app/assets/stylesheets/participation.scss
  app/components/admin/budgets/form_component.html.erb
  app/components/budgets/budget_component.html.erb
  app/controllers/admin/budgets_controller.rb
  app/controllers/admin/budgets_wizard/budgets_controller.rb
  app/models/budget.rb
  config/locales/en/admin.yml
  config/locales/es/admin.yml
  spec/shared/system/nested_imageable.rb
  spec/system/admin/budgets_spec.rb
Labels: Budgets

#4510 Improve budget phases
  app/assets/stylesheets/admin/budget_phases/form.scss
  app/assets/stylesheets/budgets/phases.scss
  app/components/admin/budget_phases/form_component.html.erb
  app/components/budgets/phases_component.html.erb
  app/controllers/concerns/admin/budget_phases_actions.rb
  app/models/budget/phase.rb
  config/locales/en/activerecord.yml
  config/locales/en/admin.yml
  config/locales/es/activerecord.yml
  config/locales/es/admin.yml
  db/migrate/20200309112812_add_main_link_to_budget_phases.rb
  db/schema.rb
  spec/components/budgets/phases_component_spec.rb
  spec/models/budget/phase_spec.rb
  spec/models/concerns/globalizable.rb
  spec/system/admin/budget_phases_spec.rb
  spec/system/admin/translatable_spec.rb
Labels: Budgets

#4533 Simplify creating single heading budgets
  app/assets/images/budgets/budget_multiple_heading_icon.png
  app/assets/images/budgets/budget_single_heading_icon.png
  app/assets/stylesheets/admin.scss
  app/assets/stylesheets/admin/budgets/heading_mode.scss
  app/components/admin/budget_phases/form_component.html.erb
  app/components/admin/budget_phases/phases_component.html.erb
  app/components/admin/budget_phases/phases_component.rb
  app/components/admin/budgets/duration_component.rb
  app/components/admin/budgets/form_component.html.erb
  app/components/admin/budgets/heading_mode_component.html.erb
  app/components/admin/budgets/heading_mode_component.rb
  app/components/admin/budgets/help_component.rb
  app/components/admin/budgets/index_component.html.erb
  app/components/admin/budgets/index_component.rb
  app/components/admin/budgets_wizard/base_component.rb
  app/components/admin/budgets_wizard/budgets/new_component.html.erb
  app/components/admin/budgets_wizard/budgets/new_component.rb
  app/components/admin/budgets_wizard/creation_step_component.html.erb
  app/components/admin/budgets_wizard/creation_step_component.rb
  app/components/admin/budgets_wizard/groups/creation_step_component.rb
  app/components/admin/budgets_wizard/groups/index_component.html.erb
  app/components/admin/budgets_wizard/groups/index_component.rb
  app/components/admin/budgets_wizard/headings/creation_step_component.rb
  app/components/admin/budgets_wizard/headings/index_component.html.erb
  app/components/admin/budgets_wizard/headings/index_component.rb
  app/components/admin/budgets_wizard/model_field_component.html.erb
  app/components/admin/budgets_wizard/model_field_component.rb
  app/components/admin/budgets_wizard/phases/index_component.html.erb
  app/components/admin/budgets_wizard/phases/index_component.rb
  app/controllers/admin/budgets_wizard/base_controller.rb
  app/controllers/admin/budgets_wizard/budgets_controller.rb
  app/controllers/admin/budgets_wizard/groups_controller.rb
  app/controllers/admin/budgets_wizard/headings_controller.rb
  app/controllers/admin/budgets_wizard/phases_controller.rb
  app/models/budget.rb
  app/views/admin/budget_groups/_form.html.erb
  app/views/admin/budget_groups/index.html.erb
  app/views/admin/budget_headings/_form.html.erb
  app/views/admin/budget_headings/index.html.erb
  config/i18n-tasks.yml
  config/locales/en/activerecord.yml
  config/locales/en/admin.yml
  config/locales/en/rails.yml
  config/locales/es/activerecord.yml
  config/locales/es/admin.yml
  config/locales/es/rails.yml
  spec/components/admin/budgets/duration_component_spec.rb
  spec/components/admin/budgets/index_component_spec.rb
  spec/models/budget_spec.rb
  spec/system/admin/budget_investments_spec.rb
  spec/system/admin/budgets_spec.rb
  spec/system/admin/budgets_wizard/budgets_spec.rb
  spec/system/admin/budgets_wizard/groups_spec.rb
  spec/system/admin/budgets_wizard/headings_spec.rb
  spec/system/admin/budgets_wizard/phases_spec.rb
  spec/system/admin/budgets_wizard/wizard_spec.rb
Labels: Budgets

#4545 Adjust budget phases link design
  app/assets/stylesheets/budgets/phases.scss
Labels: Budgets

#4546 Add missing attribute to budget strong params
  app/controllers/admin/budgets_wizard/budgets_controller.rb
  spec/system/admin/budgets_wizard/budgets_spec.rb
Labels: Budgets

#4544 Simplify investment form in single heading budgets
  app/assets/stylesheets/budgets/investments/new.scss
  app/assets/stylesheets/mixins/colors.scss
  app/assets/stylesheets/mixins/layouts.scss
  app/controllers/budgets/investments_controller.rb
  app/controllers/management/budgets/investments_controller.rb
  app/models/budget.rb
  app/models/budget/group.rb
  app/models/budget/heading.rb
  app/views/budgets/investments/_form.html.erb
  app/views/budgets/investments/new.html.erb
  config/locales/en/budgets.yml
  config/locales/es/budgets.yml
  spec/models/budget/heading_spec.rb
  spec/shared/system/mappable.rb
  spec/shared/system/nested_documentable.rb
  spec/shared/system/nested_imageable.rb
  spec/system/admin/budget_groups_spec.rb
  spec/system/admin/budget_investments_spec.rb
  spec/system/budgets/groups_spec.rb
  spec/system/budgets/investments_spec.rb
  spec/system/emails_spec.rb
  spec/system/management/budget_investments_spec.rb
  spec/system/tags/budget_investments_spec.rb
  spec/system/translatable_spec.rb
Labels: Budgets

#4507 Preview list of investments
  app/assets/images/budget_investment_no_image.jpg
  app/assets/stylesheets/budgets/investments-list.scss
  app/assets/stylesheets/budgets/single_heading.scss
  app/components/budgets/budget_component.html.erb
  app/components/budgets/investment_component.html.erb
  app/components/budgets/investment_component.rb
  app/components/budgets/investments_list_component.html.erb
  app/components/budgets/investments_list_component.rb
  app/components/budgets/single_heading_component.html.erb
  app/components/budgets/single_heading_component.rb
  config/locales/en/budgets.yml
  config/locales/es/budgets.yml
  spec/components/budgets/investment_component_spec.rb
  spec/components/budgets/investments_list_component_spec.rb
  spec/system/budgets/budgets_spec.rb
  spec/system/budgets/investments_spec.rb
Labels: Budgets

#4548 Fix duplicate support_title I18n key
  app/components/budgets/investment_component.html.erb
  app/components/budgets/investments_list_component.html.erb
  config/locales/en/budgets.yml
  config/locales/es/budgets.yml
  spec/system/budgets/votes_spec.rb
Labels: Budgets, Bug

#4553 Fix typo in "currently showing" translation
  config/locales/es/admin.yml
Labels: Budgets, Bug

#4547 Fix accessibility issues in budgets index
  app/assets/stylesheets/budgets/investments-list.scss
  app/components/budgets/phases_component.html.erb
Labels: Accessibility, Budgets, Bug

#4550 Fix investment support in management section
  app/views/budgets/investments/_investment_show.html.erb
  spec/system/management/budget_investments_spec.rb
Labels: Budgets, Bug, Manager

#4549 Improve accessibility in support investment button
  app/assets/stylesheets/participation.scss
  app/components/budgets/investments/votes_component.html.erb
  app/components/budgets/investments/votes_component.rb
  app/helpers/accessibility_helper.rb
  app/helpers/budgets_helper.rb
  app/views/budgets/investments/_votes.html.erb
  config/locales/en/budgets.yml
  config/locales/es/budgets.yml
  spec/components/budgets/investments/votes_component_spec.rb
  spec/system/budgets/investments_spec.rb
  spec/system/budgets/votes_spec.rb
  spec/system/management/budget_investments_spec.rb
Labels: Accessibility, Budgets, Refactoring

#4508 Add info section to budgets in the selecting phase
  app/assets/images/budgets/budgets_support.png
  app/assets/stylesheets/budgets/supports_info.scss
  app/components/budgets/budget_component.html.erb
  app/components/budgets/investments_list_component.html.erb
  app/components/budgets/supports_info_component.html.erb
  app/components/budgets/supports_info_component.rb
  config/locales/en/budgets.yml
  config/locales/es/budgets.yml
  spec/components/budgets/supports_info_component_spec.rb
  spec/system/budgets/budgets_spec.rb
Labels: Budgets

#4504 Allow users to remove their supports on budget investments
  app/components/budgets/investments/votes_component.html.erb
  app/components/budgets/investments/votes_component.rb
  app/components/budgets/supports_info_component.html.erb
  app/controllers/budgets/investments/votes_controller.rb
  app/controllers/budgets/investments_controller.rb
  app/controllers/management/budgets/investments/votes_controller.rb
  app/controllers/management/budgets/investments_controller.rb
  app/helpers/budgets_helper.rb
  app/models/abilities/common.rb
  app/models/budget/investment.rb
  app/models/user.rb
  app/views/budgets/investments/_investment.html.erb
  app/views/budgets/investments/_investment_show.html.erb
  app/views/budgets/investments/_votes.html.erb
  app/views/budgets/investments/index.html.erb
  app/views/budgets/investments/show.html.erb
  app/views/budgets/investments/vote.js.erb
  app/views/budgets/investments/votes/show.js.erb
  app/views/management/budgets/investments/index.html.erb
  app/views/management/budgets/investments/print.html.erb
  app/views/management/budgets/investments/show.html.erb
  app/views/management/budgets/investments/vote.js.erb
  app/views/management/budgets/investments/votes/show.js.erb
  config/locales/en/budgets.yml
  config/locales/en/responders.yml
  config/locales/es/budgets.yml
  config/locales/es/responders.yml
  config/routes/budget.rb
  config/routes/management.rb
  spec/components/budgets/investments/votes_component_spec.rb
  spec/models/abilities/common_spec.rb
  spec/system/budgets/budgets_spec.rb
  spec/system/budgets/investments_spec.rb
  spec/system/budgets/votes_spec.rb
  spec/system/management/budget_investments_spec.rb
Labels: Budgets

#4539 Fix custom system emails preview
  app/assets/stylesheets/admin.scss
  app/views/admin/newsletters/show.html.erb
  app/views/admin/system_emails/view.html.erb
Labels: Admin, Bug

#4554 Fix flaky hidden budget investments spec
  spec/system/admin/hidden_budget_investments_spec.rb
Labels: Flaky spec

#4558 Respond with 403 when features are disabled
  config/application.rb
  public/403.html
  spec/system/admin/feature_flags_spec.rb
Labels: Bug, UX

#4556 Fix margin in sign in / sign up forms divider
  app/assets/stylesheets/layout.scss
Labels: Bug, UX

#4526 Use relative units as base font size
  app/assets/stylesheets/_consul_settings.scss
  app/assets/stylesheets/admin.scss
Labels: Accessibility

#4551 Increase font size on extra large screens
  app/assets/stylesheets/layout.scss
Labels: UX

#4559 Disable JavaScript debugging in development
  config/environments/development.rb
Labels: Maintenance

#4555 Fix flaky poll recount spec
  spec/models/poll/partial_result_spec.rb
  spec/models/poll/recount_spec.rb
  spec/system/officing/voters_spec.rb
Labels: Flaky spec

#4560 Fix SVG icons on old browsers
  app/assets/stylesheets/mixins/icons.scss
Labels: Bug, UX

#4557 Remove redundant placeholders in forms
  app/views/account/show.html.erb
  app/views/admin/legislation/draft_versions/_form.html.erb
  app/views/admin/legislation/processes/_form.html.erb
  app/views/admin/legislation/questions/_form.html.erb
  app/views/debates/_form.html.erb
  app/views/devise/confirmations/new.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/links/_link_fields.html.erb
  app/views/management/email_verifications/new.html.erb
  app/views/management/user_invites/new.html.erb
  app/views/management/users/new.html.erb
  app/views/officing/residence/new.html.erb
  app/views/organizations/registrations/new.html.erb
  app/views/users/registrations/delete_form.html.erb
  app/views/users/registrations/edit.html.erb
  app/views/users/registrations/finish_signup.html.erb
  app/views/users/registrations/new.html.erb
  app/views/verification/sms/new.html.erb
  config/locales/en/activerecord.yml
  config/locales/en/admin.yml
  config/locales/en/devise_views.yml
  config/locales/en/general.yml
  config/locales/en/management.yml
  config/locales/en/officing.yml
  config/locales/en/verification.yml
  config/locales/es/activerecord.yml
  config/locales/es/admin.yml
  config/locales/es/devise_views.yml
  config/locales/es/general.yml
  config/locales/es/management.yml
  config/locales/es/officing.yml
  config/locales/es/verification.yml
  spec/system/admin/site_customization/information_texts_spec.rb
Labels: Accessibility, UX

#4563 Improve accessibility in form to add related content
  app/assets/stylesheets/layout.scss
  app/views/relationable/_form.html.erb
  app/views/relationable/_related_content.html.erb
  app/views/relationable/_related_list.html.erb
  app/views/relationable/_score.html.erb
  spec/shared/system/relationable.rb
Labels: Accessibility, Bug

#4564 Fix related content with custom URLs
  app/controllers/related_contents_controller.rb
  app/models/related_content.rb
  app/models/user.rb
  spec/models/related_content_spec.rb
  spec/shared/system/relationable.rb
Labels: Bug

#4505 Avoid rendering empty lists in top links and footer
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/icons.scss
  app/assets/stylesheets/layout.scss
  app/assets/stylesheets/layout/social.scss
  app/components/layout/social_component.html.erb
  app/components/layout/social_component.rb
  app/components/layout/top_links_component.html.erb
  app/components/layout/top_links_component.rb
  app/helpers/application_helper.rb
  app/views/layouts/_footer.html.erb
  app/views/shared/_subnavigation.html.erb
  app/views/shared/_top_links.html.erb
  spec/components/layout/social_component_spec.rb
  spec/components/layout/top_links_component_spec.rb
Labels: Accessibility

#4499 Improve the management of related content
  app/controllers/related_contents_controller.rb
  app/models/related_content.rb
  config/locales/en/general.yml
  config/locales/es/general.yml
  spec/shared/system/relationable.rb
Labels: Bug

#4532 Avoid adding compiled assets to version control
  .gitignore
Labels: Maintenance

#4566 Use links instead of order selectors everywhere
  app/assets/stylesheets/admin.scss
  app/assets/stylesheets/community.scss
  app/assets/stylesheets/layout.scss
  app/assets/stylesheets/participation.scss
  app/assets/stylesheets/print.css
  app/components/moderation/shared/index_component.html.erb
  app/components/moderation/shared/index_component.rb
  app/components/shared/comments_component.html.erb
  app/components/shared/comments_component.rb
  app/components/shared/order_links_component.html.erb
  app/components/shared/order_links_component.rb
  app/controllers/concerns/has_orders.rb
  app/views/admin/legislation/proposals/_proposals.html.erb
  app/views/comments/_comment_tree.html.erb
  app/views/debates/_comments.html.erb
  app/views/legislation/proposals/_comments.html.erb
  app/views/management/proposals/print.html.erb
  app/views/moderation/budgets/investments/index.html.erb
  app/views/moderation/comments/index.html.erb
  app/views/moderation/debates/index.html.erb
  app/views/moderation/proposal_notifications/index.html.erb
  app/views/moderation/proposals/index.html.erb
  app/views/polls/_comments.html.erb
  app/views/proposals/_comments.html.erb
  app/views/shared/_order_links.html.erb
  app/views/shared/_order_selector.html.erb
  app/views/shared/_wide_order_selector.html.erb
  app/views/topics/_comments.html.erb
  app/views/topics/_topics.html.erb
  config/i18n-tasks.yml
  config/locales/en/admin.yml
  config/locales/en/general.yml
  config/locales/en/moderation.yml
  config/locales/es/admin.yml
  config/locales/es/general.yml
  config/locales/es/moderation.yml
  spec/system/admin/legislation/proposals_spec.rb
  spec/system/comments/budget_investments_spec.rb
  spec/system/comments/budget_investments_valuation_spec.rb
  spec/system/comments/debates_spec.rb
  spec/system/comments/legislation_annotations_spec.rb
  spec/system/comments/legislation_questions_spec.rb
  spec/system/comments/polls_spec.rb
  spec/system/comments/proposals_spec.rb
  spec/system/comments/topics_spec.rb
  spec/system/communities_spec.rb
  spec/system/management/proposals_spec.rb
  spec/system/moderation/budget_investments_spec.rb
  spec/system/moderation/comments_spec.rb
  spec/system/moderation/debates_spec.rb
  spec/system/moderation/proposal_notifications_spec.rb
  spec/system/moderation/proposals_spec.rb
Labels: Accessibility, UX

#4567 Fix advanced search button position
  app/assets/javascripts/advanced_search.js
  app/assets/stylesheets/advanced_search.scss
  app/components/shared/advanced_search_component.html.erb
  spec/components/shared/advanced_search_component_spec.rb
  spec/system/advanced_search_spec.rb
Labels: Accessibility, Bug, UX

#4565 Improve home cards
  app/models/widget/card.rb
  app/views/shared/_header.html.erb
  db/dev_seeds/sdg.rb
  spec/models/widget/card_spec.rb
  spec/system/admin/widgets/cards_spec.rb
  spec/system/home_spec.rb
  spec/system/sdg_management/homepage_spec.rb
Labels: Bug

#4506 Make it easier to customize Sass variables
  app/assets/stylesheets/_consul_custom_overrides.scss
  app/assets/stylesheets/_consul_settings.scss
  app/assets/stylesheets/_custom_settings.scss
  app/assets/stylesheets/_settings.scss
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/foundation_and_overrides.scss
  app/assets/stylesheets/layout.scss
Labels: Maintenance

#4513 Remove unused CSS to set colors
  app/assets/stylesheets/admin.scss
  app/assets/stylesheets/dashboard.scss
  app/assets/stylesheets/layout.scss
  app/assets/stylesheets/participation.scss
  app/assets/stylesheets/stats.scss
Labels: Maintenance

#4514 Simplify using text color for links
  app/assets/stylesheets/admin.scss
  app/assets/stylesheets/admin/menu.scss
  app/assets/stylesheets/budgets/ballot/investment.scss
  app/assets/stylesheets/budgets/phases.scss
  app/assets/stylesheets/dashboard.scss
  app/assets/stylesheets/datepicker_overrides.scss
  app/assets/stylesheets/layout.scss
  app/assets/stylesheets/legislation.scss
  app/assets/stylesheets/legislation_process.scss
  app/assets/stylesheets/participation.scss
Labels: Refactoring

#4520 Simplify using current color on borders
  app/assets/stylesheets/admin.scss
  app/assets/stylesheets/dashboard.scss
  app/assets/stylesheets/layout.scss
  app/assets/stylesheets/participation.scss
Labels: Refactoring

#4568 Use a submit button in budget executions filters
  app/assets/stylesheets/admin/search.scss
  app/assets/stylesheets/budgets/executions/filters.scss
  app/assets/stylesheets/mixins/buttons.scss
  app/components/budgets/executions/filters_component.html.erb
  app/components/budgets/executions/filters_component.rb
  app/helpers/budget_executions_helper.rb
  app/views/budgets/executions/show.html.erb
  config/locales/en/general.yml
  config/locales/es/general.yml
  spec/components/budgets/executions/filters_component_spec.rb
  spec/system/budgets/executions_spec.rb
Labels: Accessibility, UX

#4571 Make campaign specs more robust
  spec/system/campaigns_spec.rb
Labels: Flaky spec, Specs

#4552 Use icons with text in admin table actions
  app/assets/stylesheets/_consul_settings.scss
  app/assets/stylesheets/admin/budgets/drafting.scss
  app/assets/stylesheets/admin/budgets/help.scss
  app/assets/stylesheets/admin/table_actions.scss
  app/assets/stylesheets/budgets/ballot/investment.scss
  app/assets/stylesheets/budgets/investments-list.scss
  app/assets/stylesheets/budgets/investments/ballot.scss
  app/assets/stylesheets/budgets/phases.scss
  app/assets/stylesheets/layout.scss
  app/assets/stylesheets/mixins/icons.scss
  app/assets/stylesheets/notification_item.scss
  app/assets/stylesheets/participation.scss
  app/components/admin/budget_phases/phases_component.html.erb
  app/components/admin/budgets/table_actions_component.html.erb
  app/components/admin/budgets/table_actions_component.rb
  app/components/admin/hidden_table_actions_component.rb
  app/components/admin/organizations/table_actions_component.rb
  app/components/admin/roles/table_actions_component.rb
  app/components/admin/table_actions_component.rb
  app/components/concerns/table_action_link.rb
  app/views/admin/banners/index.html.erb
  app/views/admin/milestones/_milestones.html.erb
  app/views/admin/officials/index.html.erb
  app/views/admin/officials/search.html.erb
  app/views/admin/poll/booths/_booth.html.erb
  app/views/admin/site_customization/content_blocks/index.html.erb
  app/views/admin/tags/index.html.erb
  config/locales/en/admin.yml
  config/locales/es/admin.yml
  spec/components/admin/budgets/table_actions_component_spec.rb
  spec/shared/system/admin_milestoneable.rb
  spec/system/admin/banners_spec.rb
  spec/system/admin/budget_groups_spec.rb
  spec/system/admin/budget_phases_spec.rb
  spec/system/admin/budgets_spec.rb
  spec/system/admin/budgets_wizard/budgets_spec.rb
  spec/system/admin/budgets_wizard/phases_spec.rb
  spec/system/admin/budgets_wizard/wizard_spec.rb
  spec/system/admin/officials_spec.rb
  spec/system/admin/poll/booths_spec.rb
  spec/system/admin/site_customization/content_blocks_spec.rb
  spec/system/admin/tags_spec.rb
  spec/system/admin/widgets/cards_spec.rb
  spec/system/budget_polls/budgets_spec.rb
Labels: Admin, UX

#4572 Add missing expectation to related content test
  spec/models/related_content_spec.rb
Labels: Specs

#4569 Use a submit button in admin poll question filters
  app/assets/stylesheets/admin/poll/questions/filter.scss
  app/components/admin/poll/questions/filter_component.html.erb
  app/components/admin/poll/questions/filter_component.rb
  app/helpers/polls_helper.rb
  app/views/admin/poll/questions/_filter.html.erb
  app/views/admin/poll/questions/_questions.html.erb
  spec/components/admin/poll/questions/filter_component_spec.rb
Labels: Accessibility

#4530 Reduce duplication in background color definitions
  app/assets/stylesheets/admin.scss
  app/assets/stylesheets/autocomplete_overrides.scss
  app/assets/stylesheets/budgets/phases.scss
  app/assets/stylesheets/dashboard.scss
  app/assets/stylesheets/layout.scss
  app/assets/stylesheets/legislation.scss
  app/assets/stylesheets/legislation_process.scss
  app/assets/stylesheets/participation.scss
Labels: Refactoring
