Repository consuldemocracy/consuldemocracy, pull requests merged in 2021-09, with the labels that each got.

#4669 Fix flaky investments order spec
  spec/system/budgets/investments_spec.rb
Labels: Flaky spec

#4682 Fix flaky legislation draft version spec
  spec/system/admin/legislation/draft_versions_spec.rb
Labels: Flaky spec

#4662 Upgrade Ruby to version 2.7.4
  .gitlab-ci.yml
  .ruby-version
  Dockerfile
  Gemfile.lock
  README.md
  README_ES.md
  config/initializers/paperclip.rb
Labels: Maintenance

#4603 Fix updating a translation to its original value
  app/controllers/admin/site_customization/information_texts_controller.rb
  app/models/i18n_content.rb
  spec/models/i18n_content_spec.rb
Labels: Bug, Translations

#4667 Do not show unpublished proposals on the homepage
  app/models/widget/feed.rb
  spec/models/widget/feed_spec.rb
Labels: Bug, Proposals

#4690 Simplify type and current user in component tests
  spec/components/admin/budgets/duration_component_spec.rb
  spec/components/admin/budgets/form_component_spec.rb
  spec/components/admin/budgets/index_component_spec.rb
  spec/components/admin/budgets/table_actions_component_spec.rb
  spec/components/admin/budgets_wizard/headings/group_switcher_component_spec.rb
  spec/components/admin/hidden_table_actions_component_spec.rb
  spec/components/admin/organizations/table_actions_component_spec.rb
  spec/components/admin/poll/officers/officers_component_spec.rb
  spec/components/admin/poll/questions/filter_component_spec.rb
  spec/components/admin/roles/table_actions_component_spec.rb
  spec/components/admin/stats/sdg/goal_component_spec.rb
  spec/components/admin/table_actions_component_spec.rb
  spec/components/budgets/budget_component_spec.rb
  spec/components/budgets/investment_component_spec.rb
  spec/components/budgets/investments/form_component_spec.rb
  spec/components/budgets/investments/votes_component_spec.rb
  spec/components/budgets/investments_list_component_spec.rb
  spec/components/budgets/phases_component_spec.rb
  spec/components/budgets/subheader_component_spec.rb
  spec/components/budgets/supports_info_component_spec.rb
  spec/components/layout/locale_switcher_component_spec.rb
  spec/components/layout/social_component_spec.rb
  spec/components/layout/top_links_component_spec.rb
  spec/components/machine_learning/comments_summary_component_spec.rb
  spec/components/pages/help/section_component_spec.rb
  spec/components/relationable/related_list_component_spec.rb
  spec/components/sdg/goals/help_page_component_spec.rb
  spec/components/sdg/goals/index_component_spec.rb
  spec/components/sdg/goals/plain_tag_list_component_spec.rb
  spec/components/sdg/goals/show_component_spec.rb
  spec/components/sdg/goals/tag_cloud_component_spec.rb
  spec/components/sdg/goals/tag_list_component_spec.rb
  spec/components/sdg/goals/targets_component_spec.rb
  spec/components/sdg/related_list_selector_component_spec.rb
  spec/components/sdg/tag_list_component_spec.rb
  spec/components/sdg/targets/plain_tag_list_component_spec.rb
  spec/components/sdg/targets/tag_list_component_spec.rb
  spec/components/sdg_management/menu_component_spec.rb
  spec/components/sdg_management/relations/index_component_spec.rb
  spec/components/sdg_management/relations/search_component_spec.rb
  spec/components/sdg_management/subnavigation_component_spec.rb
  spec/components/shared/advanced_search_component_spec.rb
  spec/components/shared/banner_component_spec.rb
  spec/components/shared/filter_selector_component_spec.rb
  spec/components/shared/link_list_component_spec.rb
  spec/components/shared/tag_list_component_spec.rb
  spec/components/widget/feeds/debate_component_spec.rb
  spec/components/widget/feeds/feed_component_spec.rb
  spec/components/widget/feeds/process_component_spec.rb
  spec/components/widget/feeds/proposal_component_spec.rb
  spec/rails_helper.rb
  spec/spec_helper.rb
Labels: Specs

#4595 Reduce duplication in attachments code
  app/components/attachable/fields_component.html.erb
  app/components/attachable/fields_component.rb
  app/components/documents/fields_component.html.erb
  app/components/documents/fields_component.rb
  app/components/documents/nested_component.rb
  app/components/images/fields_component.html.erb
  app/components/images/fields_component.rb
  app/components/images/nested_component.rb
  app/helpers/documentables_helper.rb
  app/helpers/imageables_helper.rb
  app/models/concerns/attachable.rb
  app/models/concerns/documentable.rb
  app/models/document.rb
  app/models/image.rb
  spec/shared/models/document_validations.rb
  spec/shared/models/image_validations.rb
Labels: Refactoring

#4661 Remove devise-async dependency
  Gemfile
  Gemfile.lock
Labels: Maintenance

#4668 Remove official level filter from advanced search
  app/assets/stylesheets/advanced_search.scss
  app/components/shared/advanced_search_component.html.erb
  app/components/shared/advanced_search_component.rb
  app/models/concerns/filterable.rb
  config/locales/en/general.yml
  config/locales/es/general.yml
  spec/system/advanced_search_spec.rb
Labels: UX

#4687 Fix "Add image" button styles in budget phases
  app/assets/stylesheets/admin/budget_phases/form.scss
Labels: Bug, UX

#4679 Add default focus outline to buttons
  app/assets/stylesheets/admin.scss
  app/assets/stylesheets/admin/machine_learning/scripts.scss
  app/assets/stylesheets/admin/machine_learning/setting.scss
  app/assets/stylesheets/advanced_search.scss
  app/assets/stylesheets/layout.scss
  app/assets/stylesheets/layout/locale_switcher.scss
  app/assets/stylesheets/mixins/buttons.scss
  app/assets/stylesheets/participation.scss
  app/assets/stylesheets/sdg/related_list_selector.scss
  app/views/admin/legislation/draft_versions/_form.html.erb
Labels: UX, Accessibility

#4680 Increase login links touch area on small screens
  app/assets/stylesheets/admin.scss
  app/assets/stylesheets/layout.scss
  app/views/layouts/_admin_header.html.erb
  app/views/layouts/management.html.erb
  app/views/shared/_admin_login_items.html.erb
Labels: UX, Accessibility

#4660 Avoid error when combining investments advanced search with filters
  app/controllers/concerns/search.rb
  spec/system/budgets/investments_spec.rb
Labels: Bug

#4698 Expire cache when adding documents and images
  app/models/document.rb
  app/models/image.rb
  app/views/budgets/investments/_investment_show.html.erb
  spec/models/proposal_spec.rb
Labels: Bug

#4701 Fix social share image URL with external storage
  app/helpers/images_helper.rb
Labels: Bug

#4703 Wait for suggestions to finish loading in tests
  app/assets/javascripts/suggest.js
  spec/shared/system/mappable.rb
  spec/shared/system/nested_documentable.rb
  spec/shared/system/nested_imageable.rb
  spec/support/common_actions.rb
  spec/system/budgets/investments_spec.rb
  spec/system/debates_spec.rb
  spec/system/emails_spec.rb
  spec/system/management/budget_investments_spec.rb
  spec/system/management/proposals_spec.rb
  spec/system/proposals_spec.rb
  spec/system/tags/budget_investments_spec.rb
  spec/system/tags/debates_spec.rb
  spec/system/tags/proposals_spec.rb
  spec/system/tags_spec.rb
  spec/system/translatable_spec.rb
Labels: Flaky spec

#4681 Use a switch control to enable/disable features
  app/assets/stylesheets/admin/machine_learning/setting.scss
  app/assets/stylesheets/admin/settings/featured_settings_form.scss
  app/assets/stylesheets/admin/settings/featured_settings_table.scss
  app/assets/stylesheets/mixins/buttons.scss
  app/components/admin/machine_learning/setting_component.html.erb
  app/components/admin/settings/featured_settings_form_component.html.erb
  app/components/admin/settings/featured_settings_form_component.rb
  app/controllers/admin/settings_controller.rb
  app/views/admin/homepage/_feed.html.erb
  app/views/admin/homepage/_setting.html.erb
  app/views/admin/homepage/show.html.erb
  app/views/admin/settings/_content_types_settings_form.html.erb
  app/views/admin/settings/_featured_settings_form.html.erb
  app/views/admin/settings/_featured_settings_table.html.erb
  app/views/admin/settings/_settings_form.html.erb
  app/views/admin/settings/_settings_table.html.erb
  app/views/admin/settings/update.js.erb
  config/i18n-tasks.yml
  config/locales/en/admin.yml
  config/locales/es/admin.yml
  spec/components/admin/settings/featured_settings_form_component_spec.rb
  spec/system/admin/feature_flags_spec.rb
  spec/system/admin/homepage/homepage_spec.rb
  spec/system/admin/settings_spec.rb
Labels: Admin, UX, Accessibility

#4702 Add sanitize to description on moderator activity
  app/views/admin/activity/show.html.erb
  spec/system/admin/activity_spec.rb
Labels: Bug, Admin

#4704 Add missing expectations in investments test
  spec/system/budgets/investments_spec.rb
Labels: Flaky spec

#4598 Store files with both Paperclip and ActiveStorage
  .gitignore
  .rubocop.yml
  app/controllers/admin/site_customization/images_controller.rb
  app/models/ckeditor/asset.rb
  app/models/ckeditor/picture.rb
  app/models/concerns/attachable.rb
  app/models/concerns/has_attachment.rb
  app/models/direct_upload.rb
  app/models/document.rb
  app/models/image.rb
  app/models/site_customization/image.rb
  config/application.rb
  config/deploy.rb
  config/environments/test.rb
  config/initializers/disable_active_storage_uploads.rb
  config/storage.yml
  db/dev_seeds/budgets.rb
  db/dev_seeds/proposals.rb
  db/migrate/20210619201902_create_active_storage_tables.active_storage.rb
  db/schema.rb
  lib/ckeditor/backend/active_storage.rb
  lib/tasks/active_storage.rake
  lib/tasks/consul.rake
  spec/controllers/active_storage/direct_uploads_controller_spec.rb
  spec/controllers/active_storage/disk_controller_spec.rb
  spec/factories/files.rb
  spec/lib/tasks/active_storage_spec.rb
  spec/models/document_spec.rb
  spec/models/image_spec.rb
  spec/models/site_customization/image_spec.rb
Labels: Release notes, Maintenance

#4699 Remove unused attachments code
  app/models/concerns/galleryable.rb
  app/views/dashboard/mailing/index.html.erb
  spec/shared/models/acts_as_imageable.rb
  spec/shared/system/nested_imageable.rb
  spec/system/admin/budget_phases_spec.rb
  spec/system/admin/legislation/processes_spec.rb
  spec/system/admin/poll/questions/answers/images/images_spec.rb
  spec/system/admin/site_customization/documents_spec.rb
  spec/system/admin/widgets/cards_spec.rb
  spec/system/legislation/proposals_spec.rb
Labels: Maintenance

#4676 Improve styles for long admin menu items
  app/assets/stylesheets/admin/menu.scss
  app/assets/stylesheets/layout.scss
  app/assets/stylesheets/mixins/icons.scss
Labels: Admin, UX

#4673 Enable SDG content by default
  app/models/setting.rb
  db/dev_seeds/settings.rb
Labels: SDG
