Repository consuldemocracy/consuldemocracy, pull requests merged in 2021-04, with the labels that each got.

#4460 Upload screenshots of failures with GitHub Actions
  .github/workflows/tests.yml
Labels: Maintenance

#4457 Integrate Coveralls with Github Actions
  .coveralls.yml
  .github/workflows/tests.yml
  spec/rails_helper.rb
Labels: Maintenance

#4453 Fix "Go back" link in stat graphs
  app/views/admin/stats/_graph.html.erb
  app/views/admin/stats/graph.html.erb
  app/views/admin/verifications/index.html.erb
  spec/system/admin/stats_spec.rb
  spec/system/admin/verifications_spec.rb
Labels: Bug

#4443 Avoid exceptions in Management section
  app/controllers/management/base_controller.rb
  config/locales/en/management.yml
  config/locales/es/management.yml
  spec/system/management/account_spec.rb
  spec/system/management/budget_investments_spec.rb
  spec/system/management/proposals_spec.rb
Labels: Bug

#4441 Fix active banners in non-UTC time zones
  app/models/banner.rb
  spec/components/shared/banner_component_spec.rb
  spec/factories/administration.rb
  spec/models/banner_spec.rb
  spec/system/admin/banners_spec.rb
  spec/system/banners_spec.rb
Labels: Bug

#4434 rake db:seed generates default custom pages for all languages
  db/pages/accessibility.rb
  db/pages/conditions.rb
  db/pages/faq.rb
  db/pages/privacy.rb
  db/pages/welcome_level_three_verified.rb
  db/pages/welcome_level_two_verified.rb
  db/pages/welcome_not_verified.rb
  spec/lib/tasks/seed_spec.rb
Labels: Translations

#4471 Fix setting locale to an unavailable one in specs
  spec/lib/tasks/seed_spec.rb
Labels: Specs

#4467 Fix flaky spec "Notifications User not logged in"
  spec/system/notifications_spec.rb
Labels: Flaky spec

#4448 Improve create investments in Management section
  app/controllers/admin/dashboard/actions_controller.rb
  app/controllers/admin/legislation/processes_controller.rb
  app/controllers/admin/milestones_controller.rb
  app/controllers/admin/poll/questions/answers/images_controller.rb
  app/controllers/admin/poll/questions/answers_controller.rb
  app/controllers/budgets/investments_controller.rb
  app/controllers/concerns/document_attributes.rb
  app/controllers/concerns/map_location_attributes.rb
  app/controllers/dashboard/polls_controller.rb
  app/controllers/management/budgets/investments_controller.rb
  app/controllers/management/proposals_controller.rb
  app/controllers/proposals_controller.rb
  spec/shared/system/mappable.rb
  spec/shared/system/nested_documentable.rb
  spec/shared/system/nested_imageable.rb
  spec/support/common_actions/users.rb
  spec/system/management/budget_investments_spec.rb
Labels: Manager

#4456 Clear fields in tests before filling them in
  spec/rails_helper.rb
  spec/system/budgets/ballots_spec.rb
Labels: Flaky spec

#4455 Do not make suggestions for related titles on edit pages
  app/helpers/suggestions_helper.rb
  app/views/budgets/investments/_form.html.erb
  app/views/debates/_form.html.erb
  app/views/proposals/_form.html.erb
  spec/system/budgets/investments_spec.rb
  spec/system/debates_spec.rb
  spec/system/proposals_spec.rb
Labels: Bug

#4461 Fix flaky spec "Edit poll allows removing answers"
  spec/system/dashboard/polls_spec.rb
Labels: Flaky spec

#4465 Restore all related content along when a user is restored
  app/controllers/admin/hidden_users_controller.rb
  app/models/user.rb
  spec/factories/proposals.rb
  spec/models/user_spec.rb
Labels: Moderation

#4464 Add SDG icons for Serbian (Cyrillic)
  vendor/assets/images/sdg/sr/goal_1.png
  vendor/assets/images/sdg/sr/goal_10.png
  vendor/assets/images/sdg/sr/goal_11.png
  vendor/assets/images/sdg/sr/goal_12.png
  vendor/assets/images/sdg/sr/goal_13.png
  vendor/assets/images/sdg/sr/goal_14.png
  vendor/assets/images/sdg/sr/goal_15.png
  vendor/assets/images/sdg/sr/goal_16.png
  vendor/assets/images/sdg/sr/goal_17.png
  vendor/assets/images/sdg/sr/goal_2.png
  vendor/assets/images/sdg/sr/goal_3.png
  vendor/assets/images/sdg/sr/goal_4.png
  vendor/assets/images/sdg/sr/goal_5.png
  vendor/assets/images/sdg/sr/goal_6.png
  vendor/assets/images/sdg/sr/goal_7.png
  vendor/assets/images/sdg/sr/goal_8.png
  vendor/assets/images/sdg/sr/goal_9.png
Labels: SDG

#4463 Expire cache when users follow/unfollow
  app/controllers/follows_controller.rb
  app/models/abilities/common.rb
  app/models/follow.rb
  app/views/budgets/investments/_investment_show.html.erb
  app/views/proposals/show.html.erb
  spec/models/abilities/common_spec.rb
  spec/models/follow_spec.rb
Labels: Bug

#4442 Improve user search by email/name
  app/models/user.rb
  spec/models/user_spec.rb
Labels: Bug

#4226 Allow users to delete their own comments
  app/assets/stylesheets/layout.scss
  app/controllers/comments_controller.rb
  app/models/abilities/common.rb
  app/models/abilities/moderation.rb
  app/views/comments/_actions.html.erb
  app/views/comments/hide.js.erb
  config/locales/en/general.yml
  config/locales/es/general.yml
  config/routes/comment.rb
  spec/models/abilities/common_spec.rb
  spec/models/abilities/moderator_spec.rb
  spec/system/comments/debates_spec.rb
Labels: UX

#4458 Speed up deployment when Ruby is already installed
  config/deploy.rb
Labels: Maintenance

#4473 Add shared-mime-info dependency to README
  README.md
  README_ES.md
Labels: Documentation

#4472 Setup database before starting the browser in tests
  spec/system/admin/administrators_spec.rb
  spec/system/admin/managers_spec.rb
  spec/system/admin/moderators_spec.rb
  spec/system/admin/sdg/managers_spec.rb
  spec/system/admin/site_customization/pages_spec.rb
  spec/system/admin/users_spec.rb
  spec/system/admin/valuators_spec.rb
  spec/system/budgets/ballots_spec.rb
  spec/system/dashboard/dashboard_spec.rb
  spec/system/dashboard/polls_spec.rb
  spec/system/officing/residence_spec.rb
  spec/system/proposals_spec.rb
  spec/system/users_spec.rb
Labels: Specs

#4462 Update Dockerfile dependencies
  .github/workflows/docker.yml
  Dockerfile
Labels: Maintenance

#4475 Reduce test database access after visiting a page
  spec/shared/system/relationable.rb
  spec/support/common_actions.rb
  spec/support/common_actions/comments.rb
  spec/system/account_spec.rb
  spec/system/admin/activity_spec.rb
  spec/system/admin/budget_groups_spec.rb
  spec/system/admin/budget_headings_spec.rb
  spec/system/admin/budget_investments_spec.rb
  spec/system/admin/budgets_spec.rb
  spec/system/admin/emails/newsletters_spec.rb
  spec/system/admin/geozones_spec.rb
  spec/system/admin/hidden_budget_investments_spec.rb
  spec/system/admin/hidden_comments_spec.rb
  spec/system/admin/hidden_debates_spec.rb
  spec/system/admin/hidden_proposals_spec.rb
  spec/system/admin/hidden_users_spec.rb
  spec/system/admin/legislation/processes_spec.rb
  spec/system/admin/legislation/questions_spec.rb
  spec/system/admin/organizations_spec.rb
  spec/system/admin/poll/active_polls_spec.rb
  spec/system/admin/poll/polls_spec.rb
  spec/system/admin/proposal_notifications_spec.rb
  spec/system/admin/proposals_spec.rb
  spec/system/admin/signature_sheets_spec.rb
  spec/system/admin/site_customization/documents_spec.rb
  spec/system/admin/site_customization/information_texts_spec.rb
  spec/system/admin/stats_spec.rb
  spec/system/admin/system_emails_spec.rb
  spec/system/admin/tags_spec.rb
  spec/system/admin/translatable_spec.rb
  spec/system/admin/widgets/cards_spec.rb
  spec/system/budget_polls/ballot_sheets_spec.rb
  spec/system/budget_polls/budgets_spec.rb
  spec/system/budget_polls/voter_spec.rb
  spec/system/budgets/ballots_spec.rb
  spec/system/budgets/budgets_spec.rb
  spec/system/budgets/investments_spec.rb
  spec/system/budgets/results_spec.rb
  spec/system/dashboard/polls_spec.rb
  spec/system/dashboard/poster_spec.rb
  spec/system/debates_spec.rb
  spec/system/emails_spec.rb
  spec/system/legislation/proposals_spec.rb
  spec/system/management/account_spec.rb
  spec/system/management/managed_users_spec.rb
  spec/system/management/proposals_spec.rb
  spec/system/management/users_spec.rb
  spec/system/moderation/budget_investments_spec.rb
  spec/system/moderation/comments_spec.rb
  spec/system/moderation/debates_spec.rb
  spec/system/moderation/proposal_notifications_spec.rb
  spec/system/moderation/proposals_spec.rb
  spec/system/officing/results_spec.rb
  spec/system/organizations_spec.rb
  spec/system/polls/voter_spec.rb
  spec/system/proposal_notifications_spec.rb
  spec/system/proposals_spec.rb
  spec/system/tags/budget_investments_spec.rb
  spec/system/tags/proposals_spec.rb
  spec/system/users_auth_spec.rb
Labels: Flaky spec

#4476 Fix source translations typos
  config/locales/en/budgets.yml
  config/locales/en/settings.yml
  config/locales/es/settings.yml
Labels: Bug

#4484 Fix checkout in Pronto on external pull requests
  .github/workflows/linters.yml
Labels: Maintenance

#4483 Add draft info on unpublished budgets
  app/assets/stylesheets/admin/budgets/index.scss
  app/components/admin/budgets/index_component.html.erb
  app/components/admin/budgets/index_component.rb
  config/locales/en/admin.yml
  config/locales/es/admin.yml
  spec/system/admin/budgets_spec.rb
Labels: Budgets

#4486 Make it easier for admins to enable SDG processes
  app/models/setting.rb
  db/dev_seeds/settings.rb
Labels: SDG

#4478 Use a maintained PostgreSQL version in Docker
  README.md
  README_ES.md
  docker-compose.yml
Labels: Maintenance, Release notes

#4489 Fix checkout in Pronto on Dependabot pull requests
  .github/workflows/linters.yml
Labels: Maintenance

#4497 Fix footer overflow on small screens
  app/assets/stylesheets/layout.scss
Labels: Bug
