Repository consuldemocracy/consuldemocracy, pull requests merged in 2021-03, with the labels that each got.

#4381 Use more generic names for validation rules
  app/models/custom/verification/residence.rb
  app/models/officing/residence.rb
  app/views/officing/residence/_errors.html.erb
  app/views/verification/residence/_errors.html.erb
Labels: Refactoring

#4353 Add SDG help page
  app/assets/stylesheets/mixins.scss
  app/assets/stylesheets/sdg/goals/targets.scss
  app/assets/stylesheets/sdg/help.scss
  app/assets/stylesheets/sdg/related_list_selector.scss
  app/components/sdg/goals/help_page_component.html.erb
  app/components/sdg/goals/help_page_component.rb
  app/components/sdg/goals/targets_component.html.erb
  app/components/sdg/related_list_selector_component.html.erb
  app/controllers/sdg/goals_controller.rb
  app/models/abilities/everyone.rb
  app/views/pages/help/_other.html.erb
  app/views/sdg/goals/help.html.erb
  app/views/shared/_subnavigation.html.erb
  config/locales/en/activerecord.yml
  config/locales/en/pages.yml
  config/locales/en/sdg.yml
  config/locales/es/activerecord.yml
  config/locales/es/pages.yml
  config/locales/es/sdg.yml
  config/routes/sdg.rb
  spec/components/sdg/goals/help_page_component_spec.rb
  spec/components/sdg/goals/targets_component_spec.rb
  spec/system/help_page_spec.rb
  spec/system/sdg/goals_spec.rb
  spec/system/sdg_management/relations_spec.rb
Labels: SDG

#4382 Use Pronto to check code conventions
  .eslintrc
  .eslintrc.json
  .eslintrc.yml
  .github/workflows/linters.yml
  .hound.yml
  .pronto.yml
  CONTRIBUTING.md
  CONTRIBUTING_ES.md
  Gemfile
  Gemfile.lock
  README.md
  README_ES.md
  config/initializers/better_html.rb
Labels: Maintenance

#4386 Fixing styles for the related list component
  app/assets/stylesheets/sdg/related_list_selector.scss
  app/components/sdg/related_list_selector_component.html.erb
Labels: Bug, SDG

#4385 Remove ESLint rules incompatible with Pronto
  .eslintrc.json
  .github/workflows/linters.yml
Labels: Maintenance

#4388 Do not require Pronto when running the application
  Gemfile
  config/initializers/better_html.rb
Labels: Bug

#4374 Change budget phases design
  app/assets/stylesheets/_consul_settings.scss
  app/assets/stylesheets/admin.scss
  app/assets/stylesheets/admin/budget_phases/form.scss
  app/assets/stylesheets/admin/budget_phases/phases.scss
  app/assets/stylesheets/admin/budgets/form.scss
  app/assets/stylesheets/admin/budgets/index.scss
  app/assets/stylesheets/admin/table_actions.scss
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/budgets/phases.scss
  app/assets/stylesheets/budgets/subheader.scss
  app/assets/stylesheets/layout.scss
  app/assets/stylesheets/participation.scss
  app/components/admin/budget_phases/phases_component.html.erb
  app/components/admin/budget_phases/phases_component.rb
  app/components/admin/budgets/duration_component.rb
  app/components/admin/budgets/index_component.html.erb
  app/components/admin/budgets/index_component.rb
  app/components/budgets/phases_component.html.erb
  app/components/budgets/phases_component.rb
  app/components/budgets/subheader_component.html.erb
  app/components/budgets/subheader_component.rb
  app/models/budget.rb
  app/models/budget/phase.rb
  app/views/admin/budget_phases/_form.html.erb
  app/views/admin/budget_phases/edit.html.erb
  app/views/admin/budgets/_form.html.erb
  app/views/admin/budgets/index.html.erb
  app/views/admin/budgets/new.html.erb
  app/views/budgets/_finished.html.erb
  app/views/budgets/_phases.html.erb
  app/views/budgets/ballot/_ballot.html.erb
  app/views/budgets/groups/show.html.erb
  app/views/budgets/index.html.erb
  app/views/budgets/show.html.erb
  app/views/management/budgets/create_investments.html.erb
  app/views/management/budgets/print_investments.html.erb
  app/views/management/budgets/support_investments.html.erb
  app/views/valuation/budgets/index.html.erb
  config/locales/en/activerecord.yml
  config/locales/en/admin.yml
  config/locales/en/budgets.yml
  config/locales/es/activerecord.yml
  config/locales/es/admin.yml
  config/locales/es/budgets.yml
  db/dev_seeds/budgets.rb
  db/migrate/20200309100127_add_name_to_budget_phases.rb
  db/schema.rb
  lib/tasks/budgets.rake
  lib/tasks/consul.rake
  spec/components/admin/budgets/duration_component_spec.rb
  spec/lib/tasks/budgets_spec.rb
  spec/system/admin/budget_phases_spec.rb
  spec/system/admin/budgets_spec.rb
  spec/system/admin/translatable_spec.rb
  spec/system/budgets/budgets_spec.rb
Labels: Budgets

#4396 Add filters on budget investments index page
  app/assets/javascripts/application.js
  app/assets/javascripts/filter_selector.js
  app/assets/javascripts/forms.js
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/filter_selector.scss
  app/components/shared/filter_selector_component.html.erb
  app/components/shared/filter_selector_component.rb
  app/controllers/application_controller.rb
  app/controllers/budgets/groups_controller.rb
  app/controllers/budgets/investments_controller.rb
  app/controllers/budgets_controller.rb
  app/controllers/concerns/has_filters.rb
  app/controllers/concerns/investment_filters.rb
  app/helpers/budgets_helper.rb
  app/views/budgets/groups/show.html.erb
  app/views/budgets/index.html.erb
  app/views/budgets/investments/_feasibility_link.html.erb
  app/views/budgets/investments/index.html.erb
  config/i18n-tasks.yml
  config/locales/en/budgets.yml
  config/locales/es/budgets.yml
  spec/components/shared/filter_selector_component_spec.rb
  spec/system/budgets/budgets_spec.rb
  spec/system/budgets/groups_spec.rb
  spec/system/budgets/investments_spec.rb
Labels: Budgets, UX

#4397 Unify budget landing pages
  app/assets/stylesheets/budgets/groups_and_headings.scss
  app/assets/stylesheets/participation.scss
  app/components/budgets/budget_component.html.erb
  app/components/budgets/budget_component.rb
  app/components/budgets/footer_component.html.erb
  app/components/budgets/footer_component.rb
  app/components/budgets/groups_and_headings_component.html.erb
  app/components/budgets/groups_and_headings_component.rb
  app/components/budgets/investments/info_component.html.erb
  app/components/budgets/investments/info_component.rb
  app/controllers/budgets/ballot/lines_controller.rb
  app/controllers/budgets/ballots_controller.rb
  app/controllers/budgets_controller.rb
  app/helpers/budgets_helper.rb
  app/views/budgets/ballot/_ballot.html.erb
  app/views/budgets/groups/show.html.erb
  app/views/budgets/index.html.erb
  app/views/budgets/investments/_header.html.erb
  app/views/budgets/investments/_investment.html.erb
  app/views/budgets/results/show.html.erb
  app/views/budgets/show.html.erb
  config/locales/en/budgets.yml
  config/locales/es/budgets.yml
  spec/system/budgets/ballots_spec.rb
  spec/system/budgets/budgets_spec.rb
  spec/system/budgets/groups_spec.rb
  spec/system/budgets/investments_spec.rb
  spec/system/tags/budget_investments_spec.rb
Labels: Budgets

#4435 Remove dependabot config file
  .github/dependabot.yml
Labels: Bug, Maintenance

#4432 Avoid timeouts in Knapsack PRO
  Rakefile
  bin/knapsack_pro_rspec
Labels: Specs

#4433 Add experimental Gitlab CI integration
  .gitlab-ci.yml
  config/database.yml.gitlab
Labels: Maintenance

#4438 Comment secret key base on production environments
  config/secrets.yml.example
Labels: Maintenance

#4439 Bump mimemagic to version 0.3.6
  Gemfile.lock
Labels: dependencies

#4404 Change budgets section styles
  .scss-lint.yml
  app/assets/stylesheets/_consul_settings.scss
  app/assets/stylesheets/admin.scss
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/budgets/ballot/investment.scss
  app/assets/stylesheets/budgets/groups_and_headings.scss
  app/assets/stylesheets/budgets/investments/ballot.scss
  app/assets/stylesheets/budgets/investments/sidebar.scss
  app/assets/stylesheets/budgets/phases.scss
  app/assets/stylesheets/dashboard.scss
  app/assets/stylesheets/datepicker_overrides.scss
  app/assets/stylesheets/layout.scss
  app/assets/stylesheets/legislation.scss
  app/assets/stylesheets/legislation_process.scss
  app/assets/stylesheets/mixins.scss
  app/assets/stylesheets/mixins/buttons.scss
  app/assets/stylesheets/mixins/colors.scss
  app/assets/stylesheets/mixins/headings.scss
  app/assets/stylesheets/mixins/icons.scss
  app/assets/stylesheets/mixins/layouts.scss
  app/assets/stylesheets/mixins/orbit_bullets.scss
  app/assets/stylesheets/mixins/sdg.scss
  app/assets/stylesheets/mixins/tags.scss
  app/assets/stylesheets/mixins/tooltips.scss
  app/assets/stylesheets/mixins/uploads.scss
  app/assets/stylesheets/pages.scss
  app/assets/stylesheets/participation.scss
  app/components/budgets/ballot/investment_component.html.erb
  app/components/budgets/ballot/investment_component.rb
  app/components/budgets/ballot/investment_for_sidebar_component.rb
  app/models/budget/ballot.rb
  app/models/budget/voting_styles/base.rb
  app/views/budgets/ballot/_ballot.html.erb
  app/views/budgets/ballot/_investment.html.erb
  app/views/budgets/ballot/_investment_for_sidebar.html.erb
  app/views/budgets/ballot/_progress_bar.html.erb
  app/views/budgets/ballot/progress_bar/_approval.html.erb
  app/views/budgets/ballot/progress_bar/_knapsack.html.erb
  app/views/budgets/investments/_ballot.html.erb
  app/views/budgets/investments/_header.html.erb
  app/views/budgets/investments/_sidebar.html.erb
  app/views/budgets/investments/index.html.erb
  app/views/documents/_nested_documents.html.erb
  app/views/images/_nested_image.html.erb
  config/locales/en/budgets.yml
  config/locales/es/budgets.yml
  spec/system/budgets/ballots_spec.rb
  spec/system/budgets/investments_spec.rb
  spec/system/budgets/votes_spec.rb
Labels: Budgets

#4444 Bump mimemagic to version 0.3.8
  Gemfile.lock
Labels: dependencies

#4445 Allow toggling elements with the keyboard
  app/assets/stylesheets/dashboard.scss
  app/assets/stylesheets/layout.scss
  app/assets/stylesheets/mixins/buttons.scss
  app/assets/stylesheets/participation.scss
  app/assets/stylesheets/sdg/goals/show.scss
  app/components/sdg/goals/show_component.html.erb
  app/views/dashboard/_next_goal.html.erb
  app/views/dashboard/_proposed_action.html.erb
  app/views/dashboard/_recommended_actions_by_status.html.erb
  app/views/layouts/_header.html.erb
  app/views/legislation/processes/_header.html.erb
  app/views/legislation/processes/_header_full.html.erb
  app/views/legislation/processes/_help_gif.html.erb
  app/views/polls/_gallery.html.erb
  app/views/polls/show.html.erb
  app/views/shared/_flag_actions.html.erb
  app/views/verification/residence/new.html.erb
  config/locales/en/general.yml
  spec/shared/system/flaggable.rb
  spec/system/dashboard/dashboard_spec.rb
  spec/system/legislation/draft_versions_spec.rb
  spec/system/legislation/processes_spec.rb
  spec/system/sdg/goals_spec.rb
Labels: Accessibility

#4451 Improve filling in dates in specs
  spec/system/admin/banners_spec.rb
  spec/system/admin/legislation/processes_spec.rb
  spec/system/admin/poll/polls_spec.rb
  spec/system/advanced_search_spec.rb
Labels: Specs
