Repository consuldemocracy/consuldemocracy, pull requests merged in 2021-07, with the labels that each got.

#4516 Limit Font Awesome imports to reduce CSS size
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/mixins/icons.scss
Labels: Maintenance, Release notes

#4561 Fix footer overlap on Internet Explorer 11
  app/assets/stylesheets/layout.scss
  app/assets/stylesheets/mixins/layouts.scss
  app/assets/stylesheets/widgets/feeds/participation.scss
Labels: UX

#4577 Hide SDG columns on admin polls if SDG feature is disabled
  app/views/admin/legislation/processes/index.html.erb
  app/views/admin/poll/polls/_poll.html.erb
  app/views/admin/poll/polls/index.html.erb
  spec/system/admin/legislation/processes_spec.rb
  spec/system/admin/poll/polls_spec.rb
Labels: Admin, Bug, SDG

#4579 Update core members
  CONTRIBUTING.md
  CONTRIBUTING_ES.md
Labels: Maintenance

#4578 Fix content and line-height in SVG font icons
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/mixins/icons.scss
Labels: Bug

#4527 Load SVG icons using asset-data-url
  app/assets/stylesheets/mixins/icons.scss
Labels: Maintenance, UX

#4582 Make it easier to add full width backgrounds
  app/assets/images/logo_header.png
  app/assets/stylesheets/_consul_settings.scss
  app/assets/stylesheets/admin.scss
  app/assets/stylesheets/budgets/investments-list.scss
  app/assets/stylesheets/budgets/investments/new.scss
  app/assets/stylesheets/budgets/phases.scss
  app/assets/stylesheets/budgets/subheader.scss
  app/assets/stylesheets/layout.scss
  app/assets/stylesheets/layout/locale_switcher.scss
  app/assets/stylesheets/legislation_process.scss
  app/assets/stylesheets/mixins/layouts.scss
  app/assets/stylesheets/pages.scss
  app/assets/stylesheets/participation.scss
  app/assets/stylesheets/sdg/goals/index.scss
  app/assets/stylesheets/sdg/goals/show.scss
  app/assets/stylesheets/widgets/feeds/participation.scss
  app/components/sdg/goals/help_page_component.html.erb
  app/components/widget/feeds/participation_component.html.erb
  app/models/site_customization/image.rb
  app/views/debates/index.html.erb
  app/views/layouts/_admin_header.html.erb
  app/views/layouts/_header.html.erb
  app/views/layouts/application.html.erb
  app/views/layouts/management.html.erb
  app/views/proposals/index.html.erb
  app/views/shared/_subnavigation.html.erb
  spec/factories/administration.rb
  spec/fixtures/files/logo_header-260x80.png
  spec/fixtures/files/logo_header.png
  spec/models/site_customization/image_spec.rb
  spec/system/budgets/investments_spec.rb
  spec/system/debates_spec.rb
  spec/system/proposals_spec.rb
Labels: UX

#4580 Improve investment form
  app/assets/stylesheets/budgets/investments/form.scss
  app/assets/stylesheets/budgets/investments/new.scss
  app/assets/stylesheets/layout.scss
  app/components/budgets/investments/form_component.html.erb
  app/components/budgets/investments/form_component.rb
  app/controllers/budgets/investments_controller.rb
  app/controllers/management/budgets/investments_controller.rb
  app/views/budgets/investments/_form.html.erb
  app/views/budgets/investments/edit.html.erb
  app/views/management/budgets/investments/new.html.erb
  config/locales/en/general.yml
  config/locales/es/general.yml
  spec/components/budgets/investments/form_component_spec.rb
  spec/system/budgets/investments_spec.rb
Labels: Budgets

#4583 Remove ES6-specific syntax in amsify suggestags
  vendor/assets/javascripts/jquery.amsify.suggestags.js
Labels: UX

#4587 Do not show confirm message if user can vote in all headings
  app/components/budgets/investments/votes_component.rb
  spec/system/budgets/votes_spec.rb
Labels: Budgets, UX

#4586 Allow attaching files using the keyboard
  app/assets/javascripts/documentable.js
  app/assets/javascripts/imageable.js
  app/assets/stylesheets/mixins/uploads.scss
  app/components/admin/budget_phases/form_component.html.erb
  app/components/admin/budgets/form_component.html.erb
  app/components/budgets/investments/form_component.html.erb
  app/components/documents/fields_component.html.erb
  app/components/documents/fields_component.rb
  app/components/documents/nested_component.html.erb
  app/components/documents/nested_component.rb
  app/components/images/fields_component.html.erb
  app/components/images/fields_component.rb
  app/components/images/nested_component.html.erb
  app/components/images/nested_component.rb
  app/components/proposals/form_component.html.erb
  app/controllers/admin/poll/questions/answers/images_controller.rb
  app/helpers/documentables_helper.rb
  app/helpers/documents_helper.rb
  app/helpers/imageables_helper.rb
  app/helpers/images_helper.rb
  app/views/admin/dashboard/actions/_form.html.erb
  app/views/admin/legislation/processes/_form.html.erb
  app/views/admin/milestones/_form.html.erb
  app/views/admin/poll/polls/_form.html.erb
  app/views/admin/poll/questions/answers/documents.html.erb
  app/views/admin/poll/questions/answers/images/new.html.erb
  app/views/admin/widget/cards/_form.html.erb
  app/views/documents/_document_fields.html.erb
  app/views/documents/_nested_documents.html.erb
  app/views/images/_admin_image.html.erb
  app/views/images/_image_fields.html.erb
  app/views/images/_nested_image.html.erb
  app/views/legislation/proposals/_form.html.erb
  config/locales/en/images.yml
  config/locales/es/images.yml
  spec/shared/system/documentable.rb
  spec/shared/system/imageable.rb
  spec/shared/system/nested_documentable.rb
  spec/shared/system/nested_imageable.rb
  spec/system/admin/widgets/cards_spec.rb
Labels: Accessibility, Bug, Refactoring

#4590 Fix typo in Spanish translation for "yes"
  config/locales/es/admin.yml
  config/locales/es/general.yml
Labels: Bug, Translations
