Repository consuldemocracy/consuldemocracy, pull requests merged in 2021-08, with the labels that each got.

#4596 Use a rake task to delete cached attachments
  app/assets/javascripts/documentable.js
  app/assets/javascripts/imageable.js
  app/components/documents/fields_component.rb
  app/components/images/fields_component.rb
  app/controllers/direct_uploads_controller.rb
  app/helpers/direct_uploads_helper.rb
  app/models/direct_upload.rb
  app/models/document.rb
  app/models/image.rb
  config/routes/direct_upload.rb
  config/schedule.rb
  lib/tasks/files.rake
  spec/lib/tasks/files_spec.rb
  spec/models/direct_upload_spec.rb
Labels: Bug, UX

#4597 Fix rubocop convention offenses
  spec/system/advanced_search_spec.rb
  spec/system/budgets/investments_spec.rb
  spec/system/emails_spec.rb
Labels: Rubocop

#4594 Render investments list when budget has multiple headings
  app/assets/stylesheets/budgets/ballot/show.scss
  app/assets/stylesheets/budgets/groups/index.scss
  app/assets/stylesheets/budgets/groups/show.scss
  app/assets/stylesheets/budgets/index.scss
  app/assets/stylesheets/layout.scss
  app/assets/stylesheets/mixins/budgets.scss
  app/assets/stylesheets/mixins/buttons.scss
  app/assets/stylesheets/participation.scss
  app/components/budgets/groups/index_component.html.erb
  app/components/budgets/groups/index_component.rb
  app/components/budgets/investments_list_component.html.erb
  app/components/budgets/investments_list_component.rb
  app/components/budgets/supports_info_component.html.erb
  app/components/concerns/header.rb
  app/controllers/budgets/groups_controller.rb
  app/views/budgets/ballot/_ballot.html.erb
  app/views/budgets/ballot/show.html.erb
  app/views/budgets/groups/index.html.erb
  app/views/budgets/groups/show.html.erb
  app/views/budgets/index.html.erb
  config/routes/budget.rb
  spec/components/budgets/investments_list_component_spec.rb
  spec/components/budgets/supports_info_component_spec.rb
  spec/system/budgets/budgets_spec.rb
  spec/system/budgets/groups_spec.rb
Labels: Budgets

#4605 Fix inconsistent order in system email preview
  app/controllers/admin/system_emails_controller.rb
  app/views/admin/system_emails/preview_pending/_proposal_notification_digest.html.erb
Labels: Bug, Flaky bug

#4646 Downgrade airbrake from 11.0.3 to 7.4.0
  Gemfile
  Gemfile.lock
Labels: dependencies

#4658 Bump faker from 1.8.7 to 2.0
  Gemfile
  Gemfile.lock
  db/dev_seeds/banners.rb
  db/dev_seeds/budgets.rb
  db/dev_seeds/communities.rb
  db/dev_seeds/debates.rb
  db/dev_seeds/legislation_processes.rb
  db/dev_seeds/legislation_proposals.rb
  db/dev_seeds/notifications.rb
  db/dev_seeds/polls.rb
  db/dev_seeds/proposals.rb
  lib/tasks/proposal_actions.rake
  spec/factories/budgets.rb
  spec/lib/remote_translations/microsoft/client_spec.rb
  spec/models/tag_spec.rb
  spec/shared/system/remotely_translatable.rb
Labels: dependencies

#4663 Fix tests after replacing message with notification
  spec/system/dashboard/dashboard_spec.rb
  spec/system/direct_messages_spec.rb
  spec/system/proposal_notifications_spec.rb
Labels: Specs

#4664 Explicitely use Debian Buster in Dockerfile
  Dockerfile
Labels: Maintenance

#4647 Improve support for RTL languages
  app/assets/stylesheets/application-rtl.scss
  app/helpers/application_helper.rb
  app/views/layouts/_common_head.html.erb
  app/views/layouts/admin.html.erb
  app/views/layouts/application.html.erb
  app/views/layouts/devise.html.erb
  app/views/layouts/management.html.erb
  config/initializers/assets.rb
Labels: UX, Community Interest

#4674 Issue#4013 lenghth validations
  app/components/debates/form_component.html.erb
  app/models/concerns/measurable.rb
  app/models/debate.rb
  spec/models/concerns/globalizable.rb
  spec/models/debate_spec.rb
  spec/system/debates_spec.rb
Labels: UX
