Repository consuldemocracy/consuldemocracy, pull requests merged in 2022-05, with the labels that each got.

#4807 Remove and simplify API and votes-related code
  app/models/comment.rb
  app/models/proposal_notification.rb
  app/models/user.rb
  config/initializers/vote_extensions.rb
  spec/models/vote_spec.rb
Labels: Refactoring

#4823 Fix crash deleting admin with assigned budgets
  app/models/administrator.rb
  spec/models/administrator_spec.rb
Labels: Bug

#4810 Show budgets map only if feature is enabled
  app/components/budgets/budget_component.html.erb
  app/components/budgets/budget_component.rb
  app/components/budgets/map_component.html.erb
  app/components/budgets/map_component.rb
  app/models/concerns/mappable.rb
  spec/components/budgets/map_component_spec.rb
  spec/system/budgets/budgets_spec.rb
Labels: Bug, Budgets

#4816 Add development instructions regarding i18n translations
  CONTRIBUTING.md
  CONTRIBUTING_ES.md
Labels: Documentation

#4814 Fix background image from Participatory Budgets page
  app/assets/stylesheets/participation.scss
Labels: Bug

#4824 Bump Rails from 5.2.7 to 5.2.7.1
  Gemfile
  Gemfile.lock
Labels: dependencies, security

#4825 Fix link and text selection in budget header
  app/assets/stylesheets/participation.scss
  spec/system/budgets/budgets_spec.rb
Labels: Bug

#4809 Remove roles when block or delete users
  app/models/user.rb
  spec/models/user_spec.rb
  spec/system/account_spec.rb
  spec/system/moderation/users_spec.rb
Labels: Bug
