Repository consuldemocracy/consuldemocracy, pull requests merged in 2022-06, with the labels that each got.

#4827 Include machine learning settings type
  app/models/setting.rb
  spec/system/admin/settings_spec.rb
Labels: Bug, Admin

#4820 Remove unnecessary alert on legislation processes
  app/views/legislation/processes/_debate.html.erb
  app/views/legislation/processes/debate.html.erb
  config/locales/en/legislation.yml
  config/locales/es/legislation.yml
  spec/system/legislation/processes_spec.rb
  spec/system/legislation/questions_spec.rb
Labels: Legislation, UX

#4766 Add new GraphQL types & schema
  app/controllers/graphql_controller.rb
  app/graphql/consul_schema.rb
  app/graphql/mutations/base_mutation.rb
  app/graphql/types/base_object.rb
  app/graphql/types/comment_type.rb
  app/graphql/types/debate_type.rb
  app/graphql/types/geozone_type.rb
  app/graphql/types/mutation_type.rb
  app/graphql/types/proposal_notification_type.rb
  app/graphql/types/proposal_type.rb
  app/graphql/types/query_type.rb
  app/graphql/types/tag_type.rb
  app/graphql/types/user_type.rb
  app/graphql/types/vote_type.rb
  app/models/concerns/graphqlable.rb
  app/models/concerns/has_public_author.rb
  config/api.yml
  config/initializers/acts_as_taggable_on.rb
  config/routes/graphql.rb
  lib/graph_ql/api_types_creator.rb
  lib/graph_ql/query_type_creator.rb
  spec/lib/graph_ql/api_types_creator_spec.rb
  spec/lib/graph_ql/query_type_creator_spec.rb
  spec/lib/graphql_spec.rb
Labels: Release notes, Maintenance

#4826 Fix warnings when compiling SCSS
  app/assets/stylesheets/_consul_settings.scss
Labels: dependencies, Maintenance

#4802 Fix typos in the English version
  app/views/account/show.html.erb
  app/views/management/_user_permissions.html.erb
  app/views/management/document_verifications/invalid_document.html.erb
  app/views/management/document_verifications/new.html.erb
  app/views/management/document_verifications/verified.html.erb
  app/views/management/email_verifications/sent.html.erb
  app/views/management/users/new.html.erb
  app/views/management/users/show.html.erb
  config/locales/en/activerecord.yml
  config/locales/en/admin.yml
  config/locales/en/general.yml
  config/locales/en/legislation.yml
  config/locales/en/management.yml
  config/locales/en/verification.yml
  config/locales/es/general.yml
  config/locales/es/management.yml
  config/locales/es/verification.yml
  db/pages/welcome_level_three_verified.rb
  db/pages/welcome_level_two_verified.rb
  db/pages/welcome_not_verified.rb
  spec/components/subscriptions/edit_component_spec.rb
  spec/models/related_content_spec.rb
  spec/system/account_spec.rb
  spec/system/admin/site_customization/information_texts_spec.rb
  spec/system/dashboard/dashboard_spec.rb
  spec/system/emails_spec.rb
  spec/system/management/document_verifications_spec.rb
  spec/system/management/managed_users_spec.rb
  spec/system/proposal_notifications_spec.rb
  spec/system/proposals_spec.rb
  spec/system/site_customization/information_texts_spec.rb
  spec/system/subscriptions_spec.rb
  spec/system/users_spec.rb
Labels: Bug

#4815 Fix Confirmation Token to only work once - #2746
  app/controllers/users/confirmations_controller.rb
  spec/controllers/users/confirmations_controller_spec.rb
  spec/system/users_auth_spec.rb
Labels: Bug, UX

#4818 System emails design
  app/assets/images/icon_mailer_comment.png
  app/assets/images/icon_mailer_reply.png
  app/assets/images/icon_mailer_share.png
  app/controllers/admin/system_emails_controller.rb
  app/helpers/mailer_helper.rb
  app/mailers/devise_mailer.rb
  app/views/devise/mailer/confirmation_instructions.html.erb
  app/views/devise/mailer/reset_password_instructions.html.erb
  app/views/devise/mailer/unlock_instructions.html.erb
  app/views/mailer/already_confirmed.html.erb
  app/views/mailer/budget_investment_created.html.erb
  app/views/mailer/budget_investment_selected.html.erb
  app/views/mailer/budget_investment_unfeasible.html.erb
  app/views/mailer/budget_investment_unselected.html.erb
  app/views/mailer/comment.html.erb
  app/views/mailer/direct_message_for_receiver.html.erb
  app/views/mailer/direct_message_for_sender.html.erb
  app/views/mailer/email_verification.html.erb
  app/views/mailer/evaluation_comment.html.erb
  app/views/mailer/machine_learning_error.html.erb
  app/views/mailer/machine_learning_success.html.erb
  app/views/mailer/newsletter.html.erb
  app/views/mailer/proposal_notification_digest.html.erb
  app/views/mailer/reply.html.erb
  app/views/mailer/user_invite.html.erb
  config/locales/en/mailers.yml
  config/locales/es/mailers.yml
  spec/system/admin/system_emails_spec.rb
Labels: Refactoring, 1.5

#4841 Make it possible to customize GraphQL types
  app/graphql/custom/mutations/.keep
  app/graphql/custom/types/.keep
  config/application.rb
Labels: Customization, 1.5

#4847 Remove legacy annotations route
  config/routes.rb
  config/routes/annotation.rb
Labels: Bug, 1.5

#4846 Remove unused CSS containing a typo
  app/assets/stylesheets/layout.scss
Labels: Maintenance, 1.5

#4842 Upgrade Ruby to version 2.7.6
  .gitlab-ci.yml
  .ruby-version
  Dockerfile
  Gemfile.lock
  README.md
  README_ES.md
Labels: Maintenance, 1.5

#4844 Allow removing investment supports by default
  app/models/setting.rb
  db/dev_seeds/settings.rb
Labels: UX, Maintenance, 1.5

#4845 Describe enabled processes in the consul.json URL
  app/controllers/installation_controller.rb
  spec/controllers/installation_controller_spec.rb
Labels: Maintenance, 1.5

#4848 Add notice after destroying a banner
  app/controllers/admin/banners_controller.rb
  config/locales/en/admin.yml
  config/locales/es/admin.yml
  spec/system/admin/banners_spec.rb
Labels: UX

#4849 Reduce conflicting queries/requests in system tests
  spec/shared/system/mappable.rb
  spec/shared/system/nested_documentable.rb
  spec/shared/system/nested_imageable.rb
  spec/support/common_actions/maps.rb
  spec/system/admin/poll/booths_spec.rb
  spec/system/admin/poll/polls_spec.rb
  spec/system/moderation/users_spec.rb
Labels: Flaky spec, Specs, 1.5

#4811 Fix Registration Without E-Mail
  app/controllers/users/registrations_controller.rb
  app/models/user.rb
  spec/system/registration_form_spec.rb
Labels: Bug, 1.5

#4837 Fix bug when creating admin tags
  app/controllers/admin/tags_controller.rb
  spec/system/admin/tags_spec.rb
Labels: Bug, 1.5

#4850 Disable Turbolinks for languages with different text direction
  app/components/layout/locale_switcher_component.rb
  app/helpers/application_helper.rb
  spec/components/layout/locale_switcher_component_spec.rb
Labels: Bug, 1.5

#4696 Enable the `Rails/I18nLocaleAssignment` cop to scan all the application ruby files
  .rubocop.yml
  app/controllers/application_controller.rb
  app/controllers/management/base_controller.rb
  app/controllers/subscriptions_controller.rb
  spec/spec_helper.rb
Labels: Rubocop, 1.5

#4856 Disable JavaScript in notification digest spec
  spec/system/emails_spec.rb
Labels: Flaky spec, 1.5

#4858 Fix Rubocop convention offenses
  app/controllers/admin/tags_controller.rb
  spec/models/abilities/common_spec.rb
  spec/system/legislation/processes_spec.rb
Labels: Rubocop, 1.5

#4756 Fix translations interpolations errors
  app/views/budgets/stats/show.html.erb
  app/views/polls/stats.html.erb
  config/locales/ar/admin.yml
  config/locales/ar/budgets.yml
  config/locales/ar/community.yml
  config/locales/ar/general.yml
  config/locales/ar/kaminari.yml
  config/locales/ar/legislation.yml
  config/locales/en/stats.yml
  config/locales/nn/budgets.yml
  config/locales/nn/community.yml
  config/locales/nn/general.yml
Labels: Bug, Translations, 1.5
