Repository consuldemocracy/consuldemocracy, pull requests merged in 2022-11, with the labels that each got.

#5021 Make it easier to have different colors per tenant
  app/assets/stylesheets/_consul_settings.scss
  app/assets/stylesheets/admin.scss
  app/assets/stylesheets/admin/budgets_wizard/creation_timeline.scss
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/budgets/ballot/investment.scss
  app/assets/stylesheets/budgets/groups_and_headings.scss
  app/assets/stylesheets/budgets/investments/ballot.scss
  app/assets/stylesheets/budgets/phases.scss
  app/assets/stylesheets/budgets/single_heading.scss
  app/assets/stylesheets/budgets/supports_info.scss
  app/assets/stylesheets/custom/tenants.scss
  app/assets/stylesheets/dashboard.scss
  app/assets/stylesheets/datepicker_overrides.scss
  app/assets/stylesheets/functions/reverse_list.scss
  app/assets/stylesheets/layout.scss
  app/assets/stylesheets/layout/social.scss
  app/assets/stylesheets/legislation_process.scss
  app/assets/stylesheets/mixins/buttons.scss
  app/assets/stylesheets/mixins/colors.scss
  app/assets/stylesheets/mixins/forms.scss
  app/assets/stylesheets/mixins/icons.scss
  app/assets/stylesheets/pages.scss
  app/assets/stylesheets/participation.scss
Labels: Community Interest, Customization, 1.6

#5003 Add SDG images in Galego
  vendor/assets/images/sdg/gl/goal_1.png
  vendor/assets/images/sdg/gl/goal_10.png
  vendor/assets/images/sdg/gl/goal_11.png
  vendor/assets/images/sdg/gl/goal_12.png
  vendor/assets/images/sdg/gl/goal_13.png
  vendor/assets/images/sdg/gl/goal_14.png
  vendor/assets/images/sdg/gl/goal_15.png
  vendor/assets/images/sdg/gl/goal_16.png
  vendor/assets/images/sdg/gl/goal_17.png
  vendor/assets/images/sdg/gl/goal_2.png
  vendor/assets/images/sdg/gl/goal_3.png
  vendor/assets/images/sdg/gl/goal_4.png
  vendor/assets/images/sdg/gl/goal_5.png
  vendor/assets/images/sdg/gl/goal_6.png
  vendor/assets/images/sdg/gl/goal_7.png
  vendor/assets/images/sdg/gl/goal_8.png
  vendor/assets/images/sdg/gl/goal_9.png
  vendor/assets/images/sdg/gl/original/goal_1.png
  vendor/assets/images/sdg/gl/original/goal_10.png
  vendor/assets/images/sdg/gl/original/goal_11.png
  vendor/assets/images/sdg/gl/original/goal_12.png
  vendor/assets/images/sdg/gl/original/goal_13.png
  vendor/assets/images/sdg/gl/original/goal_14.png
  vendor/assets/images/sdg/gl/original/goal_15.png
  vendor/assets/images/sdg/gl/original/goal_16.png
  vendor/assets/images/sdg/gl/original/goal_17.png
  vendor/assets/images/sdg/gl/original/goal_2.png
  vendor/assets/images/sdg/gl/original/goal_3.png
  vendor/assets/images/sdg/gl/original/goal_4.png
  vendor/assets/images/sdg/gl/original/goal_5.png
  vendor/assets/images/sdg/gl/original/goal_6.png
  vendor/assets/images/sdg/gl/original/goal_7.png
  vendor/assets/images/sdg/gl/original/goal_8.png
  vendor/assets/images/sdg/gl/original/goal_9.png
Labels: SDG, 1.6

#5037 Add expectations in tests confirming account
  spec/system/multitenancy_spec.rb
  spec/system/users_auth_spec.rb
Labels: Flaky spec, 2.0

#5038 Fix crash voting on a heading with a content block
  app/components/budgets/investments/content_blocks_component.html.erb
  app/components/budgets/investments/content_blocks_component.rb
  app/controllers/budgets/investments_controller.rb
  app/views/budgets/investments/_content_blocks.html.erb
  app/views/budgets/investments/_sidebar.html.erb
  spec/components/budgets/investments/content_blocks_component_spec.rb
  spec/system/budgets/ballots_spec.rb
Labels: Bug, 2.0

#5030 Allow rendering different ERB files per tenant
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/concerns/tenant_variants.rb
  app/controllers/management/base_controller.rb
  app/controllers/management/sessions_controller.rb
  app/mailers/application_mailer.rb
  spec/controllers/concerns/tenant_variants_spec.rb
  spec/mailers/application_mailer_spec.rb
Labels: Community Interest, Customization, 2.0

#5039 Use Coveralls Github Action to send test reports
  .github/workflows/tests.yml
  .gitlab-ci.yml
  Gemfile
  Gemfile.lock
  spec/rails_helper.rb
Labels: Maintenance, 2.0
