Repository consuldemocracy/consuldemocracy, pull requests merged in 2022-08, with the labels that each got.

#4883 Bump rails from 5.2.7.1 to 5.2.8.1
  Gemfile
  Gemfile.lock
  config/application.rb
Labels: dependencies, security

#4877 Use jQuery 3.5.1 in Annotator
  vendor/assets/javascripts/annotator.js
Labels: security, Maintenance

#4855 chore: Set permissions for GitHub actions
  .github/workflows/docker.yml
  .github/workflows/tests.yml
Labels: Maintenance

#4833 Add more images to admin site customization
  app/assets/stylesheets/layout.scss
  app/components/budgets/executions/image_component.html.erb
  app/components/budgets/executions/image_component.rb
  app/components/budgets/investment_component.html.erb
  app/components/budgets/investment_component.rb
  app/components/widget/feeds/process_component.html.erb
  app/components/widget/feeds/process_component.rb
  app/helpers/budget_executions_helper.rb
  app/models/site_customization/image.rb
  app/views/budgets/executions/_investments.html.erb
  app/views/layouts/_common_head.html.erb
  app/views/layouts/dashboard.html.erb
  app/views/layouts/devise.html.erb
  spec/components/budgets/executions/image_component_spec.rb
  spec/components/budgets/investment_component_spec.rb
  spec/components/widget/feeds/process_component_spec.rb
  spec/fixtures/files/favicon_custom.ico
  spec/models/site_customization/image_spec.rb
  spec/system/site_customization/images_spec.rb
Labels: Admin

#4864 Add helpers for mailer footer styles
  app/helpers/mailer_helper.rb
  app/mailers/application_mailer.rb
  app/mailers/mailer.rb
  app/views/layouts/_mailer_footer.html.erb
Labels: Refactoring

#4876 Close comments when the allegations phase is closed
  app/controllers/legislation/annotations_controller.rb
  app/models/legislation/annotation.rb
  spec/controllers/comments_controller_spec.rb
  spec/controllers/legislation/annotations_controller_spec.rb
  spec/system/comments/legislation_annotations_spec.rb
Labels: Bug, Legislation

#4906 Use the latest Ubuntu image to run tests and coveralls
  .github/workflows/tests.yml
Labels: Maintenance

#4839 Add comments count on budget investments
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/comments_count.scss
  app/assets/stylesheets/legislation_process.scss
  app/assets/stylesheets/participation.scss
  app/components/budgets/investments/info_component.html.erb
  app/components/shared/comments_count_component.html.erb
  app/components/shared/comments_count_component.rb
  app/views/admin/debates/show.html.erb
  app/views/budgets/investments/_investment_detail.html.erb
  app/views/debates/_debate.html.erb
  app/views/debates/show.html.erb
  app/views/legislation/annotations/_comment_header.html.erb
  app/views/legislation/annotations/_form.html.erb
  app/views/legislation/annotations/comments.js.erb
  app/views/legislation/annotations/index.html.erb
  app/views/legislation/draft_versions/_comments_panel.html.erb
  app/views/legislation/processes/_summary_allegations.html.erb
  app/views/legislation/processes/_summary_debate.html.erb
  app/views/legislation/processes/summary.xlsx.axlsx
  app/views/legislation/proposals/_proposal.html.erb
  app/views/legislation/proposals/show.html.erb
  app/views/legislation/questions/_question.html.erb
  app/views/proposals/_info.html.erb
  app/views/proposals/_proposal.html.erb
  app/views/topics/_topic.html.erb
  app/views/topics/show.html.erb
  config/locales/en/community.yml
  config/locales/en/general.yml
  config/locales/en/legislation.yml
  config/locales/es/general.yml
  config/locales/es/legislation.yml
  spec/components/shared/comments_count_component_spec.rb
  spec/system/budgets/investments_spec.rb
  spec/system/legislation/questions_spec.rb
Labels: Budgets, Release notes

#4874 Upgrade to Rails 6.0
  Gemfile
  Gemfile.lock
  app/components/admin/menu_component.html.erb
  app/components/admin/menu_component.rb
  app/components/admin/poll/officers/officers_component.html.erb
  app/components/admin/stats/stat_component.html.erb
  app/components/shared/link_list_component.html.erb
  app/components/shared/link_list_component.rb
  app/helpers/stats_helper.rb
  app/helpers/translatable_form_helper.rb
  app/models/concerns/attachable.rb
  app/models/concerns/has_attachment.rb
  app/models/direct_upload.rb
  app/models/image.rb
  app/models/site_customization/image.rb
  app/views/layouts/admin.html.erb
  app/views/shared/_subnavigation.html.erb
  bin/setup
  config/application.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/staging.rb
  config/environments/test.rb
  config/initializers/content_security_policy.rb
  config/initializers/i18n_translation.rb
  db/migrate/20210924194527_add_foreign_key_constraint_to_active_storage_attachments_for_blob_id.active_storage.rb
  db/schema.rb
  spec/lib/tasks/files_spec.rb
  spec/shared/system/relationable.rb
  spec/system/admin/budget_investments_spec.rb
  spec/system/admin/emails/emails_download_spec.rb
Labels: dependencies, Maintenance

#4919 Add more expectations in SDG Management search spec
  spec/system/sdg_management/relations_spec.rb
Labels: Flaky spec

#4881 Use Rails 6.0 methods to simplify code
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/models/concerns/attachable.rb
  app/models/setting.rb
  app/views/shared/_errors.html.erb
  config/initializers/globalize.rb
  db/dev_seeds.rb
  db/dev_seeds/admin_notifications.rb
  db/dev_seeds/widgets.rb
  spec/models/budget/investment_spec.rb
  spec/models/concerns/globalizable.rb
  spec/models/poll/stats_spec.rb
  spec/spec_helper.rb
  spec/system/admin/poll/shifts_spec.rb
  spec/system/polls/voter_spec.rb
Labels: Maintenance

#4941 Fix Rails/ReversibleMigration rule offenses
  db/migrate/20150806111435_change_debates_title_length.rb
  db/migrate/20151019133719_remove_user_constraints.rb
  db/migrate/20151103175139_make_comments_confidence_score_default_to_0.rb
  db/migrate/20160418172919_activate_newsletter_by_default.rb
  db/migrate/20161102133838_default_password_changed_at.rb
  db/migrate/20170102080432_adjust_budget_fields.rb
  db/migrate/20180220211105_change_newsletter_segment_recipient_to_string.rb
  db/migrate/20180702050717_add_short_description_to_proposal_dashboard_actions.rb
  db/migrate/20200908084257_change_attachment_size_fields_to_bigint.rb
Labels: dependencies
