Repository consuldemocracy/consuldemocracy, pull requests merged in 2022-01, with the labels that each got.

#4755 Make it easier to maintain the test suite in forks
  spec/components/custom/.keep
  spec/controllers/custom/.keep
  spec/custom_spec_helper.rb
  spec/rails_helper.rb
  spec/routing/custom/.keep
  spec/system/custom/.keep
Labels: Specs, Customization

#4767 Fix generating dashboard poster on production
  app/assets/config/manifest.js
  app/assets/stylesheets/dashboard_poster.scss
  app/views/dashboard/poster/index.pdf.erb
Labels: Bug

#4301 Include link to unsubscribe in email notifications
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/layout.scss
  app/assets/stylesheets/subscriptions.scss
  app/components/subscriptions/edit_component.html.erb
  app/components/subscriptions/edit_component.rb
  app/controllers/subscriptions_controller.rb
  app/mailers/mailer.rb
  app/models/user.rb
  app/views/mailer/comment.html.erb
  app/views/mailer/direct_message_for_receiver.html.erb
  app/views/mailer/newsletter.html.erb
  app/views/mailer/proposal_notification_digest.html.erb
  app/views/mailer/reply.html.erb
  app/views/subscriptions/edit.html.erb
  config/locales/en/activerecord.yml
  config/locales/en/mailers.yml
  config/locales/es/activerecord.yml
  config/locales/es/mailers.yml
  config/routes/account.rb
  db/migrate/20201218082830_add_subscriptions_token_to_users.rb
  db/schema.rb
  spec/components/subscriptions/edit_component_spec.rb
  spec/controllers/subscriptions_controller_spec.rb
  spec/mailers/mailer_spec.rb
  spec/models/user_spec.rb
  spec/system/admin/system_emails_spec.rb
  spec/system/emails_spec.rb
  spec/system/subscriptions_spec.rb
Labels: Newsletters

#4773 Fix typo for "instagram"
  app/components/layout/social_component.rb
  spec/components/layout/social_component_spec.rb
Labels: Bug
