Repository consuldemocracy/consuldemocracy, pull requests merged in 2022-03, with the labels that each got.

#4782 Add cs icon of SDGs
  vendor/assets/images/sdg/cs/goal_1.png
  vendor/assets/images/sdg/cs/goal_10.png
  vendor/assets/images/sdg/cs/goal_11.png
  vendor/assets/images/sdg/cs/goal_12.png
  vendor/assets/images/sdg/cs/goal_13.png
  vendor/assets/images/sdg/cs/goal_14.png
  vendor/assets/images/sdg/cs/goal_15.png
  vendor/assets/images/sdg/cs/goal_16.png
  vendor/assets/images/sdg/cs/goal_17.png
  vendor/assets/images/sdg/cs/goal_2.png
  vendor/assets/images/sdg/cs/goal_3.png
  vendor/assets/images/sdg/cs/goal_4.png
  vendor/assets/images/sdg/cs/goal_5.png
  vendor/assets/images/sdg/cs/goal_6.png
  vendor/assets/images/sdg/cs/goal_7.png
  vendor/assets/images/sdg/cs/goal_8.png
  vendor/assets/images/sdg/cs/goal_9.png
  vendor/assets/images/sdg/cs/original/goal_1.png
  vendor/assets/images/sdg/cs/original/goal_10.png
  vendor/assets/images/sdg/cs/original/goal_11.png
  vendor/assets/images/sdg/cs/original/goal_12.png
  vendor/assets/images/sdg/cs/original/goal_13.png
  vendor/assets/images/sdg/cs/original/goal_14.png
  vendor/assets/images/sdg/cs/original/goal_15.png
  vendor/assets/images/sdg/cs/original/goal_16.png
  vendor/assets/images/sdg/cs/original/goal_17.png
  vendor/assets/images/sdg/cs/original/goal_2.png
  vendor/assets/images/sdg/cs/original/goal_3.png
  vendor/assets/images/sdg/cs/original/goal_4.png
  vendor/assets/images/sdg/cs/original/goal_5.png
  vendor/assets/images/sdg/cs/original/goal_6.png
  vendor/assets/images/sdg/cs/original/goal_7.png
  vendor/assets/images/sdg/cs/original/goal_8.png
  vendor/assets/images/sdg/cs/original/goal_9.png
Labels: SDG

#4784 Bump rails from 5.2.6 to 5.2.7
  Gemfile
  Gemfile.lock
Labels: dependencies, security

#4788 Make it easier to customize JavaScript functions
  app/assets/javascripts/application.js
  config/application.rb
Labels: Release notes, Customization

#4787 Make it easier to customise model constants
  app/models/activity.rb
  app/models/budget.rb
  app/models/budget/phase.rb
  app/models/budget/reclassified_vote.rb
  app/models/comment.rb
  app/models/legislation/draft_version.rb
  app/models/legislation/process.rb
  app/models/poll/partial_result.rb
  app/models/poll/recount.rb
  app/models/poll/voter.rb
  app/models/progress_bar.rb
  app/models/proposal.rb
  app/models/signature_sheet.rb
  app/models/site_customization/content_block.rb
  app/models/site_customization/image.rb
  app/models/site_customization/page.rb
  spec/models/activity_spec.rb
  spec/models/budget/phase_spec.rb
  spec/models/budget/reclassified_vote_spec.rb
  spec/models/budget_spec.rb
  spec/models/comment_spec.rb
  spec/models/legislation/draft_version_spec.rb
  spec/models/legislation/process_spec.rb
  spec/models/poll/partial_result_spec.rb
  spec/models/poll/recount_spec.rb
  spec/models/poll/voter_spec.rb
  spec/models/progress_bar_spec.rb
  spec/models/proposal_spec.rb
  spec/models/signature_sheet_spec.rb
  spec/models/site_customization/content_block_spec.rb
  spec/models/site_customization/image_spec.rb
  spec/models/site_customization/page_spec.rb
Labels: Customization

#4775 Add offline ballot sheet votes to the total vote count
  app/models/poll/ballot_sheet.rb
  app/views/officing/ballot_sheets/new.html.erb
  spec/models/poll/ballot_sheet_spec.rb
  spec/system/officing/ballot_sheets_spec.rb
Labels: Bug

#4789 Add Rails 6.0 compatibility
  app/models/poll/booth_assignment.rb
  app/views/proposals/created.html.erb
  config/initializers/acts_as_taggable_on.rb
  spec/components/sdg/related_list_selector_component_spec.rb
  spec/lib/consul_form_builder_spec.rb
  spec/models/tagging_spec.rb
Labels: Bug, Maintenance

#4790 Make it easier to customize validations
  app/models/application_record.rb
  app/models/concerns/skip_validation.rb
  config/initializers/globalize.rb
  spec/models/skip_validation_spec.rb
Labels: Customization

#4792 Avoid model inheritance in skip validation test
  spec/models/skip_validation_spec.rb
Labels: Flaky spec

#4791 Fix crash on attributes with interpolation arguments
  lib/consul_form_builder.rb
  spec/lib/consul_form_builder_spec.rb
Labels: Bug

#4601 Add hide money option for approval budgets
  app/assets/javascripts/application.js
  app/assets/javascripts/budget_hide_money.js
  app/components/admin/budget_headings/headings_component.html.erb
  app/components/admin/budgets/form_component.html.erb
  app/components/admin/budgets/form_component.rb
  app/components/budgets/ballot/investment_component.rb
  app/components/budgets/groups_and_headings_component.rb
  app/components/budgets/investments/new_component.rb
  app/components/budgets/single_heading_component.html.erb
  app/components/budgets/single_heading_component.rb
  app/controllers/admin/budgets_controller.rb
  app/controllers/admin/budgets_wizard/budgets_controller.rb
  app/models/budget.rb
  app/models/budget/investment.rb
  app/models/budget/result.rb
  app/views/admin/budget_headings/_form.html.erb
  app/views/admin/budget_investments/_investments.html.erb
  app/views/admin/budget_investments/_select_investment.html.erb
  app/views/budgets/results/_results_table.html.erb
  app/views/valuation/budget_investments/_dossier.html.erb
  app/views/valuation/budget_investments/_dossier_form.html.erb
  config/locales/en/activerecord.yml
  config/locales/en/admin.yml
  config/locales/en/budgets.yml
  config/locales/es/activerecord.yml
  config/locales/es/admin.yml
  config/locales/es/budgets.yml
  db/migrate/20210311110036_add_hide_money_to_budgets.rb
  db/schema.rb
  spec/factories/budgets.rb
  spec/models/budget/heading_spec.rb
  spec/models/budget/investment_spec.rb
  spec/models/budget_spec.rb
  spec/system/admin/budget_headings_spec.rb
  spec/system/admin/budget_investments_spec.rb
  spec/system/admin/budgets_spec.rb
  spec/system/budgets/ballots_spec.rb
  spec/system/budgets/budgets_spec.rb
  spec/system/budgets/investments_spec.rb
  spec/system/budgets/results_spec.rb
  spec/system/valuation/budget_investments_spec.rb
Labels: Budgets

#4769 Show assigned heading on investment show
  app/components/budgets/investments/ballot_component.rb
  app/controllers/budgets/investments_controller.rb
  app/views/budgets/investments/_ballot.html.erb
  spec/components/budgets/investments/ballot_component_spec.rb
  spec/system/budgets/investments_spec.rb
Labels: Bug, Budgets
