Repository consuldemocracy/consuldemocracy, pull requests merged in 2022-04, with the labels that each got.

#4800 Fix checkbox label styles
  app/assets/stylesheets/layout.scss
  app/assets/stylesheets/mixins/forms.scss
  lib/consul_form_builder.rb
  spec/lib/consul_form_builder_spec.rb
Labels: Bug, UX

#4801 Allow to customize tests common action modules
  spec/shared/system/mappable.rb
  spec/shared/system/nested_documentable.rb
  spec/shared/system/nested_imageable.rb
  spec/support/common_actions.rb
  spec/support/common_actions/custom/.keep
  spec/support/common_actions/documents.rb
  spec/support/common_actions/images.rb
  spec/support/common_actions/maps.rb
  spec/support/common_actions/users.rb
Labels: Customization

#4803 Implement or remove pending tests
  app/controllers/debates_controller.rb
  app/models/abilities/administrator.rb
  app/models/abilities/moderator.rb
  app/views/admin/poll/questions/answers/images/new.html.erb
  app/views/debates/map.html.erb
  config/routes/debate.rb
  spec/models/abilities/administrator_spec.rb
  spec/models/abilities/moderator_spec.rb
  spec/models/concerns/globalizable.rb
  spec/models/concerns/reportable.rb
  spec/models/poll/poll_spec.rb
  spec/models/poll/stats_spec.rb
  spec/models/tag_cloud_spec.rb
  spec/shared/models/sanitizable.rb
  spec/shared/system/flaggable.rb
  spec/shared/system/mappable.rb
  spec/shared/system/nested_documentable.rb
  spec/shared/system/nested_imageable.rb
  spec/shared/system/remotely_translatable.rb
  spec/system/admin/budget_investments_spec.rb
  spec/system/admin/homepage/homepage_spec.rb
  spec/system/admin/poll/questions_spec.rb
  spec/system/admin/widgets/cards_spec.rb
  spec/system/comments/legislation_annotations_spec.rb
  spec/system/comments/polls_spec.rb
  spec/system/debates_spec.rb
  spec/system/emails_spec.rb
  spec/system/proposal_notifications_spec.rb
  spec/system/verification/level_two_verification_spec.rb
Labels: Bug, Polls, Specs

#4765 Add dockerignore file
  .dockerignore
  .gitignore
Labels: Devops

#4806 Add and improve hint information related to phases duration
  app/assets/stylesheets/admin/budgets/show.scss
  app/assets/stylesheets/layout.scss
  app/components/admin/budget_phases/form_component.html.erb
  app/components/admin/budgets/show_component.html.erb
  app/views/admin/budget_phases/edit.html.erb
  config/locales/en/admin.yml
  config/locales/es/admin.yml
  spec/system/admin/budget_phases_spec.rb
  spec/system/admin/budgets_spec.rb
Labels: Admin, UX

#4228 Send informative email for already confirmed users
  app/controllers/users/confirmations_controller.rb
  app/mailers/mailer.rb
  app/views/mailer/already_confirmed.html.erb
  config/locales/en/devise.yml
  config/locales/en/mailers.yml
  config/locales/es/devise.yml
  config/locales/es/mailers.yml
  spec/system/users_auth_spec.rb
Labels: Authentication
