Repository consuldemocracy/consuldemocracy, pull requests merged in 2022-12, with the labels that each got.

#4902 Add account permissions hint for screen reader users
  app/assets/stylesheets/account/permissions_list.scss
  app/assets/stylesheets/admin.scss
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/layout.scss
  app/components/account/permissions_list_component.html.erb
  app/components/account/permissions_list_component.rb
  app/controllers/management/users_controller.rb
  app/views/account/show.html.erb
  app/views/management/_user_permissions.html.erb
  app/views/management/document_verifications/invalid_document.html.erb
  app/views/management/document_verifications/new.html.erb
  app/views/management/document_verifications/verified.html.erb
  app/views/management/email_verifications/sent.html.erb
  app/views/management/users/new.html.erb
  app/views/management/users/show.html.erb
  app/views/verification/letter/new.html.erb
  app/views/verification/residence/new.html.erb
  config/locales/en/verification.yml
  config/locales/es/verification.yml
  spec/components/account/permissions_list_component_spec.rb
Labels: Accessibility, 2.0

#5036 Simplify locking current user when voting
  app/models/poll/answer.rb
  app/models/user.rb
Labels: Refactoring, 2.0

#5041 Respond with not found on missing tenants
  config/application.rb
  spec/system/multitenancy_spec.rb
Labels: UX, Community Interest

#5007 Allow using domains in tenants
  .rubocop.yml
  app/assets/javascripts/admin/tenants/form.js
  app/assets/javascripts/application.js
  app/assets/stylesheets/admin/budgets/form.scss
  app/assets/stylesheets/admin/tenants/form.scss
  app/assets/stylesheets/mixins/forms.scss
  app/components/admin/tenants/form_component.html.erb
  app/components/admin/tenants/form_component.rb
  app/components/admin/tenants/index_component.html.erb
  app/controllers/admin/tenants_controller.rb
  app/models/tenant.rb
  config/locales/en/activerecord.yml
  config/locales/en/admin.yml
  config/locales/es/activerecord.yml
  config/locales/es/admin.yml
  db/migrate/20221120123254_add_schema_type_to_tenants.rb
  db/schema.rb
  spec/controllers/concerns/tenant_variants_spec.rb
  spec/factories/administration.rb
  spec/factory_bot/strategy/insert.rb
  spec/models/abilities/administrator_spec.rb
  spec/models/setting_spec.rb
  spec/models/tenant_spec.rb
  spec/spec_helper.rb
  spec/system/admin/tenants_spec.rb
Labels: Community Interest

#5046 Use the tenant URL as a link to the tenant
  app/components/admin/tenants/index_component.html.erb
  spec/system/admin/tenants_spec.rb
Labels: Admin, UX, 2.0

#5056 Update consul democracy logo
  public/consul_logo.png
Labels: Maintenance, 2.0

#5053 Upgrade Ruby to version 2.7.7
  .gitlab-ci.yml
  .ruby-version
  Dockerfile
  Gemfile.lock
  README.md
  README_ES.md
Labels: Maintenance, 2.0

#5050 Make it possible to disable tenants
  .rubocop.yml
  app/assets/stylesheets/admin/budget_phases/phases.scss
  app/assets/stylesheets/admin/toggle_switch.scss
  app/components/admin/budget_phases/toggle_enabled_component.html.erb
  app/components/admin/budget_phases/toggle_enabled_component.rb
  app/components/admin/tenants/index_component.html.erb
  app/components/admin/tenants/row_component.html.erb
  app/components/admin/tenants/row_component.rb
  app/components/admin/tenants/toggle_hidden_component.html.erb
  app/components/admin/tenants/toggle_hidden_component.rb
  app/components/admin/toggle_switch_component.html.erb
  app/components/admin/toggle_switch_component.rb
  app/controllers/admin/tenants_controller.rb
  app/controllers/concerns/admin/budget_phases_actions.rb
  app/models/abilities/administrator.rb
  app/models/tenant.rb
  app/views/admin/budget_phases/toggle_enabled.js.erb
  app/views/admin/budgets_wizard/phases/toggle_enabled.js.erb
  app/views/admin/tenants/toggle_enabled.js.erb
  config/locales/en/admin.yml
  config/locales/es/admin.yml
  config/routes/admin.rb
  db/migrate/20221203140136_add_hidden_at_to_tenants.rb
  db/schema.rb
  spec/models/abilities/administrator_spec.rb
  spec/models/tenant_spec.rb
  spec/system/admin/tenants_spec.rb
Labels: Community Interest

#5048 Create an administrator in new tenant
  app/components/admin/tenants/new_component.html.erb
  app/components/admin/tenants/new_component.rb
  app/controllers/admin/tenants_controller.rb
  config/locales/en/admin.yml
  config/locales/es/admin.yml
  db/seeds.rb
  spec/system/admin/tenants_spec.rb
Labels: Community Interest, 2.0
