Repository consuldemocracy/consuldemocracy, pull requests merged in 2023-11, with the labels that each got.

#5173 Replace back link on budget results
  app/views/budgets/executions/show.html.erb
  app/views/budgets/results/show.html.erb
  app/views/budgets/stats/show.html.erb
  spec/system/budgets/executions_spec.rb
  spec/system/budgets/results_spec.rb
  spec/system/budgets/stats_spec.rb
Labels: Budgets, UX

#5319 Bump rails from 6.1.7.4 to 6.1.7.6
  Gemfile
  Gemfile.lock
Labels: dependencies, security, 2.1

#5256 ENS: Strip metadata from attachments
  Gemfile
  Gemfile.lock
  app/models/document.rb
  spec/fixtures/files/logo_with_metadata.pdf
  spec/system/documents_spec.rb
Labels: security

#5324 Clarify authentication_logs secret
  config/application.rb
  config/secrets.yml.example
Labels: security, 2.1

#5320 Filter sensitive information from airbrake parameters
  config/initializers/01_filter_parameter_logging.rb
  config/initializers/errbit.rb
  spec/airbrake_spec.rb
Labels: Bug, security, 2.1
