Repository consuldemocracy/consuldemocracy, pull requests merged in 2023-04, with the labels that each got.

#5074 Upgrade Ruby to version 3.0.6
  .gitlab-ci.yml
  .rubocop.yml
  .ruby-version
  Dockerfile
  Gemfile.lock
  README.md
  README_ES.md
  app/helpers/embed_videos_helper.rb
  app/models/legislation/process.rb
  app/models/poll/question/answer/video.rb
  app/models/progress_bar.rb
  spec/models/skip_validation_spec.rb
Labels: Maintenance

#5096 Bump Leaflet from 1.5.1 to 1.9.3
  Gemfile
  Gemfile.lock
  app/assets/javascripts/map.js
Labels: dependencies

#5107 Fix wrong investments on the map after voting
  app/assets/stylesheets/budgets/investments/my_ballot.scss
  app/components/budgets/investments/my_ballot_component.html.erb
  app/components/budgets/investments/my_ballot_component.rb
  app/controllers/budgets/ballot/lines_controller.rb
  app/views/budgets/ballot/lines/create.js.erb
  app/views/budgets/ballot/lines/destroy.js.erb
  app/views/budgets/investments/_sidebar.html.erb
  spec/factories/budgets.rb
  spec/system/budgets/ballots_spec.rb
Labels: Bug, Budgets
