Repository consuldemocracy/consuldemocracy, pull requests merged in 2023-07, with the labels that each got.

#5142 Reduce log size in development/test environments
  config/environments/development.rb
  config/environments/test.rb
Labels: Maintenance, 2.0

#5144 Fix text selection in budget header
  app/assets/stylesheets/admin/budgets_wizard/creation_timeline.scss
  app/assets/stylesheets/budgets/single_heading.scss
Labels: Bug, 2.0

#5149 Update project name
  .github/workflows/auto-author-assign.yml
  .github/workflows/kanban.yml
  CHANGELOG.md
  CONTRIBUTING.md
  CONTRIBUTING_ES.md
  Gemfile_custom
  README.md
  README_ES.md
  app/assets/images/logo_header.png
  app/assets/javascripts/custom.js
  app/assets/javascripts/dashboard_graphs.js
  app/assets/stylesheets/_consul_custom_overrides.scss
  app/assets/stylesheets/_consul_settings.scss
  app/models/custom/setting.rb
  app/models/setting.rb
  config/application.rb
  config/deploy.rb
  config/locales/en/admin.yml
  config/locales/en/general.yml
  config/locales/en/management.yml
  config/locales/en/pages.yml
  config/locales/en/seeds.yml
  config/locales/es/admin.yml
  config/locales/es/general.yml
  config/locales/es/management.yml
  config/locales/es/pages.yml
  config/locales/es/seeds.yml
  db/dev_seeds/settings.rb
  db/dev_seeds/widgets.rb
  db/migrate/20200602233844_create_shared_extensions_schema.rb
  doc/api/examples/ruby/example_1.rb
  doc/api/examples/ruby/example_2.rb
  public/maintenance.html
  spec/components/budgets/budget_component_spec.rb
  spec/components/budgets/phases_component_spec.rb
  spec/custom_spec_helper.rb
  spec/models/budget/phase_spec.rb
  spec/models/budget_spec.rb
  spec/models/setting_spec.rb
  spec/models/widget/card_spec.rb
  spec/system/admin/budget_phases_spec.rb
  spec/system/admin/budgets_spec.rb
  spec/system/admin/budgets_wizard/budgets_spec.rb
  spec/system/admin/translatable_spec.rb
  spec/system/localization_spec.rb
  spec/system/management/budget_investments_spec.rb
Labels: Maintenance, 2.0

#5150 Fix source string typo
  config/locales/en/mailers.yml
Labels: 2.0

#5033 Release version 2.0.0
  CHANGELOG.md
  app/controllers/installation_controller.rb
  lib/tasks/consul.rake
Labels: Maintenance, 2.0
