Repository consuldemocracy/consuldemocracy, pull requests merged in 2023-06, with the labels that each got.

#5123 Fix cached tenant secrets when running tests
  app/models/tenant.rb
Labels: Flaky bug

#5121 Allow to change the application name for deployments
  config/deploy-secrets.yml.example
  config/deploy.rb
Labels: Customization

#5104 Disable the create booths button when the polls function is disabled
  app/components/admin/budgets/actions_component.rb
  config/locales/en/admin.yml
  config/locales/es/admin.yml
  spec/components/admin/budgets/actions_component_spec.rb
Labels: Budgets

#5122 Remove metadata from images
  app/models/image.rb
  spec/fixtures/files/logo_header_with_metadata.jpg
  spec/system/images_spec.rb
Labels: security

#5134 Update search dictionaries
  lib/search_dictionary_selector.rb
Labels: Translations

#5098 Open marker popups when navigating with the keyboard
  app/assets/javascripts/map.js
  app/components/budgets/investments/map_component.rb
  app/components/budgets/map_component.rb
  app/controllers/budgets/investments_controller.rb
  app/models/abilities/everyone.rb
  app/models/concerns/globalizable.rb
  app/models/map_location.rb
  config/routes/budget.rb
  spec/models/concerns/globalizable.rb
Labels: Bug, Accessibility

#5147 Bump selenium-webdriver from 3.142 to 4.0.0
  Gemfile
  Gemfile.lock
  spec/rails_helper.rb
Labels: dependencies

#5136 Render markdown tables in legislation draft
  app/assets/stylesheets/legislation_process.scss
  app/helpers/application_helper.rb
  app/models/legislation/draft_version.rb
  lib/admin_legislation_sanitizer.rb
  lib/markdown_converter.rb
  spec/factories/legislations.rb
  spec/lib/admin_legislation_sanitizer_spec.rb
  spec/models/legislation/draft_version_spec.rb
  spec/system/legislation/draft_versions_spec.rb
Labels: 2.0

#5145 Enable mousewheel when focusing on the map
  app/assets/javascripts/map.js
Labels: UX, 2.0

#5106 Render background images with brackets in their names
  app/components/budgets/budget_component.html.erb
  app/components/budgets/budget_component.rb
  app/helpers/images_helper.rb
  app/views/dashboard/poster/index.html.erb
  app/views/dashboard/poster/index.pdf.erb
  app/views/layouts/devise.html.erb
  spec/components/budgets/budget_component_spec.rb
  spec/factories/budgets.rb
  spec/factories/files.rb
  spec/fixtures/files/clippy(with_brackets).jpg
  spec/fixtures/files/clippy_with_'quotes'.jpg
  spec/helpers/images_helper_spec.rb
  spec/models/budget_spec.rb
  spec/models/image_spec.rb
Labels: Bug, 2.0

#5146 Restart DelayedJob workers after they crash
  config/deploy.rb
  config/schedule.rb
Labels: Maintenance, 2.0
