Repository consuldemocracy/consuldemocracy, pull requests merged in 2023-10, with the labels that each got.

#5250 Add new content block `footer_legal` to Footer
  app/assets/stylesheets/layout.scss
  app/components/layout/footer_component.html.erb
  app/components/layout/footer_component.rb
  app/models/site_customization/content_block.rb
  config/locales/en/admin.yml
  config/locales/es/admin.yml
  spec/system/site_customization/content_blocks_spec.rb
Labels: 2.1

#5118 Allow undoing "like/unlike" votes
  app/assets/stylesheets/in_favor_against.scss
  app/assets/stylesheets/layout.scss
  app/components/comments/votes_component.html.erb
  app/components/comments/votes_component.rb
  app/components/legislation/proposals/votes_component.rb
  app/components/shared/in_favor_against_component.html.erb
  app/components/shared/in_favor_against_component.rb
  app/components/shared/vote_button_component.html.erb
  app/components/shared/vote_button_component.rb
  app/controllers/comments/votes_controller.rb
  app/controllers/comments_controller.rb
  app/controllers/debates/votes_controller.rb
  app/controllers/debates_controller.rb
  app/controllers/legislation/proposals/votes_controller.rb
  app/controllers/legislation/proposals_controller.rb
  app/models/abilities/common.rb
  app/models/budget/investment.rb
  app/models/legislation/proposal.rb
  app/views/comments/_comment.html.erb
  app/views/comments/_votes.html.erb
  app/views/comments/vote.js.erb
  app/views/comments/votes/show.js.erb
  app/views/debates/_debate.html.erb
  app/views/debates/_votes.html.erb
  app/views/debates/show.html.erb
  app/views/debates/vote.js.erb
  app/views/debates/votes/show.js.erb
  app/views/legislation/annotations/_comments.html.erb
  app/views/legislation/proposals/votes/show.js.erb
  config/routes/comment.rb
  config/routes/debate.rb
  config/routes/legislation.rb
  spec/components/comments/votes_component_spec.rb
  spec/components/debates/votes_component_spec.rb
  spec/components/legislation/proposals/votes_component_spec.rb
  spec/components/shared/in_favor_against_component_spec.rb
  spec/controllers/comments/votes_controller_spec.rb
  spec/controllers/debates/votes_controller_spec.rb
  spec/controllers/debates_controller_spec.rb
  spec/controllers/legislation/proposals/votes_controller_spec.rb
  spec/models/abilities/administrator_spec.rb
  spec/models/abilities/common_spec.rb
  spec/models/abilities/moderator_spec.rb
  spec/models/abilities/organization_spec.rb
  spec/routing/polymorphic_routes_spec.rb
  spec/system/comments/budget_investments_spec.rb
  spec/system/comments/debates_spec.rb
  spec/system/comments/legislation_annotations_spec.rb
  spec/system/comments/legislation_questions_spec.rb
  spec/system/comments/polls_spec.rb
  spec/system/comments/proposals_spec.rb
  spec/system/comments/topics_spec.rb
  spec/system/votes_spec.rb
Labels: UX, Accessibility, 2.1

#5255 Increase links and buttons contrast on focus
  app/assets/stylesheets/_consul_settings.scss
  app/assets/stylesheets/admin/budgets_wizard/headings/group_switcher.scss
  app/assets/stylesheets/admin/menu.scss
  app/assets/stylesheets/budgets/ballot/investment.scss
  app/assets/stylesheets/budgets/groups_and_headings.scss
  app/assets/stylesheets/budgets/phases.scss
  app/assets/stylesheets/layout.scss
  app/assets/stylesheets/layout/locale_switcher.scss
  app/assets/stylesheets/legislation.scss
  app/assets/stylesheets/mixins/links.scss
  app/assets/stylesheets/mixins/sdg.scss
  app/assets/stylesheets/mixins/uploads.scss
  app/assets/stylesheets/participation.scss
  app/assets/stylesheets/proposals/geozones.scss
  app/assets/stylesheets/sdg/help.scss
  app/assets/stylesheets/sdg/related_list_selector.scss
  app/components/proposals/geozones_component.html.erb
  app/views/budgets/executions/_investments.html.erb
  app/views/shared/_recommended_index.html.erb
Labels: Accessibility

#5257 Increase contrast in colors used in "My account"
  app/assets/stylesheets/_consul_settings.scss
  app/assets/stylesheets/admin.scss
  app/assets/stylesheets/layout.scss
  app/assets/stylesheets/layout/admin_header.scss
  app/assets/stylesheets/map_location.scss
  app/components/shared/avatar_component.html.erb
  app/components/shared/avatar_component.rb
  app/views/account/show.html.erb
  app/views/comments/_comment.html.erb
  app/views/communities/_participant.html.erb
  app/views/shared/_author_info.html.erb
  app/views/users/show.html.erb
Labels: Accessibility

#5168 Do not validate the attachment when updating the name
  app/models/concerns/attachable.rb
  spec/models/attachable_spec.rb
Labels: Bug, 2.1

#5158 Depend on a specific version of Node.js
  .github/workflows/tests.yml
  .node-version
  .nvmrc
  Dockerfile
  README.md
  README_ES.md
  config/deploy.rb
Labels: Documentation, Maintenance, 2.1

#5159 Allow adding Node packages as dependencies
  .dockerignore
  .github/dependabot.yml
  .github/workflows/tests.yml
  .gitignore
  .gitlab-ci.yml
  Capfile
  Dockerfile
  Gemfile
  Gemfile.lock
  README.md
  README_ES.md
  app/assets/javascripts/application.js
  app/assets/stylesheets/application.scss
  bin/setup
  config/application.rb
  package-lock.json
  package.json
Labels: Maintenance, 2.1

#5301 Update Node.js from 18.18.0 to 18.18.2
  .node-version
  README.md
  README_ES.md
Labels: dependencies, javascript

#5283 Allow links in forms to open in new tabs
  app/components/admin/site_customization/pages/index_component.html.erb
  app/components/budgets/investments/form_component.html.erb
  app/components/debates/form_component.html.erb
  app/components/debates/new_component.html.erb
  app/components/debates/new_component.rb
  app/components/layout/footer_component.html.erb
  app/components/proposals/form_component.html.erb
  app/components/proposals/new_component.html.erb
  app/components/proposals/new_component.rb
  app/components/sdg/related_list_selector_component.html.erb
  app/components/sdg/related_list_selector_component.rb
  app/components/shared/agree_with_terms_of_service_field_component.html.erb
  app/components/shared/agree_with_terms_of_service_field_component.rb
  app/helpers/application_helper.rb
  app/views/legislation/proposals/_form.html.erb
  app/views/organizations/registrations/new.html.erb
  app/views/users/registrations/new.html.erb
  app/views/verification/residence/new.html.erb
  config/locales/en/devise_views.yml
  config/locales/en/general.yml
  config/locales/en/verification.yml
  config/locales/es/devise_views.yml
  config/locales/es/general.yml
  config/locales/es/verification.yml
  lib/consul_form_builder.rb
  spec/components/shared/agree_with_terms_of_service_field_component_spec.rb
  spec/lib/consul_form_builder_spec.rb
  spec/system/verification/residence_spec.rb
Labels: UX, 2.1

#5282 Open links in the same tab unless necessary
  app/components/admin/machine_learning/setting_component.html.erb
  app/components/admin/machine_learning/settings_component.html.erb
  app/components/admin/site_customization/pages/index_component.html.erb
  app/components/admin/widget/cards/row_component.html.erb
  app/components/layout/footer_component.html.erb
  app/components/layout/footer_component.rb
  app/components/layout/social_component.html.erb
  app/components/layout/social_component.rb
  app/components/polls/questions/read_more_component.html.erb
  app/helpers/mailer_helper.rb
  app/helpers/text_with_links_helper.rb
  app/views/admin/dashboard/administrator_tasks/_form.html.erb
  app/views/admin/milestones/_milestones.html.erb
  app/views/admin/poll/polls/_questions.html.erb
  app/views/admin/users/_users.html.erb
  app/views/admin/valuators/_user_row.html.erb
  app/views/dashboard/_proposed_action.html.erb
  app/views/dashboard/actions/new_request.html.erb
  app/views/dashboard/community.html.erb
  app/views/dashboard/mailer/forward.html.erb
  app/views/dashboard/mailer/new_actions_notification_on_create.html.erb
  app/views/dashboard/mailer/new_actions_notification_on_published.html.erb
  app/views/dashboard/polls/_poll.html.erb
  app/views/dashboard/polls/index.html.erb
  app/views/dashboard/show.html.erb
  app/views/layouts/_mailer_header.html.erb
  app/views/layouts/dashboard/_proposal_header.html.erb
  app/views/layouts/dashboard/_proposal_totals.html.erb
  app/views/mailer/direct_message_for_receiver.html.erb
  app/views/management/document_verifications/invalid_document.html.erb
  app/views/moderation/budgets/investments/index.html.erb
  app/views/moderation/comments/index.html.erb
  app/views/moderation/debates/index.html.erb
  app/views/moderation/proposal_notifications/index.html.erb
  app/views/moderation/proposals/index.html.erb
  app/views/polls/_gallery.html.erb
  config/locales/en/general.yml
  config/locales/es/general.yml
  lib/markdown_converter.rb
  spec/components/layout/footer_component_spec.rb
  spec/components/shared/agree_with_terms_of_service_field_component_spec.rb
  spec/models/legislation/draft_version_spec.rb
  spec/system/admin/users_spec.rb
  spec/system/comments/budget_investments_spec.rb
  spec/system/comments/budget_investments_valuation_spec.rb
  spec/system/comments/debates_spec.rb
  spec/system/comments/legislation_annotations_spec.rb
  spec/system/comments/legislation_questions_spec.rb
  spec/system/comments/polls_spec.rb
  spec/system/comments/proposals_spec.rb
  spec/system/comments/topics_spec.rb
  spec/system/dashboard/polls_spec.rb
  spec/system/proposals_spec.rb
Labels: UX, Accessibility, 2.1

#5163 ENS: Enable password complexity
  app/assets/javascripts/managers.js
  app/models/user.rb
  app/views/management/account/edit_password_manually.html.erb
  config/initializers/devise-security.rb
  config/secrets.yml.example
  spec/models/user_spec.rb
  spec/system/users_auth_spec.rb
Labels: security

#5273 ENS: Enable lockable devise module
  app/models/user.rb
  config/application.rb
  config/environments/test.rb
  config/initializers/devise.rb
  config/secrets.yml.example
  db/migrate/20231009073912_add_lockable_to_devise.rb
  db/schema.rb
  spec/controllers/users/sessions_controller_spec.rb
  spec/models/user_spec.rb
Labels: security
