Repository consuldemocracy/consuldemocracy, pull requests merged in 2023-02, with the labels that each got.

#5076 Allow to add custom mailers
  app/mailers/custom/.keep
  config/application.rb
Labels: Customization

#5058 Change poll button if results or stats are enabled
  app/helpers/polls_helper.rb
  app/views/polls/_poll_group.html.erb
  spec/system/polls/polls_spec.rb
Labels: Polls

#5061 Show published budgets in the valuation panel
  app/components/valuation/budgets/index_component.html.erb
  app/components/valuation/budgets/index_component.rb
  app/components/valuation/budgets/row_component.html.erb
  app/components/valuation/budgets/row_component.rb
  app/controllers/valuation/budget_investments_controller.rb
  app/controllers/valuation/budgets_controller.rb
  app/views/valuation/budgets/index.html.erb
  spec/components/valuation/budgets/row_component_spec.rb
  spec/system/admin/budget_investments_spec.rb
  spec/system/valuation/budget_investments_spec.rb
  spec/system/valuation/budgets_spec.rb
Labels: Bug

#4992 Fix image size on proposals list
  app/assets/stylesheets/participation.scss
Labels: Bug, Proposals, UX

#5072 Fix menu on "wide" small screens
  app/assets/stylesheets/foundation_and_overrides.scss
  app/assets/stylesheets/layout.scss
  app/assets/stylesheets/layout/account_menu.scss
  app/assets/stylesheets/layout/admin_header.scss
  app/assets/stylesheets/layout/remote_translations_button.scss
  app/assets/stylesheets/layout/subnavigation.scss
  app/assets/stylesheets/mixins/colors.scss
  app/components/layout/account_menu_component.html.erb
  app/components/layout/admin_header_component.html.erb
  app/components/layout/remote_translations_button_component.html.erb
  app/components/layout/remote_translations_button_component.rb
  app/components/layout/responsive_menu_component.html.erb
  app/components/layout/responsive_menu_component.rb
  app/helpers/remote_translations_helper.rb
  app/views/layouts/_header.html.erb
  app/views/shared/_locale_switcher.html.erb
  app/views/shared/_top_links.html.erb
  spec/components/layout/remote_translations_button_component_spec.rb
  spec/support/common_actions/users.rb
  spec/system/remote_translations_spec.rb
Labels: Bug, UX, Refactoring, Accessibility

#5073 Fix crash translating an already translated text
  app/components/layout/remote_translations_button_component.html.erb
  app/components/layout/remote_translations_button_component.rb
  app/controllers/concerns/remotely_translatable.rb
  app/controllers/remote_translations_controller.rb
  app/models/remote_translation.rb
  spec/components/layout/remote_translations_button_component_spec.rb
  spec/shared/system/remotely_translatable.rb
Labels: Bug, Refactoring, Translations

#5024 Always show poll officer menu to officers
  app/components/layout/admin_login_items_component.rb
  spec/components/layout/admin_login_items_component_spec.rb
  spec/system/admin_spec.rb
  spec/system/moderation_spec.rb
  spec/system/officing_spec.rb
  spec/system/sdg_management/sdg_spec.rb
  spec/system/sdg_management_spec.rb
  spec/system/valuation/budget_investments_spec.rb
  spec/system/valuation_spec.rb
Labels: Bug, Polls

#5077 Don't cache related actions in investments view
  app/views/budgets/investments/_investment_show.html.erb
Labels: Bug

#4985 Show admin heading stats for the current budget
  app/components/admin/stats/budget_balloting_component.html.erb
  app/components/admin/stats/budget_balloting_component.rb
  app/components/admin/stats/budget_supporting_component.html.erb
  app/components/admin/stats/budget_supporting_component.rb
  app/controllers/admin/stats_controller.rb
  app/models/budget/ballot/line.rb
  app/models/budget/stats.rb
  app/views/admin/stats/budget_balloting.html.erb
  app/views/admin/stats/budget_supporting.html.erb
  db/migrate/20230206141152_remove_balloted_heading_id_from_users.rb
  db/schema.rb
  spec/components/admin/stats/budget_balloting_component_spec.rb
  spec/components/admin/stats/budget_supporting_component_spec.rb
  spec/models/budget/ballot/line_spec.rb
  spec/system/admin/stats_spec.rb
Labels: Bug, Admin, Budgets

#5082 Show valuator group investments to group valuators
  app/controllers/valuation/budget_investments_controller.rb
  app/models/budget/investment.rb
  spec/components/valuation/budgets/row_component_spec.rb
  spec/models/budget/investment_spec.rb
Labels: Bug, Coadministration

#5083 Fix flaky spec in budget supports admin stats
  spec/system/admin/stats_spec.rb
Labels: Flaky spec

#5084 Remove duplicate keys
  app/views/admin/debates/index.html.erb
  app/views/admin/legislation/proposals/_proposals.html.erb
  app/views/admin/proposals/index.html.erb
  config/locales/en/admin.yml
  config/locales/en/images.yml
Labels: Bug, Maintenance

#4997 Add description to Legislation questions
  app/assets/stylesheets/legislation_process.scss
  app/models/legislation/question.rb
  app/views/admin/legislation/questions/_form.html.erb
  app/views/legislation/questions/show.html.erb
  db/migrate/20220924224924_add_description_to_legislation_question_translations.rb
  db/schema.rb
  spec/system/admin/legislation/questions_spec.rb
  spec/system/legislation/questions_spec.rb
Labels: Legislation

#4900 Do not show money with hidden money
  app/components/budgets/investments/ballot_component.html.erb
  app/views/budgets/investments/_header.html.erb
  spec/components/budgets/investments/ballot_component_spec.rb
  spec/system/budgets/investments_spec.rb
Labels: Bug, Budgets
