Repository consuldemocracy/consuldemocracy, pull requests merged in 2023-05, with the labels that each got.

#5108 Simplify the code rendering the map
  app/assets/javascripts/map.js
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/layout.scss
  app/assets/stylesheets/map_location.scss
  app/components/budgets/investments/form_component.html.erb
  app/components/budgets/map_component.html.erb
  app/components/proposals/form_component.html.erb
  app/components/shared/map_location_component.html.erb
  app/components/shared/map_location_component.rb
  app/controllers/budgets/investments_controller.rb
  app/controllers/concerns/commentable_actions.rb
  app/controllers/legislation/proposals_controller.rb
  app/controllers/proposals_controller.rb
  app/helpers/map_locations_helper.rb
  app/models/abilities/everyone.rb
  app/models/map_location.rb
  app/views/budgets/investments/_investment_detail.html.erb
  app/views/budgets/investments/_map.html.erb
  app/views/legislation/proposals/map.html.erb
  app/views/map_locations/_form_fields.html.erb
  app/views/proposals/_info.html.erb
  app/views/proposals/map.html.erb
  app/views/shared/_map.html.erb
  config/locales/en/budgets.yml
  config/locales/es/budgets.yml
  config/routes/legislation.rb
Labels: Refactoring

#5113 Show email digest only if proposals are enabled
  app/views/account/show.html.erb
  spec/system/account_spec.rb
Labels: Proposals, UX

#5114 Bump wkhtmltopdf-binary from 0.12.6.5 to 0.12.6.6
  Gemfile.lock
Labels: dependencies

#4854 Show account activation status for each user in the admin section
  app/views/admin/users/_users.html.erb
  config/locales/en/admin.yml
  config/locales/es/admin.yml
  spec/system/admin/users_spec.rb
Labels: Admin
