Repository consuldemocracy/consuldemocracy, pull requests merged in 2023-03, with the labels that each got.

#4983 GitHub Workflows security hardening
  .github/workflows/kanban.yml
Labels: Maintenance

#5087 Clean up doc folder
  doc/README.md
  doc/api/api_en.md
  doc/api/api_es.md
  doc/api/examples/ruby/example_1.rb
  doc/api/examples/ruby/example_2.rb
  doc/imgs/button_global_configuration.png
  doc/imgs/button_statistics.png
  doc/imgs/graphiql.png
  doc/imgs/graphql-postman-get.png
  doc/imgs/graphql-postman-post-body.png
  doc/imgs/graphql-postman-post-headers.png
  doc/imgs/icon_banners.png
  doc/imgs/icon_categories.png
  doc/imgs/icon_customize_site.png
  doc/imgs/icon_moderated_content.png
  doc/imgs/icon_participatory_budgeting.png
  doc/imgs/icon_polls.png
  doc/imgs/icon_profiles.png
  doc/imgs/panel_administration.png
  doc/imgs/panel_management.png
  doc/imgs/panel_moderation.png
  doc/imgs/user_preverification.png
  doc/imgs/user_registration.png
  doc/imgs/user_verification.png
Labels: Bug, Documentation, Maintenance

#5054 Run test coverage just on the master branch
  .github/workflows/tests.yml
  spec/rails_helper.rb
Labels: Maintenance

#5093 Bump erb_lint from 0.0.37 to 0.3.1
  .erb-lint.yml
  Gemfile
  Gemfile.lock
Labels: dependencies

#5097 Disable scroll wheel for zooming in favor of map zoom buttons
  app/assets/javascripts/map.js
Labels: Bug, UX
