Repository consuldemocracy/consuldemocracy, pull requests merged in 2023-09, with the labels that each got.

#5231 Update Rubocop version used in Code Climate
  .codeclimate.yml
Labels: Maintenance

#5236 Revert "Bump pg from 1.4.3 to 1.5.4"
  Gemfile
  Gemfile.lock
Labels: dependencies

#5105 Rotate logs on production
  config/environments/production.rb
  config/environments/staging.rb
Labels: Release notes

#5240 Apply Style/InvertibleUnlessCondition rule to ERB files
  app/views/shared/_header.html.erb
Labels: Rubocop

#5152 Remove alert for Internet Explorer 8 and below
  app/assets/javascripts/application.js
  app/assets/javascripts/ie_alert.js
  app/assets/stylesheets/layout.scss
  app/views/layouts/application.html.erb
  config/locales/en/general.yml
  config/locales/es/general.yml
  spec/spec_helper.rb
  spec/system/home_spec.rb
Labels: Maintenance

#5151 Upgrade to Rails 6.1
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/controllers/account_controller.rb
  app/controllers/organizations/registrations_controller.rb
  app/controllers/pages_controller.rb
  bin/setup
  config.ru
  config/application.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/staging.rb
  config/environments/test.rb
  config/initializers/acts_as_taggable_on.rb
  config/initializers/backtrace_silencers.rb
  config/initializers/filter_parameter_logging.rb
  config/initializers/permissions_policy.rb
  config/initializers/wicked_pdf.rb
  db/migrate/20210924190647_add_service_name_to_active_storage_blobs.active_storage.rb
  db/migrate/20210924190648_create_active_storage_variant_records.active_storage.rb
  db/schema.rb
  spec/rails_helper.rb
  spec/shared/system/relationable.rb
  spec/views/welcome/index.html.erb_spec.rb
Labels: dependencies, Release notes, Maintenance

#5157 Upgrade Ruby to version 3.1.4
  .gitlab-ci.yml
  .rubocop.yml
  .ruby-version
  Dockerfile
  Gemfile.lock
  README.md
  README_ES.md
  app/controllers/stats_controller.rb
  app/graphql/types/base_object.rb
  app/helpers/globalize_helper.rb
  app/helpers/translatable_form_helper.rb
  app/mailers/mailer.rb
  app/models/budget/stats.rb
  app/models/poll/stats.rb
  app/models/sdg/process_enabled.rb
  app/models/tenant.rb
  config/deploy.rb
  config/puma/defaults.rb
  lib/remote_translations/microsoft/available_locales.rb
  spec/sessions_helper.rb
Labels: Release notes, Maintenance

#5235 Update gem dependencies once a month
  .github/dependabot.yml
Labels: Maintenance

#5232 Make model concerns customization easier
  app/models/custom/concerns/.keep
  config/application.rb
Labels: Customization, 2.1

#5242 Don't depend on the "Help" link in tests
  spec/shared/system/mappable.rb
  spec/system/legislation/draft_versions_spec.rb
  spec/system/proposals_spec.rb
Labels: Customization

#5258 Update bash script to run Knapsack Pro
  bin/knapsack_pro_rspec
Labels: Bug, dependencies
