Repository consuldemocracy/consuldemocracy, pull requests merged in 2024-03, with the labels that each got.

#5407 Update checkout action to version 3
  .github/workflows/db_schema.yml
  .github/workflows/docker.yml
  .github/workflows/linters.yml
  .github/workflows/tests.yml
Labels: Maintenance

#5411 Update upload artifact action to version 3
  .github/workflows/tests.yml
Labels: Maintenance

#5415 Update checkout action to version 4
  .github/workflows/db_schema.yml
  .github/workflows/docker.yml
  .github/workflows/linters.yml
  .github/workflows/tests.yml
Labels: Maintenance

#5419 Update setup-node action to version 4
  .github/workflows/tests.yml
Labels: Maintenance

#5420 Update upload artifact action to version 4
  .github/workflows/tests.yml
Labels: Maintenance

#5403 Add missing Spanish translations
  config/locales/es/responders.yml
Labels: Bug, Translations

#5397 Update Code Climate Rubocop version
  .codeclimate.yml
Labels: Maintenance, 2.1.1

#5426 Fix invalid HTML in comment votes
  app/assets/stylesheets/layout.scss
  app/components/comments/votes_component.html.erb
  spec/components/comments/votes_component_spec.rb
Labels: Bug, Accessibility, 2.1.1

#5431 Update Code Climate Rubocop version
  .codeclimate.yml
Labels: Maintenance

#5422 Prevent "Unable to autoload constant" error in tests
  spec/system/admin/homepage/homepage_spec.rb
  spec/system/admin/widgets/cards_spec.rb
  spec/system/polls/polls_spec.rb
Labels: Flaky spec, 2.1.1

#5395 Fix link to debates help
  app/components/debates/new_component.html.erb
  spec/components/debates/new_component_spec.rb
  spec/components/proposals/new_component_spec.rb
Labels: Bug, UX

#5389 Allow whitespace between square brackets in GeoJSON polygons
  app/models/geozone.rb
  spec/models/geozone_spec.rb
Labels: Bug, 2.1.1

#5421 Add rubocop rules affecting Rails 6.1
  .rubocop.yml
  app/models/concerns/sdg/relatable.rb
  app/models/poll/question/answer.rb
Labels: Linters, 2.1.1

#5432 Sanitize the output of a dummy component class
  spec/components/application_component_spec.rb
Labels: Specs, 2.1.1

#5428 Release version 2.1.1
  CHANGELOG.md
  app/controllers/installation_controller.rb
Labels: Maintenance, 2.1.1

#5390 Geozone Admin maps
  app/components/admin/geozones/index_component.html.erb
  app/components/admin/geozones/index_component.rb
  config/locales/en/admin.yml
  config/locales/es/admin.yml
  spec/system/admin/geozones_spec.rb
Labels: Admin

#5398 Update badges in README files
  README.md
  README_ES.md
Labels: Documentation

#5276 Allow sorting homepage cards
  app/components/admin/widget/cards/edit_component.rb
  app/components/admin/widget/cards/new_component.rb
  app/components/admin/widget/cards/row_component.html.erb
  app/components/admin/widget/cards/row_component.rb
  app/components/admin/widget/cards/table_component.html.erb
  app/components/admin/widget/cards/table_component.rb
  app/components/sdg/goals/index_component.html.erb
  app/controllers/concerns/admin/widget/cards_actions.rb
  app/controllers/pages_controller.rb
  app/models/widget/card.rb
  app/views/admin/widget/cards/_form.html.erb
  config/locales/en/activerecord.yml
  config/locales/en/admin.yml
  config/locales/es/activerecord.yml
  config/locales/es/admin.yml
  db/migrate/20231009143355_add_order_to_widget_cards.rb
  db/schema.rb
  spec/components/sdg/goals/index_component_spec.rb
  spec/models/widget/card_spec.rb
  spec/system/admin/widgets/cards_spec.rb
  spec/system/home_spec.rb
  spec/system/sdg_management/homepage_spec.rb
  spec/system/site_customization/custom_pages_spec.rb
Labels: Admin

#5440 Remove link to gitter chat
  README.md
  README_ES.md
Labels: Documentation, Maintenance

#5442 Update code of conduct contact address
  CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT_ES.md
Labels: Maintenance

#5424 Bump pg from 1.4.3 to 1.4.6
  Gemfile
  Gemfile.lock
Labels: dependencies

#5369 Make comments specs faster
  app/components/comments/form_component.html.erb
  app/components/comments/form_component.rb
  app/components/shared/comments_component.html.erb
  app/components/shared/comments_component.rb
  app/helpers/comments_helper.rb
  app/views/budgets/investments/show.html.erb
  app/views/comments/_comment.html.erb
  app/views/comments/_comment_tree.html.erb
  app/views/comments/_form.html.erb
  app/views/legislation/annotations/show.html.erb
  app/views/legislation/questions/show.html.erb
  app/views/valuation/budget_investments/_valuation_comments.html.erb
  spec/components/comments/form_component_spec.rb
  spec/factories/classifications.rb
  spec/factories/comments.rb
  spec/factories/polls.rb
  spec/system/comments/budget_investments_spec.rb
  spec/system/comments/budget_investments_valuation_spec.rb
  spec/system/comments/legislation_annotations_spec.rb
  spec/system/comments/legislation_questions_spec.rb
  spec/system/comments/poll_questions_spec.rb
  spec/system/comments/polls_spec.rb
  spec/system/comments/proposals_spec.rb
  spec/system/comments/topics_spec.rb
  spec/system/comments_spec.rb
  spec/system/legislation/questions_spec.rb
Labels: Specs

#5452 Bump ahoy_matey from 4.2.1 to 5.0.2
  Gemfile
  Gemfile.lock
Labels: dependencies

#5455 Change the English translation of check ballot to avoid confusion
  config/locales/en/budgets.yml
  spec/system/budgets/ballots_spec.rb
  spec/system/budgets/investments_spec.rb
Labels: UX
