Repository consuldemocracy/consuldemocracy, pull requests merged in 2024-01, with the labels that each got.

#5348 Rename tenant's storage folder when modifying the schema
  app/models/tenant.rb
  spec/models/tenant_spec.rb
Labels: Bug, 2.1

#5148 Order expired polls by ends date
  app/models/poll.rb
  spec/models/poll/poll_spec.rb
  spec/system/polls/polls_spec.rb
Labels: Polls

#5368 Update content block field info in heading form
  config/locales/en/admin.yml
  config/locales/es/admin.yml
Labels: Bug, 2.1

#5325 Refactor settings related code
  app/assets/stylesheets/admin/settings/featured_settings_table.scss
  app/assets/stylesheets/admin/settings/table.scss
  app/components/admin/settings/configuration_tab_component.html.erb
  app/components/admin/settings/configuration_tab_component.rb
  app/components/admin/settings/content_types_form_component.html.erb
  app/components/admin/settings/content_types_form_component.rb
  app/components/admin/settings/featured_settings_form_component.html.erb
  app/components/admin/settings/features_tab_component.html.erb
  app/components/admin/settings/features_tab_component.rb
  app/components/admin/settings/images_and_documents_tab_component.html.erb
  app/components/admin/settings/images_and_documents_tab_component.rb
  app/components/admin/settings/map_form_component.html.erb
  app/components/admin/settings/map_form_component.rb
  app/components/admin/settings/map_tab_component.html.erb
  app/components/admin/settings/map_tab_component.rb
  app/components/admin/settings/participation_processes_tab_component.html.erb
  app/components/admin/settings/participation_processes_tab_component.rb
  app/components/admin/settings/proposals_dashboard_tab_component.html.erb
  app/components/admin/settings/proposals_dashboard_tab_component.rb
  app/components/admin/settings/remote_census_tab_component.html.erb
  app/components/admin/settings/remote_census_tab_component.rb
  app/components/admin/settings/row_component.html.erb
  app/components/admin/settings/row_component.rb
  app/components/admin/settings/sdg_configuration_tab_component.html.erb
  app/components/admin/settings/sdg_configuration_tab_component.rb
  app/components/admin/settings/table_component.html.erb
  app/components/admin/settings/table_component.rb
  app/components/admin/settings/text_form_component.html.erb
  app/components/admin/settings/text_form_component.rb
  app/controllers/admin/settings_controller.rb
  app/controllers/admin/site_customization/content_blocks_controller.rb
  app/helpers/settings_helper.rb
  app/models/setting.rb
  app/views/admin/settings/_configuration_settings_tab.html.erb
  app/views/admin/settings/_featured_settings_table.html.erb
  app/views/admin/settings/_features_tab.html.erb
  app/views/admin/settings/_images_and_documents_tab.html.erb
  app/views/admin/settings/_map_configuration_tab.html.erb
  app/views/admin/settings/_participation_processes_tab.html.erb
  app/views/admin/settings/_proposals_dashboard.html.erb
  app/views/admin/settings/_remote_census_configuration_tab.html.erb
  app/views/admin/settings/_sdg_configuration_tab.html.erb
  app/views/admin/settings/_settings_table.html.erb
  app/views/admin/settings/index.html.erb
  app/views/admin/settings/update.js.erb
  app/views/admin/site_customization/content_blocks/index.html.erb
  app/views/layouts/_no_script.html.erb
  app/views/layouts/admin.html.erb
  spec/components/admin/settings/table_component_spec.rb
  spec/helpers/settings_helper_spec.rb
  spec/models/setting_spec.rb
  spec/system/admin/settings_spec.rb
Labels: Release notes, 2.1

#5116 Add map markers clustering feature
  Gemfile
  Gemfile.lock
  app/assets/javascripts/application.js
  app/assets/javascripts/map.js
  app/assets/stylesheets/application.scss
  app/components/admin/settings/map_tab_component.html.erb
  app/components/shared/map_location_component.rb
  app/helpers/settings_helper.rb
  app/models/setting.rb
  config/locales/en/settings.yml
  config/locales/es/settings.yml
  db/dev_seeds/budgets.rb
  package-lock.json
  package.json
  spec/factories/administration.rb
  spec/factories/budgets.rb
  spec/helpers/settings_helper_spec.rb
  spec/system/budgets/budgets_spec.rb
  spec/system/budgets/investments_spec.rb
Labels: 2.1
