Repository consuldemocracy/consuldemocracy, pull requests merged in 2024-05, with the labels that each got.

#5508 Update initializer reference in rubocop config file
  .rubocop.yml
Labels: Maintenance

#5503 Improve stats graphs in admin section
  app/assets/javascripts/stats.js
  app/assets/stylesheets/admin/stats/event_links.scss
  app/components/admin/settings/features_tab_component.rb
  app/components/admin/stats/budget_supporting_component.html.erb
  app/components/admin/stats/budget_supporting_component.rb
  app/components/admin/stats/chart_component.html.erb
  app/components/admin/stats/chart_component.rb
  app/components/admin/stats/event_links_component.html.erb
  app/components/admin/stats/event_links_component.rb
  app/components/admin/stats/global_chart_component.html.erb
  app/components/admin/stats/global_chart_component.rb
  app/components/admin/stats/sdg_component.html.erb
  app/controllers/admin/api/stats_controller.rb
  app/controllers/admin/stats_controller.rb
  app/controllers/application_controller.rb
  app/controllers/concerns/commentable_actions.rb
  app/controllers/debates_controller.rb
  app/controllers/legislation/annotations_controller.rb
  app/controllers/legislation/answers_controller.rb
  app/controllers/management/proposals_controller.rb
  app/controllers/stats_controller.rb
  app/controllers/verification/sms_controller.rb
  app/helpers/stats_helper.rb
  app/models/ahoy/chart.rb
  app/models/ahoy/data_source.rb
  app/models/campaign.rb
  app/models/setting.rb
  app/models/visit.rb
  app/views/admin/stats/_graph.html.erb
  app/views/admin/stats/direct_messages.html.erb
  app/views/admin/stats/graph.html.erb
  app/views/admin/stats/polls.html.erb
  app/views/admin/stats/proposal_notifications.html.erb
  app/views/admin/stats/show.html.erb
  app/views/stats/index.html.erb
  app/views/stats/index.json.erb
  config/locales/en/admin.yml
  config/locales/en/general.yml
  config/locales/en/settings.yml
  config/locales/es/admin.yml
  config/locales/es/general.yml
  config/locales/es/settings.yml
  config/routes.rb
  config/routes/admin.rb
  spec/components/admin/stats/chart_component_spec.rb
  spec/components/admin/stats/event_links_component_spec.rb
  spec/components/admin/stats/global_chart_component_spec.rb
  spec/components/admin/stats/sdg_component_spec.rb
  spec/controllers/admin/api/stats_controller_spec.rb
  spec/controllers/debates_controller_spec.rb
  spec/controllers/legislation/annotations_controller_spec.rb
  spec/controllers/legislation/answers_controller_spec.rb
  spec/factories/analytics.rb
  spec/models/ahoy/chart_spec.rb
  spec/models/ahoy/data_source_spec.rb
  spec/system/admin/stats_spec.rb
  spec/system/campaigns_spec.rb
  spec/system/notifications_spec.rb
  spec/system/stats_spec.rb
Labels: Bug, Admin, UX, Release notes

#5504 Use a GDPR-compliant configuration for Ahoy
  .rubocop.yml
  app/models/debate.rb
  config/initializers/ahoy.rb
  db/migrate/20240424002959_remove_visit_id_from_debates.rb
  db/migrate/20240424013913_add_visitor_id_and_started_at_index_to_visits.rb
  db/schema.rb
  lib/tasks/consul.rake
  lib/tasks/db.rake
  spec/lib/tasks/db_spec.rb
Labels: security

#5533 Calculate age stats based on the participation date
  app/models/budget/stats.rb
  app/models/concerns/statisticable.rb
  app/models/poll/stats.rb
  app/models/user.rb
  spec/models/budget/stats_spec.rb
  spec/models/poll/stats_spec.rb
  spec/models/statisticable_spec.rb
  spec/models/user_spec.rb
Labels: Bug

#5456 Don't use the cache in admin budget stats
  app/components/admin/stats/budget_balloting_component.rb
  app/components/admin/stats/budget_supporting_component.rb
  app/controllers/budgets/stats_controller.rb
  app/controllers/polls_controller.rb
  app/lib/geozone_stats.rb
  app/lib/percentage_calculator.rb
  app/models/budget.rb
  app/models/budget/stats.rb
  app/models/concerns/statisticable.rb
  app/models/concerns/stats_versionable.rb
  app/models/poll.rb
  app/models/poll/stats.rb
  app/models/stats_version.rb
  config/schedule.rb
  db/migrate/20240408154814_drop_stats_versions.rb
  db/schema.rb
  lib/tasks/stats.rake
  spec/lib/geozone_stats_spec.rb
  spec/models/poll/stats_spec.rb
  spec/models/statisticable_spec.rb
  spec/models/stats_version_spec.rb
  spec/spec_helper.rb
  spec/system/admin/stats_spec.rb
Labels: Bug
