Repository consuldemocracy/consuldemocracy, pull requests merged in 2024-07, with the labels that each got.

#5586 Release version 2.2.0
  CHANGELOG.md
  app/controllers/installation_controller.rb
Labels: Maintenance, 2.2

#5608 Remove kanban management github action workflow
  .github/workflows/kanban.yml
Labels: Maintenance

#5483 Don't run linters in Code Climate
  .codeclimate.yml
Labels: Maintenance

#5611 Use dependabot to update github actions dependencies
  .github/dependabot.yml
Labels: Maintenance

#5493 Add properties-alphabetical-order Stylelint rule
  .stylelintrc.yml
  app/assets/stylesheets/admin.scss
  app/assets/stylesheets/admin/budgets/heading_mode.scss
  app/assets/stylesheets/admin/dashboard/index.scss
  app/assets/stylesheets/admin/menu.scss
  app/assets/stylesheets/admin/search.scss
  app/assets/stylesheets/annotator_overrides.scss
  app/assets/stylesheets/autocomplete_overrides.scss
  app/assets/stylesheets/budgets/investments-list.scss
  app/assets/stylesheets/community.scss
  app/assets/stylesheets/dashboard.scss
  app/assets/stylesheets/datepicker_overrides.scss
  app/assets/stylesheets/icons.scss
  app/assets/stylesheets/layout.scss
  app/assets/stylesheets/layout/admin_header.scss
  app/assets/stylesheets/layout/remote_translations_button.scss
  app/assets/stylesheets/legislation.scss
  app/assets/stylesheets/legislation_process.scss
  app/assets/stylesheets/mixins/buttons.scss
  app/assets/stylesheets/mixins/forms.scss
  app/assets/stylesheets/mixins/layouts.scss
  app/assets/stylesheets/mixins/orbit_bullets.scss
  app/assets/stylesheets/mixins/uploads.scss
  app/assets/stylesheets/notification_item.scss
  app/assets/stylesheets/participation.scss
  app/assets/stylesheets/polls/poll.scss
  app/assets/stylesheets/sdg/goals/show.scss
  app/assets/stylesheets/sdg/related_list_selector.scss
  app/assets/stylesheets/shared/advanced_search.scss
  app/assets/stylesheets/stats.scss
  app/assets/stylesheets/widgets/feeds/participation.scss
Labels: Linters

#5491 Use Rails 7.0 methods to simplify code
  app/components/layout/common_html_attributes_component.rb
  app/controllers/proposals_controller.rb
  app/helpers/shifts_helper.rb
  app/lib/acts_as_paranoid_aliases.rb
  app/models/banner.rb
  app/models/budget.rb
  app/models/budget/investment.rb
  app/models/concerns/globalizable.rb
  app/models/concerns/verification.rb
  app/models/dashboard/administrator_task.rb
  app/models/legislation/process.rb
  app/models/poll.rb
  app/models/poll/question/option.rb
  app/models/proposal.rb
  app/models/proposal_notification.rb
  app/models/user.rb
  db/dev_seeds/flags.rb
  db/dev_seeds/votes.rb
  spec/factory_bot/strategy/insert.rb
  spec/models/poll/poll_spec.rb
Labels: Refactoring, Maintenance
