Repository consuldemocracy/consuldemocracy, pull requests merged in 2024-09, with the labels that each got.

#5685 Update documentation to customize the application
  app/assets/javascripts/application.js
  app/assets/javascripts/custom.js
  app/components/custom/.keep
  app/controllers/custom/.keep
  config/routes.rb
  config/routes/custom.rb
  docs/en/SUMMARY.md
  docs/en/customization/application.md
  docs/en/customization/components.md
  docs/en/customization/controllers.md
  docs/en/customization/css.md
  docs/en/customization/customization.md
  docs/en/customization/gems.md
  docs/en/customization/images.md
  docs/en/customization/introduction.md
  docs/en/customization/javascript.md
  docs/en/customization/models.md
  docs/en/customization/overwriting.md
  docs/en/customization/routes.md
  docs/en/customization/ruby.md
  docs/en/customization/tests.md
  docs/en/customization/translations.md
  docs/en/customization/views.md
  docs/en/customization/views_and_styles.md
  docs/en/features/user_content_translations.md
  docs/es/SUMMARY.md
  docs/es/customization/application.md
  docs/es/customization/components.md
  docs/es/customization/controllers.md
  docs/es/customization/css.md
  docs/es/customization/customization.md
  docs/es/customization/gems.md
  docs/es/customization/images.md
  docs/es/customization/introduction.md
  docs/es/customization/javascript.md
  docs/es/customization/models.md
  docs/es/customization/overwriting.md
  docs/es/customization/routes.md
  docs/es/customization/ruby.md
  docs/es/customization/tests.md
  docs/es/customization/translations.md
  docs/es/customization/views.md
  docs/es/customization/views_and_styles.md
  docs/es/features/user_content_translations.md
Labels: Documentation

#5688 Make "show proposal" tests pass on GitHub Actions
  spec/factories/proposals.rb
  spec/spec_helper.rb
Labels: Flaky bug

#5686 Use bundle exec to run delayed jobs on reboot
  config/schedule.rb
Labels: Bug

#5690 Don't overwrite node_modules with Docker Compose
  docker-compose.yml
Labels: Bug, Devops

#5691 Use a maintained version of PostgreSQL in Docker
  .github/workflows/db_schema.yml
  .github/workflows/tests.yml
  .gitlab-ci.yml
  config/database.yml.gitlab
  docker-compose.yml
Labels: Maintenance

#5692 Fix environment variables and version warnings in Docker
  Dockerfile
  docker-compose.yml
Labels: Maintenance, Devops

#5687 Exclude irrelevant Consul Democracy tests in knapsack
  bin/knapsack_pro_rspec
Labels: Bug, Specs

#5694 Update basic configuration guides
  docs/en/SUMMARY.md
  docs/en/installation/basic_configuration.md
  docs/en/installation/documentation_and_guides.md
  docs/es/SUMMARY.md
  docs/es/installation/basic_configuration.md
  docs/es/installation/documentation_and_guides.md
Labels: Documentation

#5693 Update Docker installation documentation
  docs/en/SUMMARY.md
  docs/en/installation/docker.md
  docs/es/SUMMARY.md
  docs/es/installation/docker.md
Labels: Documentation

#5697 Update recommendations documentation
  docs/en/SUMMARY.md
  docs/en/features/recommendations.md
  docs/es/SUMMARY.md
  docs/es/features/recommendations.md
Labels: Documentation

#5689 Directly select language in remotely translatable tests
  spec/shared/system/remotely_translatable.rb
Labels: Flaky spec, Specs

#5699 Update multitenancy documentation
  docs/en/features/multitenancy.md
  docs/es/features/multitenancy.md
  docs/img/multitenancy/languages-en.png
  docs/img/multitenancy/languages-es.png
Labels: Documentation

#5571 Add new GraphQL types for budget investments
  app/graphql/types/budget_investment_type.rb
  app/graphql/types/budget_type.rb
  app/graphql/types/milestone_type.rb
  app/graphql/types/proposal_type.rb
  app/graphql/types/query_type.rb
  app/models/budget.rb
  app/models/budget/investment.rb
  app/models/comment.rb
  app/models/milestone.rb
  docs/en/features/graphql.md
  docs/es/features/graphql.md
  spec/lib/graphql_spec.rb
  spec/models/comment_spec.rb
Labels: Community Interest

#5637 Make sure we only return public records in the API
  app/graphql/types/budget_type.rb
  app/graphql/types/query_type.rb
  spec/graphql/types/budget_type_spec.rb
  spec/graphql/types/comment_type_spec.rb
  spec/graphql/types/debate_type_spec.rb
  spec/graphql/types/milestone_type_spec.rb
  spec/graphql/types/proposal_notification_type_spec.rb
  spec/graphql/types/proposal_type_spec.rb
  spec/graphql/types/query_type_spec.rb
  spec/graphql/types/user_type_spec.rb
  spec/graphql/types/vote_type_spec.rb
  spec/support/common_actions.rb
  spec/support/common_actions/graphql_api.rb
Labels: Bug, Refactoring

#5706 Bring back GraphQL security limits
  app/graphql/consul_schema.rb
  spec/graphql/consul_schema_spec.rb
Labels: Community Interest, security

#5695 Update GraphQL documentation
  doc/api/examples/ruby/example_1.rb
  doc/api/examples/ruby/example_2.rb
  docs/en/features/graphql.md
  docs/es/features/graphql.md
Labels: Documentation

#5696 Update documentation for Production and Staging servers
  docs/en/SUMMARY.md
  docs/en/installation/create_deploy_user.md
  docs/en/installation/deploying-on-heroku.md
  docs/en/installation/digital_ocean.md
  docs/en/installation/installer.md
  docs/en/installation/mail_server_configuration.md
  docs/en/installation/manual_installation_production.md
  docs/en/installation/servers.md
  docs/en/installation/using-aws-s3-as-storage.md
  docs/es/installation/create_deploy_user.md
  docs/es/installation/deploying-on-heroku.md
  docs/es/installation/digital_ocean.md
  docs/es/installation/generating_ssh_key.md
  docs/es/installation/installer.md
  docs/es/installation/mail_server_configuration.md
  docs/es/installation/manual_installation_production.md
  docs/es/installation/servers.md
  docs/es/installation/using-aws-s3-as-storage.md
  docs/img/digital_ocean/create.png
  docs/img/digital_ocean/droplets.png
  docs/img/digital_ocean/hostname.png
  docs/img/digital_ocean/image.png
  docs/img/digital_ocean/new_ssh.png
  docs/img/digital_ocean/region.png
  docs/img/digital_ocean/server.png
  docs/img/digital_ocean/size.png
  docs/img/digital_ocean/ssh_keys.png
Labels: Documentation

#5707 Update OAuth documentation
  config/secrets.yml.example
  docs/en/features/oauth.md
  docs/es/features/oauth.md
Labels: Documentation
