Repository consuldemocracy/consuldemocracy, pull requests merged in 2024-04, with the labels that each got.

#5457 Fix RSpec/LetBeforeExamples rubocop offense
  spec/system/legislation/questions_spec.rb
Labels: Linters

#5423 Replace rails-assets.org with Node.js packages
  Gemfile
  Gemfile.lock
  app/assets/javascripts/application.js
  package-lock.json
  package.json
Labels: Maintenance, javascript

#5446 Use node packages to install Foundation
  Gemfile
  Gemfile.lock
  app/assets/javascripts/application.js
  app/assets/stylesheets/foundation_and_overrides.scss
  package-lock.json
  package.json
Labels: Maintenance, javascript

#5438 Bump autoprefixer-rails from 8.2.0 to 10.2.5.1
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/.browserslistrc
  app/assets/stylesheets/browserslist
Labels: dependencies

#5447 Bump jquery-file-upload from 9.12.5 to 9.34.0
  Gemfile
  Gemfile.lock
  app/assets/javascripts/application.js
  package-lock.json
  package.json
Labels: dependencies, security, javascript

#5448 Replace SCSS Lint with Stylelint
  .github/workflows/linters.yml
  .pronto_stylelint.yml
  .scss-lint.yml
  .stylelintrc.yml
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/admin.scss
  app/assets/stylesheets/layout/skip_to_main_content.scss
  app/assets/stylesheets/mixins/icons.scss
  app/assets/stylesheets/sdg/goals/show.scss
  package-lock.json
  package.json
Labels: Maintenance, javascript

#5463 Base staging configuration on the production one
  config/environments/custom/production.rb
  config/environments/staging.rb
Labels: Maintenance

#5464 Don't ping search engines after sitemap generation
  config/sitemap.rb
Labels: Maintenance

#5462 Bump sprockets-rails from 3.2.2 to 3.4.2
  Gemfile.lock
  config/application.rb
Labels: dependencies

#5445 Bump foundation-sites from 6.6.2 to 6.7.5
  app/assets/stylesheets/_consul_settings.scss
  app/assets/stylesheets/functions/pow.scss
  app/views/proposals/_support_status.html.erb
  package-lock.json
  package.json
Labels: dependencies, javascript

#5450 Fix font-awesome icons in Internet Explorer 11
  app/assets/stylesheets/in_favor_against.scss
Labels: Bug, UX

#5486 Correctly close <main> tag in admin layout
  app/views/layouts/admin.html.erb
Labels: Bug

#5404 Upgrade Ruby to version 3.2.3
  .gitlab-ci.yml
  .rubocop.yml
  .ruby-version
  Dockerfile
  Gemfile.lock
  README.md
  README_ES.md
  app/components/admin/budgets/actions_component.rb
  app/components/admin/budgets/links_component.rb
  app/components/admin/table_actions_component.rb
  app/controllers/concerns/feature_flags.rb
  app/controllers/concerns/has_filters.rb
  app/controllers/concerns/has_orders.rb
  app/controllers/concerns/remotely_translatable.rb
  app/helpers/application_helper.rb
  app/helpers/link_list_helper.rb
  app/models/remote_translation.rb
  app/models/user.rb
Labels: Documentation, Maintenance

#5481 Replace initialjs-rails with custom avatar code
  Gemfile
  Gemfile.lock
  app/assets/javascripts/application.js
  app/assets/javascripts/users.js
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/avatar.scss
  app/assets/stylesheets/comments/avatar.scss
  app/assets/stylesheets/layout.scss
  app/components/comments/avatar_component.html.erb
  app/components/comments/avatar_component.rb
  app/components/shared/avatar_component.html.erb
  app/components/shared/avatar_component.rb
  app/views/comments/_comment.html.erb
  spec/components/comments/avatar_component_spec.rb
  spec/components/shared/avatar_component_spec.rb
  spec/support/common_actions/comments.rb
  spec/support/matchers/have_avatar.rb
  spec/system/account_spec.rb
  spec/system/debates_spec.rb
  spec/system/proposals_spec.rb
  spec/system/users_spec.rb
Labels: Maintenance, Accessibility

#5475 Install Node packages before compiling assets in Gitlab CI
  .gitlab-ci.yml
Labels: Bug, Maintenance

#5476 Remove task to stop the puma daemon
  config/deploy.rb
Labels: Maintenance

#5465 Upgrade to Rails 7.0
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/components/admin/action_component.html.erb
  app/components/budgets/investments/ballot_component.html.erb
  app/components/budgets/investments/votes_component.html.erb
  app/components/polls/questions/answers_component.html.erb
  app/components/proposals/votes_component.html.erb
  app/controllers/notifications_controller.rb
  app/models/concerns/skip_validation.rb
  config/application.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/initializers/01_filter_parameter_logging.rb
  config/initializers/apartment.rb
  config/initializers/content_security_policy.rb
  config/initializers/cookie_rotator.rb
  config/initializers/cookies_serializer.rb
  config/initializers/inflections.rb
  config/initializers/wrap_parameters.rb
  db/migrate/20240322223950_remove_not_null_on_active_storage_blobs_checksum.active_storage.rb
  db/schema.rb
  spec/controllers/remote_translations_controller_spec.rb
  spec/models/sdg/phase_spec.rb
  spec/system/site_customization/images_spec.rb
Labels: dependencies, Maintenance

#5492 Move custom ActiveStorage service to $LOAD_PATH
  app/models/tenant.rb
  lib/active_storage/service/tenant_disk_service.rb
  spec/lib/active_storage/service/tenant_disk_service_spec.rb
  spec/models/tenant_spec.rb
Labels: Maintenance

#5459 Use buttons for non-GET actions in the admin section
  app/assets/javascripts/application.js
  app/assets/javascripts/send_admin_notification_alert.js
  app/assets/javascripts/send_newsletter_alert.js
  app/assets/stylesheets/admin.scss
  app/assets/stylesheets/admin/action.scss
  app/assets/stylesheets/admin/site_customization/images/index.scss
  app/assets/stylesheets/admin/site_customization/images/table_actions.scss
  app/components/admin/action_component.rb
  app/components/admin/budgets/actions_component.rb
  app/components/admin/budgets/groups_and_headings_component.html.erb
  app/components/admin/site_customization/images/index_component.html.erb
  app/components/admin/site_customization/images/index_component.rb
  app/components/admin/site_customization/images/table_actions_component.html.erb
  app/components/admin/site_customization/images/table_actions_component.rb
  app/components/admin/site_customization/pages/edit_component.html.erb
  app/components/admin/site_customization/pages/edit_component.rb
  app/components/admin/site_customization/pages/new_component.html.erb
  app/components/admin/site_customization/pages/new_component.rb
  app/components/admin/table_actions_component.rb
  app/controllers/admin/poll/questions/answers/images_controller.rb
  app/views/admin/admin_notifications/show.html.erb
  app/views/admin/legislation/draft_versions/edit.html.erb
  app/views/admin/legislation/questions/edit.html.erb
  app/views/admin/newsletters/show.html.erb
  app/views/admin/officials/edit.html.erb
  app/views/admin/poll/questions/answers/images/destroy.js.erb
  app/views/admin/poll/questions/answers/images/index.html.erb
  app/views/admin/site_customization/content_blocks/edit.html.erb
  app/views/admin/site_customization/content_blocks/index.html.erb
  app/views/admin/site_customization/images/index.html.erb
  app/views/admin/site_customization/pages/edit.html.erb
  app/views/admin/site_customization/pages/new.html.erb
  app/views/admin/system_emails/preview_pending/_proposal_notification_digest.html.erb
  config/initializers/routes_hierarchy.rb
  config/locales/en/admin.yml
  config/locales/en/responders.yml
  config/locales/es/admin.yml
  config/locales/es/responders.yml
  config/routes/admin.rb
  spec/components/admin/action_component_spec.rb
  spec/system/admin/admin_notifications_spec.rb
  spec/system/admin/emails/newsletters_spec.rb
  spec/system/admin/legislation/draft_versions_spec.rb
  spec/system/admin/legislation/questions_spec.rb
  spec/system/admin/officials_spec.rb
  spec/system/admin/poll/questions/answers/images/images_spec.rb
  spec/system/admin/site_customization/content_blocks_spec.rb
  spec/system/admin/site_customization/images_spec.rb
  spec/system/admin/site_customization/pages_spec.rb
  spec/system/admin/system_emails_spec.rb
  spec/system/emails_spec.rb
Labels: UX, Accessibility

#5497 Keep rendering pre-Rails7 ActiveStorage images
  config/initializers/active_storage_message_and_cookie_rotator.rb
Labels: Release notes, Maintenance

#5502 Remove duplicated spec
  spec/system/budgets/investments_spec.rb
Labels: Refactoring, Specs
