Repository consuldemocracy/consuldemocracy, pull requests merged in 2024-10, with the labels that each got.

#5708 Update remote census configuration documentation
  docs/en/features/census_configuration.md
  docs/es/features/census_configuration.md
  docs/img/remote_census/feature-disabled-en.png
  docs/img/remote_census/feature-disabled-es.png
  docs/img/remote_census/feature-enabled-en.png
  docs/img/remote_census/feature-enabled-es.png
  docs/img/remote_census/general-information-endpoint-en.png
  docs/img/remote_census/general-information-endpoint-es.png
  docs/img/remote_census/request-data-en.png
  docs/img/remote_census/request-data-es.png
  docs/img/remote_census/request-data-structure-info-en.png
  docs/img/remote_census/request-data-structure-info-es.png
  docs/img/remote_census/response-data-en.png
  docs/img/remote_census/response-data-es.png
Labels: Documentation

#5709 Update local census documentation
  docs/en/features/features.md
  docs/en/features/local_census.md
  docs/es/features/features.md
  docs/es/features/local_census.md
  docs/img/local_census/manage-local-census-csv-en.png
  docs/img/local_census/manage-local-census-csv-es.png
  docs/img/local_census/manage-local-census-en.png
  docs/img/local_census/manage-local-census-es.png
Labels: Documentation

#5710 Update user content translations documentation
  docs/en/features/user_content_translations.md
  docs/es/features/user_content_translations.md
  docs/img/translations/interface_translations/active-interface-translations-en.png
  docs/img/translations/interface_translations/active-interface-translations-es.png
  docs/img/translations/remote_translations/active-remote-translations-en.png
  docs/img/translations/remote_translations/active-remote-translations-es.png
  docs/img/translations/remote_translations/add-api-key-to-secrets.png
Labels: Documentation

#5729 Update translations from Crowdin
  config/locales/cs-CZ/activemodel.yml
  config/locales/cs-CZ/activerecord.yml
  config/locales/cs-CZ/admin.yml
  config/locales/cs-CZ/general.yml
  config/locales/cs-CZ/responders.yml
  config/locales/de-DE/devise_views.yml
  config/locales/fr/activemodel.yml
  config/locales/fr/activerecord.yml
  config/locales/fr/admin.yml
  config/locales/fr/budgets.yml
  config/locales/fr/general.yml
  config/locales/fr/mailers.yml
  config/locales/fr/moderation.yml
  config/locales/fr/settings.yml
  config/locales/fr/verification.yml
  config/locales/gl/activerecord.yml
  config/locales/nl/activemodel.yml
  config/locales/nl/activerecord.yml
  config/locales/nl/admin.yml
  config/locales/nl/general.yml
  config/locales/nl/management.yml
  config/locales/nl/rails.yml
Labels: Translations

#5728 Fix images layout in user content translations
  docs/en/features/user_content_translations.md
  docs/es/features/user_content_translations.md
Labels: Bug, Documentation

#5727 Release version 2.2.1
  CHANGELOG.md
  app/controllers/installation_controller.rb
Labels: Maintenance

#5530 Unify database configuration files
  .gitlab-ci.yml
  config/database-docker.yml.example
  config/database.yml.example
  config/database.yml.gitlab
  docker-compose.yml
  docs/en/installation/docker.md
  docs/es/installation/docker.md
Labels: Refactoring

#5731 Fix warning in hidden proposals spec
  spec/factories/proposals.rb
  spec/system/admin/hidden_proposals_spec.rb
Labels: Specs

#5738 Fix default dashboard actions factories
  spec/factories/proposals.rb
  spec/system/dashboard/dashboard_spec.rb
Labels: Specs

#5741 Make github actions workflows compatible with Ubuntu 24.04
  .github/workflows/auto-author-assign.yml
  .github/workflows/db_schema.yml
  .github/workflows/docker.yml
  .github/workflows/linters.yml
  .github/workflows/pronto.yml
  .github/workflows/tests.yml
Labels: Maintenance

#5742 Fix crash in legislation proposals with videos
  app/models/legislation/proposal.rb
  spec/models/legislation/proposal_spec.rb
  spec/system/legislation/proposals_spec.rb
Labels: Bug

#5747 Make sure requests finish in ballots back link tests
  app/views/layouts/_common_head.html.erb
  spec/system/budgets/ballots_spec.rb
Labels: Flaky spec

#5743 Release version 2.2.2
  CHANGELOG.md
  app/controllers/installation_controller.rb
Labels: Maintenance

#5754 Wait for suggestions in multitenancy and document tests
  spec/system/documents_spec.rb
  spec/system/multitenancy_spec.rb
Labels: Flaky spec

#5498 Use a switch control to toggle selections
  app/assets/javascripts/columns_selector.js
  app/assets/stylesheets/admin/budget_investments/investments.scss
  app/assets/stylesheets/mixins/buttons.scss
  app/components/admin/budget_investments/investments_component.html.erb
  app/components/admin/budget_investments/investments_component.rb
  app/components/admin/budget_investments/row_component.html.erb
  app/components/admin/budget_investments/row_component.rb
  app/components/admin/budget_investments/toggle_selection_component.html.erb
  app/components/admin/budget_investments/toggle_selection_component.rb
  app/components/admin/budget_investments/toggle_visible_to_valuators_component.html.erb
  app/components/admin/budget_investments/toggle_visible_to_valuators_component.rb
  app/components/admin/proposals/toggle_selection_component.html.erb
  app/components/admin/proposals/toggle_selection_component.rb
  app/components/admin/toggle_switch_component.html.erb
  app/components/admin/toggle_switch_component.rb
  app/controllers/admin/budget_investments_controller.rb
  app/controllers/admin/legislation/proposals_controller.rb
  app/controllers/admin/proposals_controller.rb
  app/helpers/budget_investments_helper.rb
  app/helpers/budgets_helper.rb
  app/helpers/proposals_helper.rb
  app/models/abilities/administrator.rb
  app/views/admin/budget_investments/_investments.html.erb
  app/views/admin/budget_investments/_select_investment.html.erb
  app/views/admin/budget_investments/index.html.erb
  app/views/admin/budget_investments/index.js.erb
  app/views/admin/budget_investments/toggle_selection.js.erb
  app/views/admin/budget_investments/toggle_visible_to_valuators.js.erb
  app/views/admin/budgets_wizard/phases/toggle_enabled.js.erb
  app/views/admin/legislation/proposals/_proposals.html.erb
  app/views/admin/legislation/proposals/_select_proposal.html.erb
  app/views/admin/legislation/proposals/toggle_selection.js.erb
  app/views/admin/proposals/_select_proposal.html.erb
  app/views/admin/proposals/index.html.erb
  app/views/admin/proposals/toggle_selection.js.erb
  app/views/admin/shared/_toggle_switch.js.erb
  config/initializers/routes_hierarchy.rb
  config/locales/en/admin.yml
  config/locales/es/admin.yml
  config/routes/admin.rb
  spec/components/admin/budget_investments/toggle_selection_component_spec.rb
  spec/components/admin/budget_investments/toggle_visible_to_valuators_component_spec.rb
  spec/components/admin/proposals/toggle_selection_component_spec.rb
  spec/controllers/admin/budget_investments_controller_spec.rb
  spec/controllers/admin/legislation/proposals_controller_spec.rb
  spec/controllers/admin/proposals_controller_spec.rb
  spec/factories/legislations.rb
  spec/models/abilities/administrator_spec.rb
  spec/system/admin/budget_investments_spec.rb
  spec/system/admin/legislation/proposals_spec.rb
  spec/system/admin/proposals_spec.rb
  spec/views/admin/budget_investments/select_investment_spec.rb
Labels: Admin, UX, Accessibility

#5757 Fill in space in social buttons when options are turned off
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/devise/omniauth_form.scss
  app/components/devise/omniauth_form_component.html.erb
  app/components/devise/omniauth_form_component.rb
  app/helpers/settings_helper.rb
  app/views/devise/sessions/new.html.erb
  app/views/users/registrations/new.html.erb
  spec/components/devise/omniauth_form_component_spec.rb
  spec/system/users_auth_spec.rb
Labels: UX, Refactoring

#5748 Bump graphql from 1.13.22 to 2.0.31
  Gemfile
  Gemfile.lock
Labels: dependencies

#5765 Bump markdown-it from 12.3.2 to 13.0.2
  package-lock.json
  package.json
Labels: dependencies

#5749 Bump foundation-sites from 6.7.5 to 6.8.1
  package-lock.json
  package.json
Labels: dependencies, javascript

#5636 Restrict access to Admin functions by IP Address
  .rubocop.yml
  app/controllers/admin/base_controller.rb
  app/controllers/concerns/ip_denied_handler.rb
  app/controllers/graphql_controller.rb
  app/lib/restrict_admin_ips.rb
  app/models/legislation/annotation.rb
  app/models/machine_learning.rb
  config/deploy.rb
  config/locales/en/general.yml
  config/locales/es/general.yml
  config/secrets.yml.example
  spec/components/account/sign_in_info_component_spec.rb
  spec/controllers/admin/base_controller_spec.rb
  spec/controllers/officing/voters_controller_spec.rb
  spec/controllers/polls/answers_controller_spec.rb
  spec/lib/restrict_admin_ips_spec.rb
  spec/mailers/mailer_spec.rb
  spec/models/poll/answer_spec.rb
  spec/models/tenant_spec.rb
  spec/models/user_spec.rb
  spec/support/common_actions.rb
  spec/support/common_actions/graphql_api.rb
  spec/support/common_actions/secrets.rb
  spec/system/users_auth_spec.rb
Labels: security
