Repository consuldemocracy/consuldemocracy, pull requests merged in 2024-08, with the labels that each got.

#5652 Update local installation instructions
  Dockerfile
  README.md
  README_ES.md
  docs/en/README.md
  docs/en/SUMMARY.md
  docs/en/installation/debian.md
  docs/en/installation/local_installation.md
  docs/en/installation/macos.md
  docs/en/installation/prerequisites.md
  docs/en/installation/ubuntu.md
  docs/en/installation/windows.md
  docs/es/README.md
  docs/es/SUMMARY.md
  docs/es/installation/debian.md
  docs/es/installation/local_installation.md
  docs/es/installation/macos.md
  docs/es/installation/prerequisites.md
  docs/es/installation/ubuntu.md
  docs/es/installation/windows.md
Labels: Documentation

#5651 Upgrade Ruby to version 3.2.5
  .gitlab-ci.yml
  .ruby-version
  Dockerfile
  Gemfile.lock
  README.md
  README_ES.md
  docs/en/README.md
  docs/es/README.md
Labels: Maintenance

#5660 Fix custom locales not taking precedence
  config/application.rb
Labels: Bug
