Repository consuldemocracy/consuldemocracy, pull requests merged in 2025-05, with the labels that each got.

#5966 Vendor foundation_rails_helper/form_builder.rb to drop gem dependency
  Gemfile
  Gemfile.lock
  config/initializers/foundation_form_builder.rb
  vendor/foundation_rails_helper/LICENSE
  vendor/foundation_rails_helper/form_builder.rb
Labels: dependencies, Maintenance

#5496 Upgrade to Rails 7.1
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/shared/banner.scss
  app/components/shared/banner_component.html.erb
  app/components/shared/banner_component.rb
  app/controllers/budgets/investments_controller.rb
  app/models/legislation/annotation.rb
  bin/setup
  config/application.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/initializers/01_filter_parameter_logging.rb
  config/initializers/content_security_policy.rb
  config/initializers/disable_active_storage_pdf_auto_previews.rb
  config/initializers/permissions_policy.rb
  db/schema.rb
  spec/controllers/graphql_controller_spec.rb
  spec/controllers/officing/voters_controller_spec.rb
  spec/controllers/polls/answers_controller_spec.rb
  spec/models/legislation/draft_version_spec.rb
  spec/spec_helper.rb
  spec/system/admin/banners_spec.rb
  spec/system/comments_spec.rb
  spec/system/debates_spec.rb
  spec/system/multitenancy_spec.rb
  spec/system/proposals_spec.rb
Labels: dependencies, Release notes, Maintenance

#5915 Upgrade Ruby to version 3.3.8
  .gitlab-ci.yml
  .ruby-version
  Dockerfile
  Gemfile.lock
  README.md
  README_ES.md
  docs/en/README.md
  docs/es/README.md
Labels: Maintenance
