Repository consuldemocracy/consuldemocracy, pull requests merged in 2025-03, with the labels that each got.

#5898 Use pronto.yml to configure pronto-stylelint
  .pronto.yml
  .pronto_stylelint.yml
Labels: Bug, dependencies

#5899 Fix missing Spanish translation
  config/locales/es/admin.yml
Labels: Bug, Translations

#5901 Downgrade Sass to version 1.77.5
  Gemfile
  Gemfile.lock
  config/initializers/sass.rb
Labels: dependencies, Maintenance

#5886 Add list of open source forks and modifications
  docs/en/SUMMARY.md
  docs/en/open_source/open-source-forks-and-modifications.md
  docs/en/open_source/open_source.md
  docs/es/SUMMARY.md
  docs/es/open_source/open-source-forks-y-modificaciones.md
  docs/es/open_source/open_source.md
Labels: Documentation

#5844 Remove unused CSS
  app/assets/stylesheets/community.scss
  app/assets/stylesheets/dashboard.scss
  app/assets/stylesheets/layout.scss
  app/assets/stylesheets/legislation_process.scss
  app/assets/stylesheets/pages.scss
  app/assets/stylesheets/participation.scss
  app/assets/stylesheets/stats.scss
Labels: Refactoring

#5888 Remove obsolete bin/update script
  bin/update
Labels: Maintenance

#5908 Update instructions to upgrade Consul Democracy
  docs/en/getting_started/update.md
  docs/es/getting_started/update.md
Labels: Documentation

#5890 Remove initializers no longer in Rails
  config/initializers/application_controller_renderer.rb
  config/initializers/backtrace_silencers.rb
  config/initializers/mime_types.rb
Labels: Maintenance

#5891 Fix invalid HTML caused by the dev seeds
  db/dev_seeds/settings.rb
Labels: Bug, Maintenance

#5889 Don't update Spanish in Crowdin
  crowdin.yml
Labels: Translations

#5917 Add missing expectations in system tests
  spec/mailers/mailer_spec.rb
  spec/models/notification_spec.rb
  spec/models/proposal_notification_spec.rb
  spec/shared/system/documentable.rb
  spec/shared/system/flaggable.rb
  spec/shared/system/mappable.rb
  spec/support/common_actions/comments.rb
  spec/support/common_actions/maps.rb
  spec/support/common_actions/users.rb
  spec/system/account_spec.rb
  spec/system/admin/budget_headings_spec.rb
  spec/system/admin/budget_investments_spec.rb
  spec/system/admin/budgets_spec.rb
  spec/system/admin/budgets_wizard/budgets_spec.rb
  spec/system/admin/budgets_wizard/groups_spec.rb
  spec/system/admin/budgets_wizard/headings_spec.rb
  spec/system/admin/budgets_wizard/wizard_spec.rb
  spec/system/admin/legislation/processes_spec.rb
  spec/system/admin/legislation/questions_spec.rb
  spec/system/admin/machine_learning_spec.rb
  spec/system/admin/poll/booths_spec.rb
  spec/system/admin/poll/polls_spec.rb
  spec/system/admin/poll/questions/options/options_spec.rb
  spec/system/admin/site_customization/images_spec.rb
  spec/system/admin/site_customization/information_texts_spec.rb
  spec/system/admin/system_emails_spec.rb
  spec/system/admin/tags_spec.rb
  spec/system/admin/translatable_spec.rb
  spec/system/budget_polls/officing_spec.rb
  spec/system/budget_polls/voter_spec.rb
  spec/system/budgets/executions_spec.rb
  spec/system/budgets/investments_spec.rb
  spec/system/dashboard/polls_spec.rb
  spec/system/debates_spec.rb
  spec/system/documents_spec.rb
  spec/system/emails_spec.rb
  spec/system/legislation/draft_versions_spec.rb
  spec/system/legislation/processes_spec.rb
  spec/system/management/users_spec.rb
  spec/system/moderation/comments_spec.rb
  spec/system/moderation/users_spec.rb
  spec/system/notifications_spec.rb
  spec/system/officing/booth_spec.rb
  spec/system/officing_spec.rb
  spec/system/polls/voter_spec.rb
  spec/system/proposal_notifications_spec.rb
  spec/system/proposals_spec.rb
  spec/system/sdg_management/relations_spec.rb
  spec/system/sessions_spec.rb
  spec/system/site_customization/information_texts_spec.rb
  spec/system/translatable_spec.rb
  spec/system/users_auth_spec.rb
  spec/system/users_spec.rb
  spec/system/valuation/budget_investments_spec.rb
  spec/system/verification/letter_spec.rb
  spec/system/verification/residence_spec.rb
  spec/system/verification/sms_spec.rb
Labels: Flaky spec

#5893 Remove some obsolete code
  app/assets/stylesheets/admin/poll/questions/filter.scss
  app/assets/stylesheets/participation.scss
  app/components/admin/poll/questions/filter_component.html.erb
  app/components/admin/poll/questions/filter_component.rb
  app/components/admin/proposals/index_component.html.erb
  app/components/admin/proposals/index_component.rb
  app/components/admin/proposals/successful_component.html.erb
  app/components/admin/proposals/successful_component.rb
  app/controllers/admin/api/base_controller.rb
  app/controllers/admin/poll/questions_controller.rb
  app/controllers/admin/proposals_controller.rb
  app/controllers/users/registrations_controller.rb
  app/helpers/welcome_helper.rb
  app/models/poll/question.rb
  app/models/user.rb
  app/views/admin/poll/questions/_filter_subnav.html.erb
  app/views/admin/poll/questions/_questions.html.erb
  app/views/admin/poll/questions/index.html.erb
  app/views/admin/poll/questions/show.html.erb
  app/views/admin/proposals/index.html.erb
  app/views/admin/proposals/successful.html.erb
  app/views/layouts/application.html.erb
  app/views/layouts/dashboard.html.erb
  app/views/users/registrations/new.html.erb
  app/views/welcome/_recommended.html.erb
  app/views/welcome/_recommended_carousel.html.erb
  config/locales/en/activerecord.yml
  config/locales/en/admin.yml
  config/locales/en/general.yml
  config/locales/es/activerecord.yml
  config/locales/es/admin.yml
  config/locales/es/general.yml
  config/routes/admin.rb
  db/migrate/20250222222739_remove_poll_questions_video_url.rb
  db/migrate/20250313014205_remove_users_redeemable_code.rb
  db/schema.rb
  spec/components/admin/poll/questions/filter_component_spec.rb
  spec/components/admin/proposals/index_component_spec.rb
  spec/system/admin/poll/questions_spec.rb
  spec/system/admin/translatable_spec.rb
  spec/system/budget_polls/questions_spec.rb
  spec/system/budgets/budgets_spec.rb
  spec/system/budgets/stats_spec.rb
  spec/system/comments/legislation_annotations_spec.rb
  spec/system/management/users_spec.rb
  spec/system/registration_form_spec.rb
  spec/system/tags/budget_investments_spec.rb
  spec/system/users_spec.rb
  spec/system/welcome_spec.rb
  spec/views/welcome/index.html.erb_spec.rb
Labels: Refactoring

#5927 Replace link with button in ballot investment component
  app/assets/stylesheets/budgets/ballot/investment.scss
  app/components/budgets/ballot/investment_component.html.erb
  spec/system/budgets/ballots_spec.rb
Labels: Accessibility
