Repository consuldemocracy/consuldemocracy, pull requests merged in 2025-01, with the labels that each got.

#5819 Remove tasks to upgrade to version 2.2
  .rubocop.yml
  config/initializers/active_storage_message_and_cookie_rotator.rb
  config/initializers/active_storage_message_rotator.rb
  lib/tasks/consul.rake
  lib/tasks/db.rake
  spec/lib/tasks/db_spec.rb
Labels: Maintenance

#5818 Extract CSS files for vendored and admin styles
  app/assets/config/manifest.js
  app/assets/stylesheets/admin.scss
  app/assets/stylesheets/administration-rtl.scss
  app/assets/stylesheets/administration.scss
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/budgets/investments/filters.scss
  app/assets/stylesheets/dashboard_poster.scss
  app/assets/stylesheets/foundation_and_overrides.scss
  app/assets/stylesheets/layout.scss
  app/assets/stylesheets/management/account/edit_password_manually.scss
  app/assets/stylesheets/mixins_and_variables.scss
  app/assets/stylesheets/stats.scss
  app/assets/stylesheets/vendored-rtl.scss
  app/assets/stylesheets/vendored.scss
  app/components/management/account/edit_password_manually_component.html.erb
  app/components/management/account/edit_password_manually_component.rb
  app/views/layouts/_common_head.html.erb
  app/views/management/account/edit_password_manually.html.erb
Labels: UX, Refactoring

#5820 Add Ruby version to Gemfile
  Dockerfile
  Gemfile
  Gemfile.lock
  docs/en/installation/deploying-on-heroku.md
  docs/es/installation/deploying-on-heroku.md
Labels: Maintenance

#5825 Update list of maintainers
  CONTRIBUTING.md
  CONTRIBUTING_ES.md
Labels: Maintenance

#5821 Upgrade Ruby to version 3.2.6
  .gitlab-ci.yml
  .ruby-version
  Dockerfile
  Gemfile.lock
  README.md
  README_ES.md
  docs/en/README.md
  docs/es/README.md
Labels: Maintenance

#5845 Bump pronto-rubocop from 0.11.5 to 0.11.6
  Gemfile
  Gemfile.lock
Labels: dependencies

#5856 Update translations from Crowdin
  config/locales/pt-BR/admin.yml
  config/locales/sv-SE/activerecord.yml
  config/locales/sv-SE/admin.yml
  config/locales/sv-SE/general.yml
  config/locales/sv-SE/settings.yml
  config/locales/tr-TR/activerecord.yml
  config/locales/tr-TR/admin.yml
  config/locales/tr-TR/general.yml
  config/locales/tr-TR/settings.yml
Labels: Translations

#5846 Release version 2.3.0
  CHANGELOG.md
Labels: Maintenance
